### ISSUE TITLE
:bug: Cant navigate inside a sidemenu, if the first item becomes empty somehow

### ISSUE THREAD

**Issue by codewhizz** [jurialmunkey/skin.arctic.fuse#1001]
### Skin section

Widgets

### Current Behavior

![Screenshot 2024-07-13 233916](https://github.com/user-attachments/assets/2863eaf9-ec9a-422b-93cd-88985f3c5df1)
![Screenshot 2024-07-13 233920](https://github.com/user-attachments/assets/fba96404-606d-4744-bf30-5c64091b5902)

I can't navigate to that particular side menu content and it greys out as you can see in above screenshots. It only happens when first item becomes empty.
So whenever my "Continue Watching..." content becomes empty as I have watched all shows pending, then I won't be able to navigate to TV Shows to watch other show.

### Expected Behavior

I should be able to navigate to that sidemenu, even after my 1st section becomes empty

### Steps To Reproduce

![Screenshot 2024-07-13 233840](https://github.com/user-attachments/assets/7748ebba-be64-4234-a10c-89181904abd5)
![Screenshot 2024-07-13 233854](https://github.com/user-attachments/assets/3dcc30d9-dd45-4222-bca0-67a14d5057b9)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by codewhizz** [comment]
BTW, unrelated to this issue. This is my favourite skin on Kodi. Thank you so much for making this sophisticated yet beautiful skin ❤️

**Comment by jurialmunkey** [comment]
Yes this is a known issue, there is not really anyway to solve it in the skin engine. The first widget should be something that will always have content as it is the only "known" ID of the group (the rest of the IDs are dynamically generated).

See duplicates here for e.g.
https://github.com/jurialmunkey/skin.arctic.fuse/issues/945
https://github.com/jurialmunkey/skin.arctic.fuse/discussions/879

You can use a "SkinVariables Custom Filter" widget to create a widget with a fallback path to use if the first is empty:
1. Add a new widget and choose "SkinVariables Custom Filter > Add new ..."
2. Add your continue watching path to the filter
3. Choose "Yes" when prompted to add an extra path and select your fallback path.
4. Set sort/filter/exclude methods to none
5. Save the filter with a name
6. Select the filter you saved and add it as a widget

Currently the filter will be combining both paths together, so we need to change the settings to set it to fallback instead.
1. Go to Video Add-ons > SkinVariables and find your filter
2. Open Context Menu (long press OK) and choose "Edit filters"
3. Switch the "fallback" flag from false to true and then scroll down to the bottom and choose "Save" to save it
4. Reload skin to see the changes (or just watch something so that the widget refreshes).

**Comment by codewhizz** [comment]
Cool! But, I decided to switch from Stacked to Combined as I'm finding this one easy to navigate.

 Thank you for your response anyways! I got to find out one more useful part of this skin.
