### ISSUE TITLE
[BUG] unable to scroll up or down in hubs

### ISSUE THREAD

**Issue by 666jones** [jurialmunkey/skin.arctic.fuse#108]
### Skin section

Home Widgets

### Current Behavior

Hello,

After the most recent update when entering a hub I'm unable to scroll up, down left or right. I see my widgets but I'm unable to select anything.

This is only happening in hubs. (Home page is fine)

I have them set for widgets only. 

Please let me know if you need any further information.

Cheers
Sj

### Expected Behavior

Able to select content within hubs

### Steps To Reproduce

1. Creat a hub.
2. Make it as widget only
3. Go to the hub and try and select a item

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Which version of the skin? I can't recreate so possibly already fixed it.

Also make sure top widget has content and isn't disabled etc.

**Comment by 666jones** [comment]
V0.2.5 I just noticed this was fixed in v0.2.7. I tried to update fuse but it's just not updating

**Comment by 666jones** [comment]
Scratch this it just updated 🤦🏻‍♂️ all good working lovely now. Sorry to have wasted your time

**Comment by jurialmunkey** [comment]
No worries!

I definitely pushed a few changes a bit prematurely in 0.2.5 before they were ready -- so there's been a bit of a flurry of hotfix updates today once I noticed the issues on my tv. 

I'm guessing the auto-update has a timer before it rechecks because I usually have to do a manual recheck for updates for it to come through if I do more than one a day.
