### ISSUE TITLE
Icon in search will not change.

### ISSUE THREAD

**Issue by DROIDshield** [jurialmunkey/skin.arctic.fuse#128]
### Skin section

Other

### Current Behavior

In the search function I've added a addon so I can go straight into search and call up the name of a artist or album and I will get it. This is fine but in the search list the icon i have chosen for this search list will not change.

In my picture it shows a Spotify icon from the default settings I used,  this was changed to an icon from the pallet called song. I have tried multiple icons and even created my own test path and still the icon will not update.

### Expected Behavior

The icon should change and update when picked from the pallet. 

### Steps To Reproduce

Goto search settings and create a widget albums or songs.

Change that icon to a icon of choice.

Update those settings.

Goto search and check that icon to see if ithas updated. 
![20230913_180045](https://github.com/jurialmunkey/skin.arctic.fuse/assets/97023369/e2cb5217-7c7a-4905-9fd8-b4966f3c47d1)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This should be addressed in v0.4 which will be released in next couple of days.

You can get a preview of the new version from the Omega testing branch:
https://github.com/jurialmunkey/skin.arctic.fuse/archive/refs/heads/omega_testing.zip
 
Note that v0.4 no longer uses SkinShortcuts at all and instead uses my own new widget management addon in SkinVariables, so it will not import your old setup. 

I'm working on a script to help import SkinShortcuts setup to SkinVariables which is why I haven't released v0.4 yet.

**Comment by jurialmunkey** [comment]
v0.4 now in main repo.
