### ISSUE TITLE
[Feature] Decouple Spotlight Play Button

### ISSUE THREAD

**Issue by Demonseed-jpg** [jurialmunkey/skin.arctic.fuse#134]
### Skin section

Home Widgets

### Feature description

Currently the Play/Menu button is controlled by the Kodi setting that controls what happens when you click on a movie (play vs. show info).

I think this button would be better suited to a skin setting:
- Always Play/Browse Button
- Always Menu Button
- Kodi Setting Controlled (what it is today)

This setting may potentially be even better as a Spotlight widget setting allowing each Spotlight widget to control them individually as well.

### Why is this feature needed? Please justify and explain.

Having the Spotlight button combo of Play + More Info feels the best for the Spotlight for me.

However this requires me to select the default action when clicking on media to be Play, whereas normally I prefer this setting to be on Show Info. 

This ticket is recommending moving that behavior to a setting so people can keep this behavior, or force the combo to one of the other two options at all times (or controlled by the Widget individually if possible).

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
The problem is that Kodi setting overrides the "Action(Select)" command and forces it to open the info dialog.

If default select is set to "Info" then there is no reliable way to play the item. The Kodi `PlayMedia(PATH)` command will break folders (e.g. TV Shows). Some addons do not correctly set the IsFolder flag or do other actions than `ActivateWindow(videos,PATH,return)` so it is not possible to do those manually.

**Comment by Demonseed-jpg** [comment]
Ah, I see. So just to make sure I am understanding this properly, for you to implement this:

You’d have to switch the button to `PlayMedia(PATH)` to force it to stay as a Play button, but that can have incompatibilities with other addons that don’t properly set the IsFolder flag or do other actions?

**Comment by Demonseed-jpg** [comment]
That makes sense. Is TMDb Helper an addon that does something unconventional as you described or otherwise would be impacted by this, or would it be capable of handling this change fine?

I ask because at least to me, since TMDb Helper is basically used as the engine of the skin in my case, would be totally worth it to me if that’s the case (not impacted negatively by this).

I also can totally understand not implementing the feature, it totally makes sense and could drive issues created here to help solve what would be a setting problem. Maybe a warning message can be populated when forcing the play button is selected (like how it does when you enable installing from unknown sources)?

**Comment by jurialmunkey** [comment]
TMDbHelper would definitely work fine with this change.

It's more that I don't want to add too many behaviour fine-tuning type options because it starts getting a bit unwieldy from the code side of things.

Honestly would just prefer it to be Play + More Info always. The "Menu" button was only ever a band-aid. I'm tempted to just change it anyway and if there's issues to take it up with the specific addon author.

**Comment by Demonseed-jpg** [comment]
Personally, I would also prefer it to be that always😅

**Comment by Demonseed-jpg** [comment]
Thanks for doing that!

I am a huge fan of your work, and as I come back from my Kodi hiatus, I will be using this skin extensively. I always have tons of ideas of how I think the skin could be improved, but if I’m ever submitting too many ideas please feel free to tell me to buzz off.

**Comment by jurialmunkey** [comment]
Please do submit ideas! 

It doesn't bother me if people submit lots of ideas. It's only annoying if people act rude, entitled or impatient. 

As long as people don't get upset if I disagree on some points, then I'm always happy to hear ideas. It's always better when people are engaged with improving the skin.

Also it helps as feedback because sometimes I will have had a similar idea but have had some reservations for whatever reason and it can really help as a springboard to talk the issues out a bit (like in this thread!)

**Comment by Demonseed-jpg** [comment]
That’s great to hear! I did this back a few years ago before my hiatus with TMDb Helper and you’ve always been great at implementing or giving a great explanation as why you wouldn’t, it’s great to see that’s still the case. 😊
