### ISSUE TITLE
custom nodes or dialog lists

### ISSUE THREAD

**Issue by daveftw84** [jurialmunkey/skin.arctic.fuse#135]
### Skin section

Other

### Feature description

any chance we can get custom lists like how you had in aura?
or custom nodes like you have in tmdbhelper?
im trying to fliter menus and orgainze them to make a stacked widget using auto widgets shortcut groups but once the widget gets to the part of opening the (other addons) menus. it stops there, i can click menus and it opens up to addon but the stacked widget wont. so i was hoping you can add this feature 

### Why is this feature needed? Please justify and explain.

this addon seems to be very focused on widgets, i want to make my own widgets

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
You can make nodes using Tmdbhelper's node functionality. It's not limited to tmdbhelper paths - you can use any path
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Node-Customisation

The other option is to use the library node editor addon.

**Comment by Demonseed-jpg** [comment]
> You can make nodes using Tmdbhelper's node functionality. It's not limited to tmdbhelper paths - you can use any path https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Node-Customisation
> 
> The other option is to use the library node editor addon.

Would it be possible to integrate a node builder into TMDb Helper, so that this can be built and designed in-app instead of having to do it manually by creating and editing a file?

I’m happy to make another issue for this, just seemed really related and could potentially solve the requester’s ask in-app so I thought I’d ask here.

**Comment by jurialmunkey** [comment]
It already does have an option in the context menu to Add/Remove from nodes. It's just limited to TMDbHelper contextmenu because I can't modify contextmenus for other addons/library.

**Comment by jurialmunkey** [comment]
But also, that's what the Library Node Editor does. It's a little more complicated to use Library Node Editor because it has more functionality but it can do the same thing.

**Comment by Demonseed-jpg** [comment]
Ah, understood. Thank you very much!

**Comment by jurialmunkey** [comment]
Also the command to add a node in TMDbHelper is 
`RunScript(plugin.video.themoviedb.helper,make_node)`

So you can map this to a button and it should work for any focused folder.

**Comment by jurialmunkey** [comment]
Added a "Add Node" make_node button to the side command palette in the context menu under "Similar". The button will only display if the item is a folder and you're inside the media window (i.e. not from widgets).

Also added a "TMDbHelper Nodes" option in the skinshortcuts menu to help get to those nodes quicker when setting up.

**Comment by Demonseed-jpg** [comment]
That’s awesome, thanks jurialmunkey!

**Comment by daveftw84** [comment]
> It already does have an option in the context menu to Add/Remove from nodes. It's just limited to TMDbHelper contextmenu because I can't modify contextmenus for other addons/library.

"legally?"
because autowidget does it. so did superfav

**Comment by daveftw84** [comment]
dialog lists was amazing, would love to see that return. thanks for taking the time for my cries

**Comment by jurialmunkey** [comment]
>  because autowidget does it. so did superfav

These don't modify the context menu for the listitem. 

What they do is they add a "global" context menu entry at the end of all context menus - adds a lot of clutter and also overhead in evaluating the conditions when the context menu is generated, so I don't like doing that unless it is part of a separate optional context menu addon (e.g. like the optional [TMDbHelper context menu addon](https://github.com/jurialmunkey/context.themoviedb.helper) which adds the "TMDbHelper Options" entry).

Global context menu entries are no different to the button I've added in the side menu - except this is controlled by the skin rather than forced by an addon.

**Comment by daveftw84** [comment]
Oh I thought it was one of the differences between unofficial and official
add ons.
This is my facebook memory today haha.
