### ISSUE TITLE
an option to limit number of items show in widgets

### ISSUE THREAD

**Issue by daveftw84** [jurialmunkey/skin.arctic.fuse#136]
### Skin section

Home Widgets

### Feature description

i would like to be able to cap my widgets at the same size that tmdb helper is capped at, 25.
alot of my menus has too many items, i tried to split it up using addons like auto widget but failed. also last played widget for live tv is showing too much.

### Why is this feature needed? Please justify and explain.

performance 

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by woodside007** [comment]
I believe there's already an option to limit widgets.
![Screenshot 2023-09-19 140748](https://github.com/jurialmunkey/skin.arctic.fuse/assets/8515006/aac09966-81f7-4910-8e75-8b81c53c787a)

**Comment by jurialmunkey** [comment]
Note that limiting widget item count won't improve loading speed because the limit only changes how many items *display* in the list, not how many *load* (which is controlled by the plugin).

All the items in the plugin directory will still load as normal inside the plugin; the limit is only applied after it hands over all the items to Kodi which will then limit how many items from that directory are displayed.

On very large lists you might get a small performance increase but the main benefit is for sorting: it's faster for Kodi to sort 20 items than 200; and is also useful to make specific widgets e.g. limit=10 sortby=rating gives a "Top 10" widget.

**Comment by daveftw84** [comment]
Well noted. any effect with the pvr menus? Like recently played?  Or skin
doesnt control that either?

 But having soo many items printed on the actual screen does nothing?  I
always felt like I killed it when I loaded too many big menus on my low
power devices, I have code of sworn i feel a difference,  especially during
the boot up And overall feel of the home screen.

**Comment by jurialmunkey** [comment]
> Well noted. any effect with the pvr menus? Like recently played?

Possibly since that's internal but I'm not sure. I'd expect Kodi still retrieves the full list from the database before limit is applied.

> But having soo many items printed on the actual screen does nothing?

You might get a navigation performance increase but not a loading one -- i.e. you might have smoother navigation with fewer items but it won't affect how long it takes the list in each widget to load.

The other main benefit you might find with fewer items is that you're less likely to have new items that have new artwork needing to be downloaded, processed, and cached by Kodi's background artwork loader. 

That makes it more likely that background artwork loader thread is blocking up your network (downloading new artwork), or cpu (processing, resizing and resampling artwork), or disk (writing processed artwork to disk cache) -- and those things could all affect performance.

Note that only impacts items visible on screen -- it'd be the same cost if you limited every list to 10 items but every single one had new artwork. It's just that by having more items in general, that scenario is more likely overall.

**Comment by daveftw84** [comment]
sounds like it's catching page two But processing page one
