### ISSUE TITLE
[BUG] Submenu sorting not working for titles

### ISSUE THREAD

**Issue by RentreX** [jurialmunkey/skin.arctic.fuse#145]
### Skin section

Home Widgets

### Current Behavior

When using the submenu for titles (ie: A -C, D - G etc) it does not show in alphabetical order. 

I have even tried setting the sort method to name and title.

### Expected Behavior

For the submenu to display in alphabetical order

### Steps To Reproduce

Use the default submenu for title. 

Change the sorting method (does not help)

### Screenshots and Additional Info

![20231003_142747](https://github.com/jurialmunkey/skin.arctic.fuse/assets/60731904/62ffa5f7-fa7f-4b33-ba78-a401d552269b)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Do you have a debug log for this one too? I can't reproduce this issue either. 

Are you using some unusual version of Kodi or getting library content in some unusual way? -- because these are just standard smart playlists and should follow its sort method like any other smart playlist.

For instance, here's the playlist for D-G:
https://github.com/jurialmunkey/skin.arctic.fuse/blob/nexus/extras/hub/movies/titles/D-G.xsp

There's not really anything to it -- it just matches if title starts with D,E,F, or G and then sorts by title.

**Comment by RentreX** [comment]
I have also just checked tv shows (screenshot is from movies).

The  order for the submenu for tv shows is W - Z, L - O, H - K, T - V, D - G, A - C, P - S.

Which as you can see that isn't alphabetical order. Though the order is different from movies to tv shows

**Comment by jurialmunkey** [comment]
Oh right, I see what you mean - I missed that at first and thought you were talking about content inside the widget.

That's very unusual - the default sorting value (None) should be filename order. The "title" sort method won't do anything since these don't have titles, only labels -- but I'll see if setting default sort method to "label" helps at all.

**Comment by RentreX** [comment]
No worries. Glad we finally both understood what I was trying to say. That is my fault.

Yeah I didn't think changing the sort type would be the problem at all.

Thanks

**Comment by RentreX** [comment]
I have just downloaded 0.2.32 and can confirm this is now working as expected.
