### ISSUE TITLE
[BUG] Genre selection in Library does not select

### ISSUE THREAD

**Issue by RentreX** [jurialmunkey/skin.arctic.fuse#146]
### Skin section

Library Views

### Current Behavior

Currently selecting a genre  from the explore menu when you go to your library does not select a genre.

It refreshes the library but does not select the genre and does not filter the library at all.

### Expected Behavior

When selecting a genre it should filter out the library and only show the videos with the selected genre 

### Steps To Reproduce

Go to Library (movies or tv shows)
Go to explore
Select genre
Pick a genre

### Screenshots and Additional Info

![20231003_143255](https://github.com/jurialmunkey/skin.arctic.fuse/assets/60731904/0662b96f-33a5-4e4d-b0a1-d432bdcea189)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Do you have a debug log of this issue? I can't reproduce it

**Comment by RentreX** [comment]
https://paste.kodi.tv/avujulihes.kodi

Every time I click on a genre in the library it throws this error:
error <general>: Keymapping error: no such action 'container.update()' defined

**Comment by jurialmunkey** [comment]
> error : Keymapping error: no such action 'container.update()' defined

Yeah that'd be why it isn't working -- that's the command used to update the current library view container with the new path.

The question is why the command isn't working because it is a default Kodi builtin command. I've never seen this error before, it's really strange.

**Comment by RentreX** [comment]
Is there anything that I could try and do to figure out the reasoning for it?

I have uninstalled and reinstalled the skin aswell and that has not helped at all.

I have just checked AH2 and it works correctly.(Library/ filter/ genre/ "select genre"/ "click okay"/

Also on AF if I go to discover feature (in search) and select genre, it works as excepted.

![20231004_115049](https://github.com/jurialmunkey/skin.arctic.fuse/assets/60731904/6c5ac136-f201-410d-9180-f16084783172)
![20231004_115159](https://github.com/jurialmunkey/skin.arctic.fuse/assets/60731904/c54f67b5-0033-4bd1-acbf-43d3b7f675cf)

**Comment by RentreX** [comment]
I also just saw that when you click on genre in discovery it gives a tick before refreshing.

Though in library it does not stick the tick before refreshing.

**Comment by jurialmunkey** [comment]
> I have just checked AH2 and it works correctly.(Library/ filter/ genre/ "select genre"/ "click okay"/

This uses a different window/method which is managed internally by Kodi. You can get to that advanced filter by clicking the "filter" icon in the buttons under the row.

> Also on AF if I go to discover feature (in search) and select genre, it works as excepted.

Yeah, this is also a different method where the filtering is managed via the SkinVariables plugin. This method can only be used on widgets, not the library.

> I have uninstalled and reinstalled the skin aswell and that has not helped at all.

Reinstalling the skin won't do anything because this is an issue with Kodi itself. The `Container.Update()` command is a standard builtin command for Kodi so it should work. 
https://kodi.wiki/view/List_of_built-in_functions#GUI_container_built-in's

Without this command, there is no way for a skin to update the library container, so it is a fairly significant issue with your Kodi install which will have knock-on effects in a lot of areas.

It'd be like if `PlayMedia()` stopped being recognised as a command -- then it would be impossible for the skin to play anything manually from a button.

**Comment by RentreX** [comment]
A clean install fixed it. I really wonder how long that was happening for.
