### ISSUE TITLE
[BUG] Clearlogos showing up inconsistantly

### ISSUE THREAD

**Issue by Logs22** [jurialmunkey/skin.arctic.fuse#15]
### Skin section

Home Widgets

### Current Behavior

When browsing along the home menu/home widgets, clear logos don't always show up

### Expected Behavior

Clear logos should show up

### Steps To Reproduce

Browse any tmdbhelper widget until clear logo doesn't populate

### Screenshots and Additional Info

![Screenshot 2023-07-26 194622](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65024236/92c5c97c-a6de-4038-a96f-0b9876f59d5a)

The clear logo will populate if you pull up the context menu < manage artwork < select artwork. You don't even have to select any artwork, but this seems to trigger a refresh of the artwork for the item and will cause the clear logo to then populate.

The other solution I have found is enabling fanart plugin and widget artwork in TMDBHelper after inputting my fanart api key, but this slows down loading and isn't recommended per the addon so I wanted to report it instead of using that.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Do you have fanarttv service lookups enabled in TMDbHelper?

The plugin/widget options shouldn't be necessary, but you still need to input a fanarttv client key. Also, you *must* enable service lookups (if you disabled this option then it is working correctly because you told it not to lookup artwork).

> The other solution I have found is enabling fanart plugin and widget artwork in TMDBHelper after inputting my fanart api key, but this slows down loading and isn't recommended per the addon so I wanted to report it instead of using that.

I wouldn't worry about this too much. 

Yes, it does very slightly slow down initial loading of the widget because it forces the lookup to happen before the items are displayed, but that's only the first time before the artwork details are cached. Once the artwork details for an item are cached, it should be just as fast as when the option is disabled.

Fanarttv artwork details are cached for 14 days, so its not like these details get refreshed often. I leave these on because the experience is much nicer when the widget already has the artwork ready and you dont need to wait for the service to look it up.

**Comment by Logs22** [comment]
That seems to have fixed it except for the items that are cached, thank you for the awesome new skin!
