### ISSUE TITLE
[BUG] Category/Submenu fixedlists with allowed movement are forced by Kodi to focus second position

### ISSUE THREAD

**Issue by woodside007** [jurialmunkey/skin.arctic.fuse#157]
### Skin section

Home Widgets

### Current Behavior

The default focused position of the categories menu item is landing on the second menu item instead of the first after last update.  

### Expected Behavior

After starting Kodi I would expect the default focused menu position for the categories menu items to land on the first menu item instead of the second menu item.

### Steps To Reproduce

Start Kodi
Focused position lands on second menu item

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by AakashC2020** [comment]
Hi @jurialmunkey, 

I'm also facing this exact same issue like @woodside007 after the latest update. Could you please check and kindly resolve?

**Comment by AakashC2020** [comment]
Hi @jurialmunkey

Sorry to ask again, but this is a kind request to resolve this issue as it's really looking bad to see the 2nd menu items loading first instead of the ones under the 1st menu item.

This issue started after the last update, earlier everything was fine. Thanks in advance!

**Comment by jurialmunkey** [comment]
@AakashC2020 im well aware of this issue. Im not ignoring it - so far I cannot fix it.

It is a kodi issue to do with the way fixed lists work. Kodi forces the second position to be focused because the list is setup to use that as the fixed point for scrolling - - setting the fixed point to the first position to "solve" it means it is impossible to know if there are more to the left

I do not know the solution because I do not know c++ to fix the bug in Kodi's skin engine.

**Comment by jurialmunkey** [comment]
@AakashC2020 im well aware of this issue. Im not ignoring it - so far I cannot fix it.

It is a kodi issue to do with the way fixed lists work. Kodi forces the second position to be focused because the list is setup to use that as the fixed point for scrolling - - setting the fixed point to the first position to "solve" it means it is impossible to know if there are more to the left

I do not know the solution because I do not know c++ to fix the bug in Kodi's skin engine.

Requesting that I fix something repeatedly is not going to make me be able to fix it faster - if I don't fix something quickly then generally it means I don't know what the solution is.

**Comment by AakashC2020** [comment]
> @AakashC2020 im well aware of this issue. Im not ignoring it - so far I cannot fix it.
> 
> It is a kodi issue to do with the way fixed lists work. Kodi forces the second position to be focused because the list is setup to use that as the fixed point for scrolling - - setting the fixed point to the first position to "solve" it means it is impossible to know if there are more to the left
> 
> I do not know the solution because I do not know c++ to fix the bug in Kodi's skin engine.
> 
> Requesting that I fix something repeatedly is not going to make me be able to fix it faster - if I don't fix something quickly then generally it means I don't know what the solution is.

Hi @jurialmunkey,

I'm extremely sorry if I've annoyed you. I was not sure if you've noticed this issue, hence I messaged you twice. I'm really sorry about that! I was actually not aware that this is a Kodi issue and thought it might be a simple error on the code since the last update which could be fixed easily. You're one of the best developer in this field that I've ever known and the most friendly person also who listens to everyone every time. It was really not my intention to chase you. Please take your time and see if this issue can be resolved or not. Thanks again for the great work that you've been doing each and every day for everyone! You're an awesome person! 🙂❤️

**Comment by jurialmunkey** [comment]
>I was not sure if you've noticed this issue

I get a github notification on my phone whenever someone opens or comments on an issue thread, and also whenever someone tags me -- so I've definitely seen this issue since I got five notifications about it...

> thought it might be a simple error

Any bug which is simple to fix, I fix practically straightaway.

If I don't fix a bug straightaway, it typically means either: (1) it is complicated to fix; (2) the standard "fix" will cause other issues; (3) I'm unable to reproduce it; (4) I'm uncertain of the cause; (5) it will be made redundant by an incoming update; (or (6) I'm busy).

In this case, (2) applies: The standard "fix" of setting focusposition=0 creates other issues -- namely, it makes it impossible to tell if you are on the first item or if there are more items available to scroll to on the left.

Without modifying Kodi code, the alternative for keeping focusposition=1 and allow movement is to make the real list 0% opacity and then overlay a fake list in the position I want. That's a complicated solution.

**Comment by AakashC2020** [comment]
> > I was not sure if you've noticed this issue
> 
> I get a github notification on my phone whenever someone opens or comments on an issue thread, and also whenever someone tags me -- so I've definitely seen this issue since I got five notifications about it...
> 
> > thought it might be a simple error
> 
> Any bug which is simple to fix, I fix practically straightaway.
> 
> If I don't fix a bug straightaway, it typically means either: (1) it is complicated to fix; (2) the standard "fix" will cause other issues; (3) I'm unable to reproduce it; (4) I'm uncertain of the cause; (5) it will be made redundant by an incoming update; (or (6) I'm busy).
> 
> In this case, (2) applies: The standard "fix" of setting focusposition=0 creates other issues -- namely, it makes it impossible to tell if you are on the first item or if there are more items available to scroll to on the left.
> 
> Without modifying Kodi code, the alternative for keeping focusposition=1 and allow movement is to make the real list 0% opacity and then overlay a fake list in the position I want. That's a complicated solution.

Hi @jurialmunkey,

Sure. I can completely understand that this is a very complicated issue. I was not aware that Kodi has made a change to fixed lists recently which resulted in focusing the second position of the list, as I've not noticed this issue in the earlier versions of Arctic Fuse. The fake list overlay method definitely sounds quite complicated as that will take a lot of effort as per your description and may need a lot of R&D. Being a great fan of your work since the days of the first Arctic skins I'm sure you'll find some sort of solution to this. Even if not, I can move the item that I want to be focused at the first skin load to the second menu position and can adjust for now. Thank you so much for the detailed explanation! 👍🏻

**Comment by jurialmunkey** [comment]
This is not a kodi change. 

I am deliberately setting the list to use the second item in the list as the fixed position to show that there are items to the left.

The difference is that the list also has a movement value of 2. This means that when you reach the first item, focus is allowed to then *shifts* to position 1 rather than the list scrolling. And likewise, when you reach the end of the list, focus shifts to position 3 and 4.

This is done in the skin for two reasons - the movement value makes it easier for mouse/touch interaction because it means the list will not scroll wildly when the mouse focuses other items within the allowed movement, and, secondly, the fixed position being on 2 allows you to tell if there are more items available on both sides due to the position the list scrolls out. 

Normally if you use this type of approach in the library, kodi will treat it properly and start the list on item 1. However there is some bug in the skinning engine  where it does not correctly focus the first item when these settings are set and instead immediately jumps to the fixed position.

**Comment by AakashC2020** [comment]
> This is not a kodi change.
> 
> I am deliberately setting the list to use the second item in the list as the fixed position to show that there are items to the left.
> 
> The difference is that the list also has a movement value of 2. This means that when you reach the first item, focus is allowed to then _shifts_ to position 1 rather than the list scrolling. And likewise, when you reach the end of the list, focus shifts to position 3 and 4.
> 
> This is done in the skin for two reasons - the movement value makes it easier for mouse/touch interaction because it means the list will not scroll wildly when the mouse focuses other items within the allowed movement, and, secondly, the fixed position being on 2 allows you to tell if there are more items available on both sides due to the position the list scrolls out.
> 
> Normally if you use this type of approach in the library, kodi will treat it properly and start the list on item 1. However there is some bug in the skinning engine where it does not correctly focus the first item when these settings are set and instead immediately jumps to the fixed position.

Hi @jurialmunkey,

Thanks again for the detailed explanation! I can now clearly understand the reasons for the issue. It's really a problem to think about. Hope you'll find some solution soon like you always do. Thank you!
