### ISSUE TITLE
[BUG] Card View not showing complete view

### ISSUE THREAD

**Issue by The-Crow-Den** [jurialmunkey/skin.arctic.fuse#158]
### Skin section

Home Widgets

### Current Behavior

Showing half of the final movie card item when selected.

### Expected Behavior

Show full movie card

### Steps To Reproduce

Go to the end of a widget using the card style.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Screenshot? I can't reproduce this issue. What resolution and aspect ratio?

**Comment by The-Crow-Den** [comment]
Using it on a 4k tv 16:9
![6FC2F4FE-DEEA-491A-9BD0-8BFC99B3877A](https://github.com/jurialmunkey/skin.arctic.fuse/assets/100861929/73cce24a-8466-4412-8260-d7636624b2dc)

**Comment by jurialmunkey** [comment]
Looks like tv overscan.

Need to disable overscan in your TV settings, or if you cant do that then need to recalibrate the screen using Kodi's screen calibration tool.

The other possibility is that you're using a resolution in kodi which is not compatible with your TV.

**Comment by jurialmunkey** [comment]
Skin can't change your resolution, so it's something to do with Kodi.

Could be a coincidence that it happened at same time as update, or possibly something happened while kodi was writing new guisettings.xml and the file got corrupted and reverted to an old version etc.

Other possibility is that your TV started incorrectly reporting its display modes (or did so temporarily which force kodi to switch its resolution)

If you can't get it to change back in kodi settings and you've got a spare hdmi port on your tv (assuming you use hdmi) then try switching to a different one - - something that happened on my TV that drove me nuts for a while was that one of my hdmi ports I was using started dying and sometimes wouldn't correctly report the video modes it supported, so that would mess up my display resolution. Bit of a long shot as it was a pretty specific issue with my system but sometimes it can be as simple as unplugging and replugging to get the display modes to update/refresh.
