### ISSUE TITLE
Update 3.0 Fuse last poster cut off widget cut off

### ISSUE THREAD

**Issue by derrgoo** [jurialmunkey/skin.arctic.fuse#159]
### Skin section

Home Widgets

### Current Behavior

See picture. Last poster cut off widget. 

### Expected Behavior

Show all poster and arrow 

### Steps To Reproduce

Scroll widget to right. 

### Screenshots and Additional Info

![IMG_8916](https://github.com/jurialmunkey/skin.arctic.fuse/assets/63697905/beb8c2e2-21fe-494c-beed-8d85b476560b)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
What screen aspect ratio?

**Comment by derrgoo** [comment]
I just tested on my shield pro on 65 inch tv and it is not cut off but not showing the last movie in the widget. The version just before this loves the widget to left so you see all.

**Comment by derrgoo** [comment]
https://github.com/jurialmunkey/skin.arctic.fuse/assets/63697905/3428022d-b270-4168-89a6-ba5aa2734e57

**Comment by jurialmunkey** [comment]
Again, what is your screen aspect ratio? This is a screen aspect ratio issue so I need to know what aspect ratio you're using.

**Comment by jurialmunkey** [comment]
Also it looks like your screen is incorrectly calibrated.

**Comment by derrgoo** [comment]
16:9 standard. This first time ever done this and also on my Mac Pro. Version before okay.

**Comment by jurialmunkey** [comment]
If it is actually 16:9 then it looks like your screen is incorrectly calibrated or you're using the wrong resolution. Those posters in your video are significantly squashed.

A 16:9 screen ratio will show 7 full posters yet yours is only showing 6, and that's because your resolution is not matching your screen.

**Comment by derrgoo** [comment]
Seems to be my TV's. I reset them and still I only see 6 posters. I checked my shield also calibrated and all shows to fit on screen.

**Comment by derrgoo** [comment]
I reloaded 2.36 and this gives it the 7 posters and everything looks crisp. So 3.0 blows everything up and even see low resolution on all graphics. I have both tv and shield calibrated.

**Comment by jurialmunkey** [comment]
Got a debug log?
Skin shouldn't change your resolution.

**Comment by derrgoo** [comment]
[https://www.dropbox.com/scl/fi/ras8ru75g8ly6skaai084/kodi.log?rlkey=pqfoua2h8gfmbmk01scwkvzgd&dl=0]()

**Comment by derrgoo** [comment]
Let me know if that works for my log.

**Comment by jurialmunkey** [comment]
> 2023-10-14 17:34:12.907 T:40015    info <general>: GUI format 720x480, Display Windowed

This not a 16:9 display. Also that is very low resolution.

A skin can't control your resolution.

**Comment by jurialmunkey** [comment]
Also Macbook pro has a 3:2 screen not a 16:9 screen. These are massively different aspect ratios.

**Comment by jurialmunkey** [comment]
The video of your screen looks like you are using a 3:2 resolution squashed into a 16:9 screen.

**Comment by jurialmunkey** [comment]
For example:

Here is a true 3:2 screen resolution. Notice that it displays six posters across (not seven) but it is not squashed.

![screenshot00173](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/a8c3d329-b73c-4d99-9677-0d141c0bf485)

Now here is a 3:2 screen resolution which has been windowed in 16:9. Notice how it looks squashed exactly like in your video

![screenshot00174](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/5ad11213-dad3-47e9-b76d-a4d654abc4b1)


Now here is a *true* 16:9 resolution after reloading the skin after changing resolution.

![screenshot00175](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/5f0dbfb8-0291-4b83-b8f4-d38db3a4dbef)


These screenshots all taken with version 0.3


I've got a Surface Laptop Studio which also has a 3:2 screen. If you adjust the screen and the screencast or switch to another monitor with a different aspect, you need to reload the skin using the `ReloadSkin()` command so that Kodi will update to use the new resolution.

The big question though is why your other monitor output is only at 480p.

**Comment by derrgoo** [comment]
My MacBook Pro I actually made font bigger because my work laptop and forgot to switch back!

I tried reinstalling everything and I am happy to report it now looks like yours again with 7 and updated to 3.0. As usual the "user" issue lol. Thanks you for spending your time helping me.

**Comment by jurialmunkey** [comment]
No worries. glad we got to the bottom of it!
