### ISSUE TITLE
[BUG] "More items" still shows for widgets

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.fuse#172]
### Skin section

Home Widgets

### Current Behavior

Testing with Omega Alpha 3, I set "Show more item on limited widgets" to off. This works for video, music containers, but I noticed that for a PVR widget, the "more" item was still present.

### Expected Behavior

"more" item should not be present  if "Show more item on limited widgets" is set to off.

### Steps To Reproduce

Set "Show more item on limited widgets" to off.
Configure a PVR widget (I used recent channels)

### Screenshots and Additional Info

![screenshot00005](https://github.com/jurialmunkey/skin.arctic.fuse/assets/67786207/82d10cce-3e1d-4bda-9b1f-839a178fb561)
![screenshot00007](https://github.com/jurialmunkey/skin.arctic.fuse/assets/67786207/ce48fb8b-4e92-41e4-bf4b-7c16f0bdc57b)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
If you change that specific widget to a different type of widget does the more item disappear? (assuming of course the widget is limited and has more items to show).

In Omega, the "more" item itself is created by Kodi internally. The skin simply sets an attribute to `never|auto|always` to determine how the container should act - So I think this might be a bug with Kodi rather than the skin but want to make sure I haven't just missed the attribute somewhere.

**Comment by jurialmunkey** [comment]
Ah just realised you're still on Alpha 3. I think that was released before the commit which added this attribute.

Does it still happen with Beta 1 / Nightlies ?

**Comment by DROIDshield** [comment]
@berkhornet could I ask what PVR are you using thanks?

**Comment by berkhornet** [comment]
@jurialmunkey - Omega Beta 1 fixed it - good spot! Many thanks for your help

**Comment by berkhornet** [comment]
> @berkhornet could I ask what PVR are you using thanks?

@DROIDshield - I am using IPTV Simple Client
