### ISSUE TITLE
[BUG] "Skin Shortcuts could not build menu"

### ISSUE THREAD

**Issue by ditydot** [jurialmunkey/skin.arctic.fuse#176]
### Skin section

Home Widgets

### Current Behavior

After changing a skin option from "Horizontal (Classic)" to "Vertical (Detailed)", the Skin Shortcuts dependency fails to build the home menu.

1. All that's shown after dismissing the error is the spotlight widget, but you can't interact with it.
2. I have to use the Kore app to launch the settings menu
3. Reinstalling the Skin Shortcuts add-on doesn't fix the issue
4. Reinstalling Arctic Fuse didn't fix the issue

### Expected Behavior

Skin Shortcuts should rebuild the menu after changes are made.

### Steps To Reproduce

1. Open settings
2. Change skin variable "combined style" from "Horizontal (Classic)" to "Vertical (Detailed)"
3. Reload skin

### Screenshots and Additional Info

https://paste.kodi.tv/ukebujubuj

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Log please

**Comment by ditydot** [comment]
> Log please

https://paste.kodi.tv/ukebujubuj

**Comment by jurialmunkey** [comment]
> AttributeError: 'Template' object has no attribute 'tree'

Hmmm, this is an unusual error. Suggests that the template.xml file didn't get generated correctly but I'd expect there would've been other errors if that was the case.

Can you get me the template.xml file from here?
`kodi/addons/skin.arctic.fuse/shortcuts/template.xml`

If the file exists and it isn't corrupted then possibly there's not enough of a wait between it being written and skinshortcuts reading for the disk cache to flush properly.

You could try bumping the sleep value here (try maybe 2 seconds instead of 0.5)
https://github.com/jurialmunkey/skin.arctic.fuse/blob/35265ce470f1ad06c3f5b1c628dfba757c23e313/shortcuts/skinvariables-buildtemplate.json#L13

And then increase the build version here to force it to rebuild:
https://github.com/jurialmunkey/skin.arctic.fuse/blob/35265ce470f1ad06c3f5b1c628dfba757c23e313/shortcuts/skinvariables-generator.json#L5

**Comment by ditydot** [comment]
Here you go: [template.zip](https://github.com/jurialmunkey/skin.arctic.fuse/files/13066085/template.zip)

In the meantime, I'll see if I can implement those changes.

**Comment by ditydot** [comment]
Just an update: Changing those two values didn't fix the problem.

**Comment by jurialmunkey** [comment]
Thanks, that's really useful. I see the issue -- your profile name has a special character `&` which is breaking the xml because that's a reserved character.

I'll have a look into best way to address this scenario in the code -- but if you want to fix it immediately, just rename your profile to replace `&` with `and`

**Comment by ditydot** [comment]
Oh my god, to think the fix would be that simple. I made the change and so far, so good.
