### ISSUE TITLE
:bug: Fonts dont fit the screen in some menus

### ISSUE THREAD

**Issue by patkino** [jurialmunkey/skin.arctic.fuse#18]
### Skin section

Home Widgets

### Current Behavior

Long labels don't fit the lines in spotlight and videoOSD, as the font is too large

### Expected Behavior

Fit the screen

### Steps To Reproduce

Select e.g. video on YouTube with a long title. Check spotlight, ply the video, check videoOSD

### Screenshots and Additional Info

![IMG-20230728-WA0002](https://github.com/jurialmunkey/skin.arctic.fuse/assets/85682547/e074c739-962a-43b2-b4d5-fd28ba7380ec)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I can't reproduce this issue.

What screen resolution are you using? What font set?

**Comment by patkino** [comment]
1080p50hz
Default font

**Comment by patkino** [comment]
Issue is applicable to all titles that have more than 2 lines

**Comment by jurialmunkey** [comment]
I can't replicate this at all. Are you on Nexus? Because I can't reproduce on Nexus. If I force a really long line by duplicating the label, it will only show the first two lines:

![screenshot00102](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/d29ca8b2-3c59-4e9e-86a8-ddad4e4f106c)



If you're on Kodi 21 alpha, then that's some textbox display bug to do with Kodi 21 and needs to be reported. The text should not display like that in a textbox if `<aligny>center</aligny>` is set -- it looks like someone has made a change to the textbox alignment code and is not properly calculating the line height to figure out what to display.

**Comment by patkino** [comment]
Well I'm on nexus. And it shows more than 2 lines like this.
Maybe it's a Cyrillic font feature..

**Comment by patkino** [comment]
![6960190-1690706781845](https://github.com/jurialmunkey/skin.arctic.fuse/assets/85682547/a312ad4a-32ab-4ae2-8943-dd0fd7a9f73c)

**Comment by jurialmunkey** [comment]
It definitely should not display like that. The label is not even tall enough to display that far down.

You can see here that the group is only defined as being 120 pixels height
https://github.com/jurialmunkey/skin.arctic.fuse/blob/5553cc6cfee304f67d9d61bfadfbb29164f23774/1080i/Includes_Info.xml#L35

Yet in your screenshot the label is approx 180 pixels height. This is some problem with the version of Kodi not honouring the label height correctly because that is displaying text outside the bounds.

**Comment by jurialmunkey** [comment]
Is this still happening with the workaround I added?

**Comment by patkino** [comment]
Now I can't apply the skin. Its selection crashes Kodi.
*skinvariables 1.1.7
