### ISSUE TITLE
Bakeground Style 'fake blur'

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#188]
### Skin section

Home Widgets

### Current Behavior

Pictures will explain it better, but if background style is fake blue, then the movie background will not come up unless you actually go on it.

### Expected Behavior

Fake blur and Real Blue to be the same 

### Steps To Reproduce

Appearance
Background style Fake Blur
Go onto widgets 
Chose categories at bottom, but do not press up to select movie

### Screenshots and Additional Info

![firetv_2023-10-29_19_33_18](https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/53c3fce3-6ab8-48bb-be5a-a0d210893d3a)
![firetv_2023-10-29_19_33_48](https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/544b08e9-e126-43a9-9a77-f05364c1abb6)
![firetv_2023-10-29_19_35_21](https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/c1f20c04-fcbc-4b7b-a8af-cb87b7e59ccb)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Yeah there's no really much that can be done about this. Kodi doesn't have a way to set an "active" container ID so it's only possible to get details using the focused item.

The reason it works for real blur is because that's done with Tmdbhelper and I can script it. But that defeats the purpose of the fake one - the performance comes from using Kodi's local fanart.

The only other way I could do it is write a variable with thousands of conditions for every possible container ID - which also defeats the purpose.

**Comment by adamosborne83** [comment]
You hero
