### ISSUE TITLE
[Feature] side menu items without categories

### ISSUE THREAD

**Issue by 666jones** [jurialmunkey/skin.arctic.fuse#19]
### Skin section

Home Widgets

### Feature description

Side menu items without the need for categories. 

The ability to just have side menu items with widgets only.

### Why is this feature needed? Please justify and explain.

Because I'm old and like things to be as simple as possible. I get lost in all these things. I normally just have around 5 side menu items with around 5 widgets in each.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I had a similar thought the other day that it'd be nice to have a simpler "widgets only" type of option. I've already got something ready for the hubs, so I'll push that now.

Still working on the home menu though as the skinshortcuts setup functions a little differently there due to how the widget group selector menu works. 

Also, I think Home could use an extra middle-ground type of option -- e.g. a "widgets+categories" type of option that removes the spotlight plus submenus, but leaves in the widget group menu.

**Comment by jurialmunkey** [comment]
Next release will add this option.

For the hubs there is a "Widgets only" option which disables the categories, submenus and top widget.

For the home screen, in addition to the "Widgets only" option there is also a "Widgets categories" option which disables the submenu so that the widgets slide up when the categories selector is focused (similar to the classic "combined" seasons view).

**Comment by 666jones** [comment]
> Next release will add this option.
> 
> For the hubs there is a "Widgets only" option which disables the categories, submenus and top widget.
> 
> For the home screen, in addition to the "Widgets only" option there is also a "Widgets categories" option which disables the submenu so that the widgets slide up when the categories selector is focused (similar to the classic "combined" seasons view).
> 
> EDIT: Forgot to mention - if "Widgets only" is selected for the home screen, it will use the widgets from the first category (it doesn't display the categories but it still needs the widgets defined in one of them so that skinshortcuts builds).
> 
> EDIT 2: For my own reference -- possible future idea for "Widgets only" would be to have the category selected at random on startup (so set one category and you get the same set everytime, but set multiple categories and you get one of the category groups at random rather than just the first one).

Just done your update. You have been busy I'm very surprised that you have cracked all this out already. Great job and thanks for taking the time. I have sorted my home tab nicely now i just need to play about with the hubs. I'm sure I seen a link somewhere to buy you a drink I'll have a search now and see if I can find it. If not feel free to share the link here and I'll get you a coffee. Again thanks for your work and time
