### ISSUE TITLE
Top right hand

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#192]
### Skin section

Home Widgets

### Feature description

I'm getting g really pedantic now, but, is there a way to have the top right hand background whilst 'working' translucent instead of solid.

I'm all about sex appeal and looks

### Why is this feature needed? Please justify and explain.

Good sex appeal

### Screenshots and Additional Info

https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/3abc8881-c3e6-4af6-aab4-03377fa6f5bc

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Text is unreadable overlayed on light fanart.

Either the notification dialog needs a background OR the fanart needs to be dimmed like it was in AH2 - - dimming is something I don't want to do because a big part of the design of this skin was to allow full brightness backgrounds.

It's the same reason why I don't have an option for clock in top right - text is simply unreadable there on some backgrounds.
