### ISSUE TITLE
[BUG] issue when selecting item created from widget 

### ISSUE THREAD

**Issue by SJ1O** [jurialmunkey/skin.arctic.fuse#206]
### Skin section

Home Widgets

### Current Behavior

Hello Jurial, I created a widget from the fen add-on for the movie category within fen. But when I click on one of these options via the widget it sometimes takes upto 1 / 2 minutes to load. However if I navigate directly within the fen add-on I don't have the loading issue it's really fast matter of seconds. I'm not sure if there is some type of issue or if this is just how it is because it's from the widget but would be grateful if you could look into it and see if there is something causing this to happen. Also I must note that these categories are trakt dependent incase that could be a possible cause. This seems to be temperamental but does happen more often then not. I will try replicate the issue and update this with a log incase. Not sure who to actually report this to ie you or Pete but thought I'd seek your advice first incase it was a skin glitch.

Fire cube 3rd gen
Kodi 20.2 

Many thanks
SJ

### Expected Behavior

Not to get stuck on the loading screen for to long.

### Steps To Reproduce

Create fen widget. Fen - Movies create widget to here.
View the widget and select watched or in progress. I mainly have this issue with these two options. 
It will possibly hang for a while before content loads.

### Screenshots and Additional Info

![20231111_085907](https://github.com/jurialmunkey/skin.arctic.fuse/assets/121204283/0fa5dd2b-5b8c-45fe-9c5c-e07fec5b51fc)
![20231111_085929](https://github.com/jurialmunkey/skin.arctic.fuse/assets/121204283/8f59e7bc-f3fb-423d-b735-9538d220d422)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Skins dont have any control over how content loads (other than, of course, determining which widget goes where). There's really nothing a skin can do to make loading go faster or slower because it isn't involved in that process at all. 

It isn't even possible for a skin to control the order widgets load in. Other than determining when a widget is visible, a skin cannot control when or how the content loads -- that process is done entirely by Kodi and the end plugin.

The only way a skin might have any impact on loading is if there's a widget in the background which is still loading and so holding up the loading queue -- e.g. maybe a widget got stuck still loading.

Another possibility is that the plugin does some initial precaching when you first open it in the library, so by going via a widget you miss out on that benefit and have to wait for it to do that process -- but I'm really just making a guess there which is not based on anything in particular, so I wouldn't put too much weight in that statement.

A debug log would give more clues.

**Comment by SJ1O** [comment]
Sorry for the late reply just got the chance to get a log.

https://paste.kodi.tv/uwugiriruv

Is this the correct type of log you need? 

I have a feeling it might be as you mentioned about the precaching but I really don't know. Just thought I'd get your thoughts on the matter.

Thanks very much for looking into it it's much appreciated 👍🏼

Kind regards
SJ

**Comment by jurialmunkey** [comment]
> I have a feeling it might be as you mentioned about the precaching but I really don't know. Just thought I'd get your thoughts on the matter.

Yeah I really guessing, as I have no idea how that plugin works but I can see in the log there's messages about a Trakt service syncing (and looks like first time around it failed), so it is definitely a possibility

Also possible is skin updates causing reloads (which I can also see in the log) slowing things down first time around. 

Basically when Kodi does an update it deletes the entire skin folder and then extracts the new zip, so any custom XML code will be deleted and addons like skinvariables (and skinshortcuts before) will need to rebuild their custom code. After the custom code is rebuilt, they will then need to reload the skin so that the code gets included. 

What might be affecting things here is the viewtypes code being rebuilt, because that triggers when you first open a media window after a new update. Skin reloading to include the viewtypes code is going to cause the view container to reload which means the plugin is effectively loading twice first time after an update.

With all the rapid skin updates at the moment, that's a big possible contributor. There's not much that can be done about that (short of not getting updates!)
