### ISSUE TITLE
[Feature] Released, Returning and ended next to date

### ISSUE THREAD

**Issue by 666jones** [jurialmunkey/skin.arctic.fuse#22]
### Skin section

Home Widgets

### Feature description

It would be nice if it was possible to include Released, Returning or ended next to the date like I have included in the photo.

### Why is this feature needed? Please justify and explain.

It's not all that important however it's a handy bit of information that was implemented into one of your other skins

### Screenshots and Additional Info

![20230730_014221](https://github.com/jurialmunkey/skin.arctic.fuse/assets/121204283/83cb06ab-cb54-4c7b-adca-fcac92b8bd4f)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
The Next Aired data is in the ratings line. The icon tells you the status

✔️ = Ended / Released
Mr InBetween Ended.
Last Aired on 13/07/2021

![Screenshot 2023-07-30 110650](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/1a9ff8ac-0425-4871-94ac-9db8c9b46e0b)

❗ = Cancelled
Mindhunter is Cancelled. 
Last Aired on 16/08/2019

![Screenshot 2023-07-30 110727](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/ff7e37bb-b75b-4a87-8f5b-5b2b4905a257)

 🎯 = Continuing
Silo is Continuing.
Last Aired 29/06/2023 (will show Next Aired date once info is available).

![Screenshot 2023-07-30 110805](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/106afc6d-31ae-4e03-9693-88f8b3abcac7)

🎬 = In Production
Ahsoka is In Production
Due to Air 23/08/2023

![Screenshot 2023-07-30 110841](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/34723dc7-5b3e-4d21-9d64-f98aa22936d8)

**Comment by 666jones** [comment]
Ahh that makes sense I never noticed these different icons 👍🏻
