### ISSUE TITLE
[BUG] media sources in options

### ISSUE THREAD

**Issue by A30B06** [jurialmunkey/skin.arctic.fuse#220]
### Skin section

Other

### Current Behavior

Hey jurial, in the v4.0 update was the ability to add media sources to the options menu removed?

### Expected Behavior

Before v4.0 was able to add a media source to the options window. (I used this to directly connect to real debrid which was added as a source)

### Steps To Reproduce

N/A. Not available anymore

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I'm not quite sure what you mean by media source? Do you mean like files mode - eg where you'd add a source and choose the content type to add to library?

I didn't deliberately remove any paths - but since I had to redefine them all by hand it's possible there's some I didn't think about (or didn't know were used!)

Happy to add whatever paths are needed to the choices.

**Comment by A30B06** [comment]
Hey :)
Yeah sorry I don’t know the exact name for it. In the top level media menu you have Movies, TV Shows, Files, Playlists & Video addons. Clicking into files then shows all of the media sources you have set up.

if I remember right in the old version you would choose videos and then it gave you the option of Movies, TV and sources, so you could select which source you wanted for the file view.

**Comment by jurialmunkey** [comment]
Ah right - I yeah I forgot that videodb:// path skips that level. I always think it's the base level and so you can get anywhere from it but there's actually a separate path for sources (which I guess makes sense since the aren't *yet* databases and so technically shouldn't be in videodb). I should be able to find that path and add it.
