### ISSUE TITLE
After update previous setup has gone.

### ISSUE THREAD

**Issue by DROIDshield** [jurialmunkey/skin.arctic.fuse#221]
### Skin section

Home Widgets

### Current Behavior

I've just updated to the latest version and all of my previous setup has gone.

Is this correct? Should this have happened that all of the widgets i previously had should be removed for the new layout?

### Expected Behavior

Expected to update and all of my previous widgets to still be in place.

### Steps To Reproduce

Update all and restart. 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Expected behaviour. See this post:
https://forum.kodi.tv/showthread.php?tid=373859&pid=3172616#pid3172616

v0.4 onwards removes SkinShortcuts as a dependency, so it's not backwards compatible.

Needed to rip off the SkinShortcuts band-aid because it was starting to get really convoluted trying to wrangle it into doing what I wanted and it isn't really being developed anymore (only maintained).

I know it's a major pita to have to re-setup but it's definitely going to be worth it moving forward. Should be the last major breaking change now that I've made my own template building and shortcuts management script. 

I did consider having an import function to try to pull in skinshortcuts data but it was going to be really messy and ultimately I decided it was better to force a clean start rather than trying to deal with issues with badly imported data.

Older skin versions are available from releases if you're not quite ready to make the switch yet (old skinshortcuts config should still be intact because the new script doesn't touch it, so you can roll back until you're ready to setup).

**Comment by DROIDshield** [comment]
Okay, yep its a blow but I'll go with it and start the setup again...

The Mrs is gonna kill me for sitting here pressing buttons into the early hours...😂😂😂😂👍
