### ISSUE TITLE
[BUG] Stacked Folder uses last item in submenu

### ISSUE THREAD

**Issue by Jcloak** [jurialmunkey/skin.arctic.fuse#223]
### Skin section

Home Widgets

### Current Behavior

This might be a weird use case or maybe I am configuring things wrong. I was able to setup TV Show lists with stacked folders for seasons and episodes before the latest update. I tried to set it up again and now I am running into this issue:

When I add stacked folder widgets for submenu items, only the last item in the submenu gets the stacked folder widgets.

### Expected Behavior

I expect the stacked folder widgets to show the appropriate seasons and episodes for the selected submenu item.

### Steps To Reproduce

1. Create category item called "Shows"
2. Enable "Use as widget"
3. Create 3 submenu items: "Comedy", "Drama" and "Animated"
4. Add 2 Stacked Folder Widgets for "Seasons" and "Episodes"
5. Navigate to "Comedy" and attempt to navigate downwards to the stacked folders. Nothing happens
6. Navigate to "Animated" and the stacked folders work as expected
7. Navigate to "Comedy" and the "Animated" stacked folders remain

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Yeah this is because now static submenu items generate their own individual widget *per* item. That's done so that it doesn't need to reload constantly as you scroll through the items -- it just switches visibility of the widget shown instead.

Problem is that stacked widget looks at the widget which is its own ID minus one, so that'll always be the last submenu widget.

You can get around this by using a submenu list instead of items -- the widget of a submenu list acts the same as a stacked widget (one widget but path updates as you move), so that will always have the same ID.

If you make a node with your submenu items, then you can add the node as your submenu list, use it as a widget, and then stack your next widget on top.

**Comment by Jcloak** [comment]
Alright, I think I'm almost there. I created a Shows.json file in my nodes folder with 3 items in the list: Comedy, Drama and Animated. I added a category item called "Shows" and am using a submenu list pointing to that newly created Shows node. All 3 submenu items appear as expected, but when I navigate down I cannot get any of the stacking functionality to work. I tried with no widgets as well as adding the stacked folder widgets. 

I think this is the part where I'm getting lost. I'm not exactly sure what this part means:

> use it as a widget, and then stack your next widget on top.

**Comment by jurialmunkey** [comment]
@Jcloak - Just added an option to allow stacking from static items (it essentially transforms it into a node automatically). Should simplify it considerably.

Will push it to my repo a bit later today, just a few more features I want to get in first.

**Comment by ambulancePilot** [comment]
This works perfectly! I've got Genres as a category and Movie Genres and TV Genres as submenu items used as widgets, and then a stacked folder in the widgets section of the category and it works just as intended. Highlight a genre and the widget below populates. Great stuff!
