### ISSUE TITLE
Pull Favorites to a widget

### ISSUE THREAD

**Issue by derrgoo** [jurialmunkey/skin.arctic.fuse#224]
### Skin section

Home Widgets

### Feature description

With the latest update it stopped the ability to pull favorites into a widget. I may be wrong, maybe ai just can’t find. Now the only option is to build a category and click to open all favorites box. 🙏 

### Why is this feature needed? Please justify and explain.

Put certain random channels in favorites and made a widget to select what is in favorites. 

### Screenshots and Additional Info

![IMG_9001](https://github.com/jurialmunkey/skin.arctic.fuse/assets/63697905/9d75572d-56df-4be6-b7b1-44b665695979)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I was under the impression that favourites didn't work properly from a widget -- i.e. it will play some types of items but not all and it doesn't work properly for folders -- so I didn't add it as an option.

The path is `favourites://` so you should be able to input that manually using `Action > Edit` if you still want to use it and it works for what you need it for.

Nodes would be more suitable for this type of thing though I understand the convenience of favourites since it is built into Kodi's context menu.

**Comment by derrgoo** [comment]
That worked great.
