### ISSUE TITLE
[BUG] Unable to Select Home Hub

### ISSUE THREAD

**Issue by Dml2023** [jurialmunkey/skin.arctic.fuse#228]
### Skin section

Home Widgets

### Current Behavior

When in Classic Layout Style and the focus is on the side menu moving up and down the menu changes to the Widgets defined for each hub, If I select a hub I then see the Spotlight and Categories with their respective widgets for the selected hub. When I try to select the Home Hub, the selected Spotlight and Categories do not display.

### Expected Behavior

The Spotlight and Categories should display as they do in the Movies/Tv/Music hubs

### Steps To Reproduce

1. Go to Home Icon
2. Click on Home Icon

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
The home screen *is* the hub.

If you want it to show categories and spotlight then you have to change the style to categories

**Comment by Dml2023** [comment]
Ok, Thanks for the clarification. Just getting used to the changes on 0.4 and the obvious extra options that using skin variables give you.

**Comment by jurialmunkey** [comment]
What I could do is allow deleting the home screen link. Then when I add back custom hubs you could instead link it to a separate hub. That'd allow classic on home with each button going to a hub. 

The only issue with allowing home to be deleted is that then you have no way to edit the home screen if you switch out of classic mode (because you need the home hub link to edit its categories).

**Comment by Dml2023** [comment]
Thanks again JM, That sounds like a nice solution. If you were to go down that route, would you then be able to have code check that when switching out of Classic mode if an actual Home link does not exist, then it gets recopied from the default json file, or at least prompted to recreate it?

**Comment by jurialmunkey** [comment]
> Thanks again JM, That sounds like a nice solution. If you were to go down that route, would you then be able to have code check that when switching out of Classic mode if an actual Home link does not exist, then it gets recopied from the default json file, or at least prompted to recreate it?

That's the route I was thinking of going originally but decided against it because I'm not particularly keen on modifying user configs unannounced (and I could see a pop-up confirmation quickly becoming annoying).

Had a bit of lightbulb moment now though. Instead of allowing the shortcut to be deleted/changed, I can just allow for it to be disabled/enabled. That way there's always access to it but it doesn't show up in the menu itself; which will also work in other layout styles.

**Comment by Dml2023** [comment]
Hey JM, Your light bulbs are very bright :). Your solution definitely provides the best flexibility.
