### ISSUE TITLE
[BUG] Left side movement from Search box issue

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/skin.arctic.fuse#243]
### Skin section

Other

### Current Behavior

On movin to left from the search box in the search menu, widgets do not appear anymore. Could you kindly fix it?

### Expected Behavior

On moving left from the Search box in the Search menu the home widgets should show up correctly like it used to before.

### Steps To Reproduce

Go to the search box in the search menu. Move left. The widgets won't show up until you click on any left side menu item.

### Screenshots and Additional Info

![IMG20231124073927](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/fb42221f-92b2-42f6-9b0c-f0b1e4c7f93d)

![IMG20231124073732](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/86c323fa-3d51-43d8-8dea-6b61be40e8b8)

![IMG20231124073738](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/7f5cb321-34a6-4c4c-b97d-a45213007cd8)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I disagree with left closing the search menu. I think that's a bad idea because it makes it hard to navigate the edit box (pressing left/right moves the cursor through the characters, so if you accidentally press left too many times the box will close randomly).

I think with the changes to the search menu, the expectation is that left/right will move between icons and the edit cursor.

I will, however, add an onup close action.

Also recent changes will improve appearance considerably to look less "broken" when the side menu is focused and no items are available.

**Comment by AakashC2020** [comment]
Hi @jurialmunkey,

Fine. Thank you so much!
