### ISSUE TITLE
[BUG] Titles Category submenu title sorting

### ISSUE THREAD

**Issue by Dml2023** [jurialmunkey/skin.arctic.fuse#245]
### Skin section

Home Widgets

### Current Behavior

When viewing the submenu of the "Titles" category (A-C, D-G, etc) titles that start with "The" all appear in the "T-V" sub menu instead of using the sort title as is used in Library view. The Genre category Submenu widgets sort correctly though.

### Expected Behavior

The widget should use the sort title of the TV Show or Movie

### Steps To Reproduce

Go to Shows Hub or Movies Hub with categories, go to the Title category, navigate to the T-V submenu.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Yeah I'm not sure if there's a solution to this one. The "titles" lists are just a folder of smart playlists which each check the start letter of the title. You can see the T-V one here:
https://github.com/jurialmunkey/skin.arctic.fuse/blob/nexus/extras/hub/movies/titles/T-V.xsp

As far as I can tell, Kodi doesn't support using SortTitle as a field for rules in Smart Playlists (which is what would be needed to have a smart playlist based on sort letter instead of just the plain title).
https://github.com/xbmc/xbmc/blob/940fe21f4ff0a18e4c5f97956ad5bd7d523a80d6/xbmc/playlists/SmartPlayList.cpp#L448-L478

**Comment by Dml2023** [comment]
Thanks for the reply JM. I'll have to hope that Kodi will implement SortTitle in the Smart Playlists in a future version.
