### ISSUE TITLE
[BUG] Clicking on item in widget leads to incorrect view

### ISSUE THREAD

**Issue by joopdo** [jurialmunkey/skin.arctic.fuse#257]
### Skin section

Home Widgets

### Current Behavior

When selecting an item in a widget that is a plugin (e.g., `plugin://plugin.video.kpn/?_=live_tv`), the view switches to a different page as it's showing the video.

### Expected Behavior

The selected item should play the video, and once I stop playing, the widget listing should return to the view where I choose the video before.

### Steps To Reproduce

1. Navigate to the widget containing a plugin (for instance: `plugin://plugin.video.kpn/?_=live_tv`.)
2. Select an item.
3. The view switches to a different page, then starts showing the video.

### Screenshots and Additional Info

The video shows the behavior that I found first, and then my expected behavior.
https://github.com/jurialmunkey/skin.arctic.fuse/assets/1182449/cfb9eb5a-ed0c-46bb-b8b1-fff5bf53c75e

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
The skin doesn't control the onclick behaviour of the widget.

It sounds like this plugin is incorrectly setting playable items with the folder flag, which means kodi will attempt to open them as a folder (so needs to open the media window set as the target).

Have you confirmed this doesn't happen in other skins with customisable widgets? Because I suspect it happens in all of them.

**Comment by joopdo** [comment]
Apologies. 

I confirmed the same behavior happens with another skin with customizable widget.

Thank you for this insight and the amazing work you (are) put(ting) out there! Closing.
