### ISSUE TITLE
What are the chances???

### ISSUE THREAD

**Issue by DROIDshield** [jurialmunkey/skin.arctic.fuse#260]
### Skin section

Home Widgets

### Feature description

This is just a question, As the skin gets more requests for new features and the amount of widgets addons etc I use in my setup im finding that running AF on top of Kodi with all the other useful addons I need to make this run like "NF" with a twist, I find im now starting to see some lagging on both my Shields... 3 gig of ram isn't cutting it so I had to drop 4x widget rows to bring back the smooth running. 

So I'm wondering  @jurialmunkey  what are the chances of turning AF into a app with TMDB and a player built-in so all I have to add is my Trakt account and maybe a RD account?

This would run so much smoother on all android unit's My, powerful pc can handle it but even a unit as powerful as the shield has limits. 

What do you say?

### Why is this feature needed? Please justify and explain.

This would be a welcome transition if it could be done

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
What do you mean by "app"? You mean you want me to single-handedly write my own version of Kodi from scratch for Android? Considering I don't even use Android at all, I think it is pretty safe to say that will never happen.

You are giving far too much weight to what skins and plugins do. 

In terms of playing files, all a streaming plugin does is give Kodi a URL to play. The plugin might manage some parts like authentication with the server and managing the download, but it is Kodi which is reading, decoding, and rendering the video/audio from the file to the screen. 

Without Kodi there is no "player" because Kodi IS the player. It is also resonsible for managing all the rendering of GUI elements on screen, managing peripherals, managing keymaps, managing navigation and so on. 

Thinking plugin and skin devs are what make Kodi work is like thinking painters and interior designers are what make a house.
