### ISSUE TITLE
:bug: Side menu navigation issues

### ISSUE THREAD

**Issue by SJ1O** [jurialmunkey/skin.arctic.fuse#273]
### Skin section

Home Widgets

### Current Behavior

Side menu / navigation / focus issue

1. When you enter a hub via the side menu then go / click (home) via the side menu, it doesn't focus on home and takes you to a blank home page. You then need to scroll back upto home on the side menu again then you can see the home page. So in theory your navigating to home on the side menu twice to view your home content.

2. When you enter a hub it focuses on the home tab rather than on the hub you just entered (only happens on classic widget only hubs)

3. When you view a widget and scroll to the end click next page to view the 2nd page and then up on the navigation it goes to the search function rather than bumb (I have up nav set to bumb in navigation settings)

4. When you view a widget and scroll to the end click next page to view the 2nd page and then if you go back ( return ) to the widgets it focuses in a random place most often focuses back on the side menu. ( Only happens in classic widget only hubs )

I have included these issues in one report as I think atleast 3 of them are linked. And thought it's possibly simpler for yourself to go over rather than write four reports.

I closed my last issue to try keep the report as clean and detailed as possible and tried to explain it better to the best of my ability.

Kind regards 
SJ

### Expected Behavior

Focus where entered

### Steps To Reproduce

I think I have included enough details for you to be able to replicate in current behaviour. If you need any more information I'll be happy to help.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I've split point 3 off into a separate issue, as that will need to be dealt with separately. The other three are definitely all related (and possibly can be fixed altogether by the same fix)

Separate thread for 3 here: https://github.com/jurialmunkey/skin.arctic.fuse/issues/274

**Comment by SJ1O** [comment]
Sorry I just nodded off. For point 1 I just checked and I have classic mode selected for the home page. Also I should note that I also only have one widget set for my home page. And after clicking home if im currently in another hub it defiantly takes me to a home page with no widgets and I need to scroll up again to home to get my home page widget to show. I personally think pre v4 behaviour was more user friendly. I was browsing movies and left it in the movie hub. My wife come along and wanted to continue watching a show so she went to the home tab and waited about 2 minutes thinking it's going to load then I needed to explain to her that she must scroll up to the home tab again. Then she moaned at me and said I need to stop changing stuff. I tried to put the blame on you but she was adiment that It was my fault.

**Comment by jurialmunkey** [comment]
> I was browsing movies and left it in the movie hub. My wife come along and wanted to continue watching a show so she went to the home tab and waited about 2 minutes thinking it's going to load then I needed to explain to her that she must scroll up to the home tab again. 

This will be because you haven't added anything to the widget group for the movies icon (only to the widget group for the hub).

Anyway in v0.4.20 there is now a `Global Widgets` option in classic mode for the side menu icons. If you enable that, it will allow you to setup a "global" widget group which will be used for whichever menus you enable it on.

(I know I'm getting a bit sidetracked from the actual issue thread here but I promise I am looking into the focus issue too!)

**Comment by SJ1O** [comment]
Sorry let me explain it again. 
I was already in the movie hub browsing movies. The wife then come along picked up the remote scrolled to the home icon clicked it. It then automatically focused back on the movies icon but no widgets loaded. ( Would of expected the home widgets to load as pressed enter on the home icon) but nothing happened. I then said scroll back to the home icon and it will show your shows.

I have just recorded a video for you. (Currently in documentary hub) but wanting to now view my home page. You will see I need to scroll to the home icon twice to get it to show the widgets.

I just tested it with global widget set on the home page and it still has the same behaviour.

However all this aside I'm 99% sure this is just down the the focus issue.


https://github.com/jurialmunkey/skin.arctic.fuse/assets/121204283/b12f2391-3fd6-4b10-945f-58b88769a571

**Comment by SJ1O** [comment]
Also no rush all in your own time pal, I appreciate the support you offer and what you do and have done. So I don't expect anything done until your good and ready. And as you mentioned the global widget was you aware that there is no way to change the style from landscape?

**Comment by jurialmunkey** [comment]
> The wife then come along picked up the remote scrolled to the home icon clicked it. It then automatically focused back on the movies icon but no widgets loaded. ( Would of expected the home widgets to load as pressed enter on the home icon) but nothing happened.

Yes this is expected behaviour because you have not added any widgets to movies widget group for the home screen. You have only added widgets for the movies hub window which is only opened when the icon is clicked.

These are separate sets of widgets which are displayed depending on whether home window or movies hub window is active.

Hopefully this screenshot will help to understand the options better. Orange text with arrows highlights important parts, blue text gives a bit more detail


![screenshot00256](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/2fba5d9f-771c-4c43-bd67-dadc4061aafa)

**Comment by SJ1O** [comment]
I completely understand what your saying about the Hub widgets Vs focused icon widgets. I'm not expecting to see widgets unless I actually click on a hub. 

However surely if you press enter on the home icon when you have it set as classic mode hub it should enter the home hub. Instead it opens a page with no widgets (side menu / hub your actually navigating away from I think) regardless if you have it set as classic home widgets or even use global widgets on the home page. I have just tested it with categories style hub and it works very lovely. This issue is just with classic mode widgets on the home page. The reason I don't see any widgets at all is because I only have hub widgets set up I'm not using focus widgets on any of my menu items. 

Anyway I'm 99% sure all this boils down to it not focusing on the menu item you actually select and the main hub this affects the most is the home hub when the home hub is set as classic widgets.

I hope this didn't stress you out to much just needed you to know I'm not being completely crazy 😅

**Comment by jurialmunkey** [comment]
> I completely understand what your saying about the Hub widgets Vs focused icon widgets. I'm not expecting to see widgets unless I actually click on a hub.

You're actually not understanding...

In classic mode, the home screen functions DIFFERENTLY from the other hub windows.

The purpose is to replicate the "classic" behaviour of Kodi's default skin Estuary where the widget group displayed on the right side of the HOME screen changes depending on which item in the side menu currently has focus.

Hence why the setting is no longer simply called "widgets only" and is instead now called "classic mode".

> The reason I don't see any widgets at all is because I only have hub widgets set up I'm not using focus widgets on any of my menu items.

Yes exactly. Because that is how classic mode is meant to work.

If you don't set and widgets to the movie icon widget group then nothing will be displayed when it has focus on the home screen because there's nothing to display in that group.

That is the purpose of the global widget group.

Instead of setting separate individual groups of widgets per side menu item on home screen, the global widget group allows creating a single a group of widgets to display for any side menu item where the setting is enabled.

**Comment by SJ1O** [comment]
Ahh ok I got you I'm ever so sorry about this feel like I must have droven you crazy I was adiment it wasn't right 🤦🏻‍♂️. 

Well thanks very much for explaining and again I'm truly sorry i was just getting very confused. Last night I actually decided to change it up and add categories to all of my side menu items even if I only have one category within the menu. I actually like the look of the highlighted pink category tab think it makes things even more clearer and everything focuses and functions perfectly so win win situation. 

Your welcome to close this now if you wanted as I much prefer just using category hubs. 

Thanks for all your help and support you truly are amazing.

**Comment by jurialmunkey** [comment]
> Ahh ok I got you I'm ever so sorry about this feel like I must have droven you crazy I was adiment it wasn't right 🤦🏻‍♂️.

Haha no worries. It happens.

> Your welcome to close this now if you wanted as I much prefer just using category hubs.

I'll leave it open as I definitely want to fix these issues anyway, especially since I'm currently using classic mode in my own setup. I find having an open issue gives me something concrete to work against which helps me keep organised / focused.

**Comment by SJ1O** [comment]
I just tested this and it all seems to be working as expected now 👍🏼
