### ISSUE TITLE
🐛 Browse button on spotlight not working.

### ISSUE THREAD

**Issue by rapteev** [jurialmunkey/skin.arctic.fuse#278]
### Skin section

Widgets

### Current Behavior

Hi
I don’t know if it’s only me but happens on 2 different machines both running kodi 20.2 and fuse 0.4.20 on windows 11.
Selecting browse button on a spotlight tvshow nothing happens.

### Expected Behavior

Browse selected tv show

### Steps To Reproduce

On spotlight try to use browse button on displayed tv show

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by rapteev** [comment]
Hi Jurialmunkey 

This also happens for music/artists on spotlight.

**Comment by jurialmunkey** [comment]
I cant reproduce this issue. I haven't touched the code for spotlight recently so I can't really see any reason why it would start behaving differently now -- unless this has been happening for a while and you just haven't noticed?

**Comment by jurialmunkey** [comment]
Actually, what's your onclick action? Is it info instead of play?

**Comment by rapteev** [comment]
Hi
Thank you very much 
Yes I have kodi set to show info on click.
I don’t know if I can ask you here or start a new post but updates not showing on nexus . The last skin version there is 0.4.20

**Comment by jurialmunkey** [comment]
I haven't backported to Nexus yet. 

Updates on Nexus will be more infrequent now that the GUI bump forces me to maintain two versions of the skin. 
New features will be first added on Omega as the main branch. Then I will backport to Nexus when I have time.

It's mainly that the GUI and addon versions create conflicts when merging back into Nexus and needs manual intervention. It's not too bad at the moment because both branches are otherwise identical but it's still enough of a pain to not want to do it nightly -- more of an every two to three days type of thing.

**Comment by rapteev** [comment]
Well it seems that I have to update to Omega 😀
