### ISSUE TITLE
:sparkles: Allow search path suffixes

### ISSUE THREAD

**Issue by lksmasin** [jurialmunkey/skin.arctic.fuse#317]
### Skin section

Widgets

### Feature description

The [procedure](https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/104) described for the arctic horizon 2 addon works, but there are addons where it is not possible to edit the search path so that the search query is at the end. It would require some kind of variable that is marked and the skin will automatically add the search query to it. Example: plugin://plugin.video.mycoolplugin/?info=search&query={search_query}&type=movie. Otherwise I have to praise the skin, I like it a lot, keep up the good work.

### Why is this feature needed? Please justify and explain.

In some add-ons it is not possible to move the search query to the end of the path.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
What is a specific example of an addon which cannot be rearranged? Because your example can:

```
plugin://plugin.video.mycoolplugin/?info=search&type=movie&query=
```

The order of params in a URL should not be important.

**Comment by lksmasin** [comment]
@jurialmunkey In our country we have a pretty popular add-on that streams content from cloud storage. I am sending the link to the GitLab of the above mentioned add-on. https://gitlab.com/stream-cinema-community/plugin-kodi

**Comment by jurialmunkey** [comment]
I don't want to install a plugin. I just want an example of the search path.

**Comment by lksmasin** [comment]
@jurialmunkey  Oh, I'm sorry, I misunderstood.
Activate the plugin call window, after which the search text entry form is displayed and after entering it, the search is started and a list of searched titles is returned:

`ActivateWindow(Videos, "plugin://plugin.video.stream-cinema-2-release/search",return)`

However, if you already have the search <string> available, then:

`plugin.video.stream-cinema-2-release/get_media/?%2A&render_type=search&url=%252Fapi%252Fmedia%252Ffilter%252Fv2%252Fsearch%253Fvalue%253D<string>%2526order%253Ddesc%2526sort%253Dscore%2526type%253D%25252A%2526size%253D50?`

**Comment by jurialmunkey** [comment]
> Activate the plugin call window, after which the search text entry form is displayed and after entering it, the search is started and a list of searched titles is returned:

This is impossible from the skin search window. A skin cannot input keyboard text. 

Even if it could, this type of approach requires the plugin to update the container path. That's only possible inside media windows where there is a single view container. A container update after inputting a search term is not possible in a custom window with multiple widget containers.

> However, if you already have the search available

Does this path work for new search strings which haven't been searched before?
i.e. if you replace the `<string>` part with a new search that you haven't done and then enter that path as a normal widget on the home screen, does it work?

Because I can add a way to add a suffix to the end of the path that would allow the string to go in the middle -- but if it doesn't work for new searches then that's pointless because it won't be useful anyway.

**Comment by jurialmunkey** [comment]
Closing as stale. No response to my question.
