### ISSUE TITLE
:bug: Localization of TMDbHelper.TraktStats.Recent.0.Type

### ISSUE THREAD

**Issue by dm1tz** [jurialmunkey/skin.arctic.fuse#326]
### Skin section

Fonts and Languages

### Current Behavior

Recently watched type fetched from TMDb Helper is not localized.

### Expected Behavior

Recently watched type fetched from TMDb Helper is localized.

### Steps To Reproduce

1. Switch to any language except English
2. Go to the main menu
3. Observe a short info block with wached stats.

### Screenshots and Additional Info

This is clearly a TMDb Helper issue, but since Arctic Fuse [seems to be the only skin/addon](https://github.com/search?q=TMDbHelper.TraktStats.Recent.0.Type&type=code) that uses this I figured I'll land it here. So, currently, TMDb Helper receives an unlocalized recently watched type (movie or episode) from [here](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/08039dec16362003fe90ebd523ca011f47eef991/resources/tmdbhelper/lib/script/method/trakt.py#L102) so there's no way to translate it in Fuse. Maybe a short if-else statement together with get_localized() func and new gettext strings in TMDb Helper will do the trick? 

![eng](https://github.com/jurialmunkey/skin.arctic.fuse/assets/82608185/d44d7bc6-d862-4110-bcb8-eb31973176ea)
![ua](https://github.com/jurialmunkey/skin.arctic.fuse/assets/82608185/ceea9311-d3ee-4672-8594-2ba4b8e97c15)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
It shouldn't be localized in TMDbHelper because the type is used in the Trakt API as a parameter.

I could maybe put it in a skin VAR instead e.g.
```xml
<variable name="TraktStats_Recent_0_Type">
<value condition="String.IsEqual(Window(Home).Property(TMDbHelper.TraktStats.Recent.0.Type),movie)">$LOCALIZE[342]</value>
<value condition="String.IsEqual(Window(Home).Property(TMDbHelper.TraktStats.Recent.0.Type),episode)">$LOCALIZE[20359]</value>
[etc.]
</variable>
```

Then it'd be used in the string to replace
`The $INFO[Window(Home).Property(TMDbHelper.TraktStats.Recent.0.Type)] $INFO[Window(Home).Property(TMDbHelper.TraktStats.Recent.0.Episode.Title),[COLOR=main_fg_90][B],[/B][/COLOR]]`

With
`The $VAR[TraktStats_Recent_0_Type,[LOWERCASE],[/LOWERCASE]] $INFO[Window(Home).Property(TMDbHelper.TraktStats.Recent.0.Episode.Title),[COLOR=main_fg_90][B],[/B][/COLOR]]`

Would that work?

You'd be able to remove the `[LOWERCASE]` tags if grammatically it needs to be capitalized as first word.

Side note for myself: I really need to split these strings up into individual sentences to make it easier to manage the translations.

**Comment by dm1tz** [comment]
> It shouldn't be localized in TMDbHelper because the type is used in the Trakt API as a parameter.

I meant to localize the Trakt API response string with type if that makes sense.

> Would that work?

Yeah, that would be great. I can update all the translations for these new strings so that you can save your time. Besides, I need to update some ua strings so could make it in one PR. 342 for movie type and 20359 for episodes, right?

**Comment by jurialmunkey** [comment]
> 342 for movie type and 20359 for episodes, right?

These are Kodi strings rather than skin ones, so they should already be localized. But yeah, great if you can (re) translate those new strings I've added. It's split into sentences now, so should make it simpler to translate (and also makes it easier to reuse in the skin).
