### ISSUE TITLE
📌 Discussion on navigation

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#328]
### Skin section

Widgets

### Feature description

Please can you bring navigation options back

### Why is this feature needed? Please justify and explain.

Well, why not? 

### Screenshots and Additional Info

![firetv_2023-12-19_08_24_26](https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/43198e41-970c-4533-aa3a-708db9146618)
Please 

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I needed to simplify things. These options are a nightmare to support.

What exact issue are you experiencing with the current navigation?

**Comment by adamosborne83** [comment]
Sorry, I didn't mean to make it sound like it did, if you intentially removed it. I thought it was a mistake. 
https://imgur.com/a/jtYPKxP

So, I really miss loop.... as you ser when I press the left button it keeps going back to menu.

It's fine on back up button to get to menu 

Sorry, I hope I make sense.

**Comment by adamosborne83** [comment]
Also, where I have numerous widgets along the button, I would usually press the left, but now it just goes to menu.

Hope this video shows a bit of context too.https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/e7fc31c6-1596-4f5e-8585-a7a397b88c79

**Comment by woodside007** [comment]
Maybe at least on the spotlight widget bring back the ability to scroll the spotlight widget left and right to cycle through spotlight items on the browse/play-more info buttons. As it is now, if you happen to see an item that you want more info on and it changes before you navigate to the more info button you have to cycle right through all items until you land on it again. Also maybe on the category menu items it would be nice to have looping back. If you scroll right to the end until it bumps you have to press left multiple times to get back to the beginning. Maybe even just enable it so that the back button takes you back to the first category item if looping isn't now possible. Cheers.

**Comment by jurialmunkey** [comment]
> Maybe at least on the spotlight widget bring back the ability to scroll the spotlight widget left and right to cycle through spotlight items on the browse/play-more info buttons.

I really need to standardise the behaviour when moving from content to menu. It doesn't make sense to have one control (spotlight) do something different onleft and not got to the menu like every other control does.

> Also maybe on the category menu items it would be nice to have looping back

This was not intentional. It was meant to cycle on categories and will be fixed in the above commits.

> Maybe even just enable it so that the back button takes you back to the first category item if looping isn't now possible.

I need to standardise the behaviour first. Then I can have an option for this.

Ultimate end goal is three possible options for behaviour of *all* content.

1. Content always loops *through* menu -- i.e. left at start goes to menu, left again goes to end of list; right at end loops to menu.
2. Content never loops -- i.e. left at start goes to menu, left again bumps; right at end bumps.
3. Content only loops -- i.e. left goes to end, right goes to start of list; pressing back goes to menu.

But before that, I need to get at least (1) working correctly for everything -- hence the need to strip out all these micromanagement options. There should not be that level of micromanagement at the skin level. It should be a global setting for everything.

**Comment by adamosborne83** [comment]
Thanks as always.

**Comment by adamosborne83** [comment]
OK, so ideal, from my perspective....

https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/a4599526-94dd-46cb-b4d0-e4e154b2304f

So the above video, of need be BUMP at start and end, I did use to have loop.


https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/4c7f8676-50bb-4c7c-afd6-6f45cc6e7be6

Defo loop here is possible 



https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/ebdc6a70-2097-4158-9c23-2b498596cd91

This is the main annoyance, the left button always going to menu.

If this is too specific, then so be it. You know I appreciate all you do.

**Comment by ambulancePilot** [comment]
I think you hit the nail on the head with the 3 options you outlined. For me, option 3 is best however the default config is also acceptable.

**Comment by jurialmunkey** [comment]
@adamosborne83 

> So the above video, of need be BUMP at start and end, I did use to have loop.

That's fixed already in the above commits (github master but not in repo releases yet).

> Defo loop here is possible

Same with that one too at the end row selector - already fixed. 

Both of those were accidental -- was trying to fix a looping issue with search filters and didn't think about consequences elsewhere.

> This is the main annoyance, the left button always going to menu.

I think by default left *should* go to the menu. I think the bigger problem there is the looping bug mentioned above -- you're meant to be able to loop *through* the menu to get to the other side of the list (i.e. same as how widgets work).

Once I've got that sorted so that the behaviour is consistently looping through everywhere, then I can look at adding some additional global options.

I can definitely see value in having the three options (i.e. loop / wrap / bump) -- it's just all the "micro" situations that I want to get rid of so that it is one consistent navigation everywhere depending on the setting.

**Comment by jurialmunkey** [comment]
Okay, I *think* I've sorted all the looping conditions now. Will push a new version (v0.4.36) to the repo soon. Once that's out, please use this thread to report any other spots you find inconsistent behaviour.


> Maybe at least on the spotlight widget bring back the ability to scroll the spotlight widget left and right to cycle through spotlight items on the browse/play-more info buttons. 

@woodside007 - I've added a spin control button for the spotlight now, so that can be used to scroll through the items without affecting the navigation loop.

**Comment by adamosborne83** [comment]
OK, so I've installed the latest version.

https://imgur.com/a/zc4GHyt

In my opinion, the fact that every time you get to the 'end' of something, it then does to the menu, is not great.

Please take this as feedback and not entitlement. As over the years I've been on your github, I hope you know this.  Now, this will maybe sound simple, but in real terms, not.

Could there be almost a tick box selection for 'loop does not include menu'

Then, the only way to get to the menu would be the back button on the remote?

**Comment by adamosborne83** [comment]
Also, I'm super glad I am now able to scroll through spotlights again. 
The home screen will take getting used too, these 2 extra clicks, haha.... no pleasing some people of a free akin, with someone using their free time.

![firetv_2023-12-20_06_17_38.jpg](https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/415766b0-7c00-422b-bfd7-38c6e5c92c24)

**Comment by adamosborne83** [comment]
Thanks for this, especially as there was so little discussion around it 😀 Works brilliant.
