### ISSUE TITLE
Clock in footer

### ISSUE THREAD

**Issue by Blackysbd** [jurialmunkey/skin.arctic.fuse#358]
### Skin section

Clock and Notifications

### Current Behavior

When setting clock in right footer using view with spotlight the clock is hard to see whilst scrolling the spotlight. Also when the clock is expanded it also shows the analogue clock, both are not needed.
Would it be possible to have the expanded clock with weather at the top right of the screen as in AH2

### Expected Behavior

Clock should only show digital or analogue and should be visible at all times.

### Steps To Reproduce

Settings, furniture,right footer, clock

### Screenshots and Additional Info

![Screenshot (5)](https://github.com/jurialmunkey/skin.arctic.fuse/assets/53400821/f13e6092-dc00-4e97-a9ef-4a371b0ba6ed)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
>  Would it be possible to have the expanded clock with weather at the top right of the screen as in AH2

No. And for exactly the reason you're asking - bad visibility. 
If you think that bottom right clock is hard to see, well top right is far far far worse...

Practically impossible to read on a light background or a busy one. The whole point of *not* putting the clock there was so that I did not need to dim the background. Not to mention that space is reserved for notification toast and it will conflict with the tabbed style.

Practically impossible to see in top right:

![screenshot00338](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/a0b9173b-0209-4d56-982a-84b564609eb7)

**Comment by jurialmunkey** [comment]
>  Also when the clock is expanded it also shows the analogue clock, both are not needed.

Analogue clock is necessary in this position. All footer objects that have a text line are required to have an anchor icon. The clock acts as the anchor and is necessary when flipping to now playing so that the styles align properly.

So I have to say no to both of these requests I'm afraid.

**Comment by Blackysbd** [comment]
> > Also when the clock is expanded it also shows the analogue clock, both are not needed.
> 
> Analogue clock is necessary in this position. All footer objects that have a text line are required to have an anchor icon. The clock acts as the anchor and is necessary when flipping to now playing so that the styles align properly.
> 
> So I have to say no to both of these requests I'm afraid.

No problem, thanks for the explanation. I have the clock in the left header but no option to expand it there. 
Cheers for the reply
