### ISSUE TITLE
:bug: Odd behaviour when editing widgets of 'noop' categories

### ISSUE THREAD

**Issue by Dml2023** [jurialmunkey/skin.arctic.fuse#361]
### Skin section

Widgets

### Current Behavior

When editing or creating widgets for a category for a None (noop) category, if you have more than one, if you create a new widget, once the widget is added the customisation screen jumps to the second 'noop' category and when editing any property of the widget, as the change is made the customisation screen also jumps to the other category. Widget additions and option changes do get saved even with this issue.

### Expected Behavior

The customisation screen should remain focused on the selected category and widget being created/edited.

### Steps To Reproduce

In the Widget Customisation screen create at least 2 categories for None (noop) shortcuts
Create any widget you want for each category
As each widget is added the category will switch to the other 'noop' category.
Change a widget option of any created widget and once the change is made, the category will switch again.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Nothing I can do about it. It is a kodi thing.

Whenever a container reloads, kodi tries to refocus the previously focused item. If you've got two items in a container that both have the same path then Kodi will focus the first one. 

So when you make a change, the container needs to reload to show the change. Then Kodi forces focus to the item it *thinks* is the one you were on previously based upon its path - because you've got two items with same path (noop) then Kodi focuses first one. 

There's no way for a skin to override this behaviour.

**Comment by Dml2023** [comment]
Fair enough. Thanks for the explanation.
