### ISSUE TITLE
:bug: Stacked Folders lose navigation position after video stops

### ISSUE THREAD

**Issue by Jcloak** [jurialmunkey/skin.arctic.fuse#366]
### Skin section

Widgets

### Current Behavior

When I stop playback of a video, the position returns to the first item in the submenu and goes all the way up to the parent category as well

### Expected Behavior

When I stop playback of a video, I expect it to stay on the same widget where I started playback intially.

### Steps To Reproduce

1. Create a "Shows" category item
2. Create a submenu list for "Comedy", "Drama" etc.
3. Add a "Stacked Folder" for Seasons
4. Add an additional "Stacked Folder" for Episodes
5. Navigate to "Drama", "Some Drama Show", then navigate down to "Season 2" and choose a specific episode and start playing
6. Stop playback
7. Navigation is lost. "Shows" is highlighted, the widget also goes back to the first item in the submenu which is "Comedy"
8. At this point the navigation becomes pretty confused and I usually have to navigate up and down and around a few times to get it working again

### Screenshots and Additional Info

I think this is a recently developed issue. I'm pretty sure it used to remember the current navigation location when playback was stopped. I think it might have happened in the past 10 days or so. Also, if there is a better way to do what I'm doing, I would be happy to hear about it.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
The change was because I had people complaining that the hub windows did *not* reset to the top after opening.

But I think I'm more on your side here. The confusion from losing your position outweighs the minor inconvenience of sometimes needing to scroll up from the last position of the hub.

I possibly have a better way to handle the reset to top anyway, so might be able to solve both (have it reset to top when opening from side menu but keep position when returning back from another window)

**Comment by xyzfre** [comment]
Thank you @jurialmunkey just updated to the current version ,after playback ends is working perfect
