### ISSUE TITLE
Network logos on Home Screen Widgets 

### ISSUE THREAD

**Issue by xyzfre** [jurialmunkey/skin.arctic.fuse#373]
### Skin section

Widgets

### Feature description

If it’s possible to have an option to enable Network logos on the Home Screen Widgets

### Why is this feature needed? Please justify and explain.

I think it helps when scrolling through the home screen widgets to have the network logo available somewhere on the screen specially, for TV shows very helpful

### Screenshots and Additional Info
Thank you for this amazing skin @jurialmunkey 

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Already does work with Square layout for library. 

![screenshot00342](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/5de70ad3-e9ff-4059-939a-e3ec3ca9ef91)


I will add an update so that it also works with TMDb Helper networks list (though there's so many networks, it's not very useful to view all of them in a widget anyway).

Can't do anything about other plugins as it is dependent on the dbtype or property(dbtype) being set to studio so that the skin can identify the item as a studio.

**Comment by jurialmunkey** [comment]
Oh wait I misunderstood. You mean in the footer.

**Comment by xyzfre** [comment]
Yes on the footer would be very helpful. My apologies I should've been more specific.

**Comment by jurialmunkey** [comment]
I can only add it for the last widget in the group. For other widgets it will overlap so is not suitable.

**Comment by xyzfre** [comment]
Thank you @jurialmunkey for adding this feature 💯
