### ISSUE TITLE
:bug: TMDb show search broken

### ISSUE THREAD

**Issue by subexx** [jurialmunkey/skin.arctic.fuse#383]
### Skin section

Other

### Current Behavior

When I search tv shows it shows up, however clicking on it doesn’t do anything. In the previous version of skin I was able to long press the show and browse to the seasons. After the latest update it also broken. Nothing happens when I click on browse seasons. 

### Expected Behavior

Browse to show seasons when select from search screen.

### Steps To Reproduce

1. Go to search
2. Search show
3. Select show > nothing happens
4. Long press on show >browse lists>seasons > nothing happens

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Ah yeah it's because I changed it from a window to a dialog to help try to make the transition animation a bit smoother. But I forgot about dialogs blocking window changes. I'll change it back to a window.

**Comment by ambulancePilot** [comment]
Hi jurial! I am unfortunately still having this issue, however if I set the select action in tmdb helper to browse, it works as expected.

But if I set it to play, nothing happens when I press the select button on a TV show search result. The long press action works to bring up the context menu where I can press brows then seasons.

But I seem to recall that I used to be able to just hit select on the TV show and it would automatically bring up the seasons and episodes view?

This is only an issue in the search hub when using tmdb TV shows search.

**Comment by jurialmunkey** [comment]
@ambulancePilot - I can't seem to recreate the issue you're having. Using TMDb TV Shows either as standard search or in the discover mode opens the seasons view when I click enter / select on a tvshow.

**Comment by subexx** [comment]
> @ambulancePilot - I can't seem to recreate the issue you're having. Using TMDb TV Shows either as standard search or in the discover mode opens the seasons view when I click enter / select on a tvshow.

I had the issue when  'TMDBHelper>settings>navigation>Default select action' was set to Play. Changed it to Browse.

**Comment by ambulancePilot** [comment]
> > @ambulancePilot - I can't seem to recreate the issue you're having. Using TMDb TV Shows either as standard search or in the discover mode opens the seasons view when I click enter / select on a tvshow.
> 
> I had the issue when 'TMDBHelper>settings>navigation>Default select action' was set to Play. Changed it to Browse.

Are you also having the issue where it's set to Play and it does nothing when you hit select on the TV show?

I have a feeling this has something to do with some of the peripheral input related changes they made in Omega recently.

@jurialmunkey how can I help debug this?

**Comment by jurialmunkey** [comment]
I'm using default select as play on Omega and it works for me.

Can you give me a debug log with debug logging turned on (Settings > System) - might help see if the correct keycode / action is happening -- could be as simple as a keymap issue.

**Comment by ambulancePilot** [comment]
I am beginning to think this might be a key map issue as I do have a custom keymap. However I don't recall if I have ever remapped the select key. I'm at work now, but when I get home in the morning I will generate a debug log from a cold boot with the behavior reproduced. Thank you for getting back to me!

**Comment by ambulancePilot** [comment]
https://paste.kodi.tv/ahalecofac

Didn't have much time at home to try without my custom keymap but there is the log file. I hope it's useful!

**Comment by ambulancePilot** [comment]
Hey @jurialmunkey,

I did  some testing on my own. Here's what I did:

- removed keymap.xml (no effect)
- updated from omega b3 to nightly (no effect)
- disabled/enabled joystick support (no effect)
- changed input from IBM keyboard to tv remote and then back (no effect)

`2024-03-01 16:45:53.821 T:12120   debug <general>: Keyboard: scancode: 0x17, sym: 0x0d, unicode: 0x00, modifier: 0x0`
`2024-03-01 16:45:53.821 T:12120   debug <general>: HandleKey: return (0xf00d) pressed, window 11105, action is Select`

It seems like the correct input is being sent. The problem is also reproducible using Kore from my phone.

This is only an issue from within the search option given by the skin. When I go into tmdbh and search TV shows from there, everything works as expected. Keep in mind I have disabled search and menu on the home hub and have made my own search icon which activates 1105 (or 11105, in some places there seems to be an extra 1 in front).

Enabling the search and menu option and searching for a TV show results through the default search icon up top does not change anything. It still doesn't work.

The select button works everywhere else in kodi as expected.

Here is my latest debug log: https://paste.kodi.tv/upevicivun.kodi

I would appreciate any help! I don't think  I'm the only one with the issue.

**Comment by jurialmunkey** [comment]
@ambulancePilot 

Thanks. I don't think I'm going to get anything more from the log. As you note it shows the action is Select and that's all I was checking for to rule out a keymap issue or something to do with the recent peripherals issue on Android. Question now is why the Select action isn't browsing the show!

Have you modified your search widgets at all? Could you give me your config file? Might help see if something is wrong there
`kodi/userdata/addon_data/script.skinvariables/nodes/skin.arctic.fuse/skinvariables-shortcut-searchmenu.json`

**Comment by jurialmunkey** [comment]
@ambulancePilot 

Actually, don't worry! I managed to recreate the issue messing about with the setup! Let me see if I can figure out what is going on and hopefully should have a fix soon.

**Comment by ambulancePilot** [comment]
Thank you for replying @jurialmunkey!

[
    {
        "label": "Movies",
        "icon": "special://skin/extras/icons/film.png",
        "path": "DefaultSearch-TMDBMovies",
        "target": "",
        "widget_style": "Poster",
        "guid": "guid-b3fa42c4"
    },
    {
        "label": "TV Shows",
        "icon": "special://skin/extras/icons/tv.png",
        "path": "DefaultSearch-TMDBShows",
        "target": "",
        "widget_style": "Poster",
        "guid": "guid-9aee37fd"
    },
    {
        "label": "Actors and People",
        "path": "DefaultSearch-TMDBPeople",
        "icon": "special://skin/extras/icons/person-burst.png",
        "target": "",
        "guid": "guid-6f43082f",
        "widget_style": "Poster"
    }
]

That is the content of the file you requested. Is the target supposed to be empty?

**Comment by ambulancePilot** [comment]
Oh my god I'm glad you sorted it out!

It's strange that target was being set to none as recall this being a rather recent issue. But maybe I had never used default TMDbH search widgets previously and was using custom search strings. I can't remember. Either way. Thank you so much!

What should the target be in that case? Maybe I can insert it myself while you push an update at your convenience.

Thank you so much <3

**Comment by jurialmunkey** [comment]
Yeah target should be videos. There's some issue here with it not passing through when re-adding one of the defaults.

Reason it was working for me is because I never deleted the original from the search, but when you re-add it from the defaults for some reason the node value isn't passing through to the target.

**Comment by ambulancePilot** [comment]
I think that is what happened to me! I was always using the default search configuration until I messed around with it and used a custom search string for another addon. Didn't like it and then it never worked after I set it back to default.
