### ISSUE TITLE
Endless (cycled) scrolling of the home menu

### ISSUE THREAD

**Issue by patkino** [jurialmunkey/skin.arctic.fuse#4]
### Skin section

Home Widgets

### Feature description

Cycling of navigation, so there'll be no need to go back-back-back before entering a new hub

### Why is this feature needed? Please justify and explain.

Too many presses while navigating

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Can you explain a bit more.

Do you mean when you reach the end of the widgets at the bottom it will scroll back up to the fullscreen widget (and vice versa going the other way)? Or do you mean something else?

**Comment by patkino** [comment]
E.g. when you reach the end of submenu of the first widget and press down - nothing happens now. My suggestion is to move to the next widget.
And for the last widget - move up to the fullscreen

**Comment by jurialmunkey** [comment]
>E.g. when you reach the end of submenu of the first widget and press down - nothing happens now. My suggestion is to move to the next widget.

I'm not quite sure what you mean by "submenu of first widget" ???


![screenshot00087 (2)](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/51d0a687-15ae-46eb-ab69-2f33f19a2f4e)

^^ Do you mean e.g. in that image moving from the "Netflix" button in the submenu down to the "Random TV Shows" widget is not working? Because it should.

>  And for the last widget - move up to the fullscreen

Yeah that can be added.

**Comment by patkino** [comment]
> ^^ Do you mean e.g. in that image moving from the "Netflix" button in the submenu down to the "Random TV Shows" widget is not working? Because it should.

What I mean is (at your screenshot) - when you move down from Netflix to "Random TV Shows" and press down again - you get stuck at the bottom of this branch.
I suggest to navigate further to "Music"

**Comment by jurialmunkey** [comment]
Ah I understand.

It would need to just focus the side menu at the item (rather than click into the next hub) but that can be done. 

I actually used to do that in an earlier version - up from play button goes to sidemenu one position up (so focuses movies in this case), and down from end of widgets goes to sidemenu one position down (so focuses music in this case).

Also btw you can map a key to the "menu" command and that will automatically open the sidemenu no matter where you are. I mapped longpress back on my remote: so one tap to go to start of row; double tap to go back; and longpress to open menu.

**Comment by jurialmunkey** [comment]
Okay next version will have an option:
`Skin Settings > Navigation > Widget group end action`

Can choose `Loop` `Menu` or `Bump` 
Should be pretty self explanatory what each does.

**Comment by patkino** [comment]
Well, thanks for considering. 
There are three options now, but none of them allows to go further down to the next sideman item. Only gets you back to the side menu.

**Comment by jurialmunkey** [comment]
> none of them allows to go further down to the next sideman item

I did try that but it was really weird when it was setup. It just felt really awkward.
