### ISSUE TITLE
Art work for shows/movies not found

### ISSUE THREAD

**Issue by DROIDshield** [jurialmunkey/skin.arctic.fuse#407]
### Skin section

Widgets

### Feature description

Recently I've noticed when TMDB helper shows widgets  some tend not to have any art work at all. Is there a way I can get tmdb helper to go find the artwork some place else rather than where it is already looking? 

I have all of the API keys installed for everything in tmdb helper that requires one but still I have this issue.  Or can a delete button be added to the context menu so  programs or movies like this can be removed from the list?
![20240110_200719](https://github.com/jurialmunkey/skin.arctic.fuse/assets/97023369/ef6dc195-431b-4b21-9cca-2c5bca65f3b9)
![20240110_200749](https://github.com/jurialmunkey/skin.arctic.fuse/assets/97023369/1d09d565-8b6a-4e9a-b355-ff714803308b)

### Why is this feature needed? Please justify and explain.

To keep the setup looking clean and uniform.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
This is not really anything to do with the skin.

The simple way to "solve" this issue is to upload the missing artwork to TMDb or FanartTV.
https://www.themoviedb.org/tv/9722-10-days-that-unexpectedly-changed-america
https://fanart.tv/series/81412/10-days-that-unexpectedly-changed-america/

There's no sense in having an option to select artwork manually because you could just upload it instead and then everyone will benefit.

Complex rules about deleting items from lists would be a complete pain to manage. If you want curated lists, that's what Trakt and MDbList are for. It makes no sense to remove items from TMDb simply because they have no artwork.
