### ISSUE TITLE
[Feature] ability to edit hub label and icon

### ISSUE THREAD

**Issue by 666jones** [jurialmunkey/skin.arctic.fuse#43]
### Skin section

Home Widgets

### Feature description

I was trying to create my own hub with widgets. I edited the music hub but I'm unable to change the label or icon. So I created a a custom side menu and pointed it to the music widget this way I could change the label and icon. However when in that hub it still says music at the top (page title I think it's called) also this method makes it so when I'm in this hub it's not got the little coloured dot next to the focused side menu 

### Why is this feature needed? Please justify and explain.

Just makes things more customable

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Changing the icon for non custom items doesn't make sense because they are linked to the content type. Eg the "movies" shows the indicator dot when the library view contains movies or sets, not just when the hub is visible (same for tvshows, music, pvr, addons etc)

What's really needed here are some properly custom hubs - I'll need to figure out a good way to manage that as currently they are all individually hard coded.

**Comment by 666jones** [comment]
Yh I agree some hubs that could be more customised would be cool. For the meantime I'll just stick with the edited music hub. It's no issue just has the music title when I'm in that hub and tbh I rarely go in that hub. It's the only one that I needed to change the label on so no big deal. Really like this skin. Sorry I posted so many requests I was just posting them before I forgot

**Comment by jurialmunkey** [comment]
> Sorry I posted so many requests I was just posting them before I forgot

No that's complete okay! Please do make requests/suggestions. I want to encourage people to do that as it only helps to make the skin better -- obviously I'll disagree about some things or there might be technical limitations which mean some things aren't possible but overall I'd rather people be engaged and making suggestions even if it turns out I don't implement them.

It's only when people act like I owe them something and get upset if I don't want to do something- that's when it gets annoying because obviously this is my free time I spend on a passion project and not my actual job.

**Comment by 666jones** [comment]
> > Sorry I posted so many requests I was just posting them before I forgot
> 
> No that's complete okay! Please do make requests/suggestions. I want to encourage people to do that as it only helps to make the skin better -- obviously I'll disagree about some things or there might be technical limitations which mean some things aren't possible but overall I'd rather people be engaged and making suggestions even if it turns out I don't implement them.
> 
> It's only when people act like I owe them something and get upset if I don't want to do something- that's when it gets annoying because obviously this is my free time I spend on a passion project and not my actual job.

Ok I wrote afew more things down I'll post them at some point today :) and I completely understand things have limitations and won't be possible. I actually read alot of peoples messages to Devs and have come across afew where there very rude about things and do act like there owed something I don't think they understand that all your doing is helping, giving support, features and services for free in your own time . However alot of people are cool and show a huge amount of respect which is nice.

**Comment by jurialmunkey** [comment]
`Skin Settings > Menus > Item X > Custom`
`Skin Settings > Menus > Item X > Customise Action > Hubs > Custom Hub XX`
`Skin Settings > Menus > Item X > Customise Hub`

**Comment by xyzfre** [comment]
Thank you @jurialmunkey for adding this feature this is a really good one 💯💯

**Comment by AakashC2020** [comment]
Thank you @jurialmunkey for adding the Custom hubs feature in this skin! It's really great and very useful!
