### ISSUE TITLE
This is a question not Issue.  Backwards compatible or not?

### ISSUE THREAD

**Issue by DROIDshield** [jurialmunkey/skin.arctic.fuse#436]
### Skin section

Other

### Feature description

@
skinvariables-shirtcut-sidemenu.json

Could you tell me if this file is backwards compatible ie, I've copied the file from my Shield (Android) to my laptop(Windows) 
The shield has the best setup and I wanted to port it across to my laptop but it seems to not work.

Or if you could remind me of the steps I need to do to make it work I'd  be grateful. 

### Why is this feature needed? Please justify and explain.

Would like to make my PC theater setup as my Shields around the house.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I'm not quite sure what you mean by "backwards" compatible?

If you mean is it platform agnostic and works on any platform, then the answer is yes -- you should be able to copy the config files over to a different platform as long as you put it in the right place (i.e. copying to/from the addon_data folder for the profile)

Make sure Kodi is closed when you do this because the config is saved to memory and so it will simply overwrite any file you add to addon_data if Kodi is open.

**Comment by jurialmunkey** [comment]
You must also rebuild go into widget config and rebuild widgets for the change to take effect.

**Comment by DROIDshield** [comment]
Thats the bit I forgot, go into qidget config and rebuild. Thanks again.
