### ISSUE TITLE
:bug: Home doesn't return to first widget in group

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.fuse#439]
### Skin section

Widgets

### Feature description

Would it be possible to have an option to always display the first widget in the visible widget group when returning to the home screen. Currently the previously visible widget is displayed.

### Why is this feature needed? Please justify and explain.

Clearer navigation. At the moment on return to the home screen the user doesn't know if there any widgets "above" the displayed widget

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Pressing back again should take you to the top of the group if there are more widgets above. Is it not working?

I think it's a bit confusing to go back to top immediately when it is not the one you clicked on (eg think of widget with albums/tvshoes where you click to see songs/episodes but then decide you want to go back and play something different you saw - I think the general expectation is that pressing back takes you back to where you were previously) . But more importantly there's no real good way to manage it because each group will have a different top widget ID - whenever I've tried to do something like that previously it's ended up becoming a bit of a mess trying to handle that and it ends up creating situations where focus gets stuck.

**Comment by berkhornet** [comment]
Many thanks for the explanation. I can confirm that when pressing "back" as suggested works.

The use case that confused me was selecting a side menu item to open the library when the first widget in the group was not visible (for example with focus on the menu item, press "right", "down", "left", "select"). Then when in the library navigate left and press "close". In this case the focus is on the side menu item, and it is necessary to press "right" and then "up" x times  to display the first widget in the group. And it's easy (for me at least) to forget there are widgets above the one displayed!

Would it be possible to optionally show some navigation arrows (up and down) if there are additional widgets available (say next to the widget label or side menu item). If I recall correctly AH2 had this option. 

Totally understand if this isn't feasible - many thanks for a great skin!

**Comment by jurialmunkey** [comment]
> The use case that confused me was selecting a side menu item to open the library ... And it's easy (for me at least) to forget there are widgets above the one displayed

Yeah I agree about this one. Now that you've pointed it out, I've definitely had this same sequence of events happen and been confused by it because you can't press back to reset. Just forgot about it because recently everything I've watched started in a widget.

Will need to have a think about best way to address it. I guess ideally when clicking a side menu item the focus would reset to the top of the group before you leave so its already waiting like that when you return.

> Would it be possible to optionally show some navigation arrows (up and down) if there are additional widgets available 

This is an idea I keep returning to. It's less about whether its possible (definitely is) and more about it being visibly obvious enough to be useful without looking ugly -- in AH2 it was a bit easier for the up arrow since the background had a bit of a fade already but in Fuse the brightness of the background makes it a bit trickier.

**Comment by berkhornet** [comment]
Thanks for response. Happy to run any tests if required.

**Comment by berkhornet** [comment]
Thank you.
