### ISSUE TITLE
bug: skin crashes Kodi if no widgets are within a menu

### ISSUE THREAD

**Issue by Vigmos** [jurialmunkey/skin.arctic.fuse#441]
### Skin section

Widgets

### Current Behavior

Hey, almost a perfect skin, but one annoying issue(may have been reported before but I'd sit see it.) If I have a sidebar menu items and I don't want any widgets within that menu, if I select left or right on my remote on that side menu item then Kodi will freeze completely and requires a force close. I know I could just add a random widget/shortcut to this menu item to stop this occurring but I simply want a shortcut here without anything else.

### Expected Behavior

Nothing, pressing left or right on a menu item with no widgets should not cause anything to occur. It's as if it tries to select a non existing widget.

### Steps To Reproduce

(using classic mode for the homescreen layout)
1. Go to skins settings
2. Select customise widgets
3. Add a new items to the left menu bar. L et's call it "my folder" which is the 3rd menu items
4.  Do not add any any widgets then go back to the Kodi homescreen.
5. From the sidebar scroll to the new menu item "my folder".
6. Press left or right on your remote.
7. The application will now freeze and requires a force close.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Vigmos** [comment]
Thanks I will take your advice and look into this. I know it seems like a weird approach, but it was 1 item in the menu I didn't need widgets for simply because there are no widgets related to the shortcut I wanted, everything else I use plenty of widgets. I thought it would just be good to atleast report that if you don't have widgets it will essentially break it. Thanks

**Comment by jurialmunkey** [comment]
Why not put the shortcut in the options menu then? 

In terms of the actual crash, the code to manage the focus is complicated but sending focus to a non-existent control should not cause Kodi to crash. Not sure what platform/version you're on but this sounds like a Kodi bug.

Skins technically should not be able to cause a crash by using normal commands and if they do it means there's some sort of error handling that has been missed in the core code. It's not really something that should even be "fixed" in the skin because it's not really the skins fault -- if Kodi gets told to focus a non-existent control it should simply do nothing not crash.

**Comment by jurialmunkey** [comment]
^^^ This will avoid the crash but I still really do not recommend this type of setup as you will have weird behaviour and possibly will end up with focus getting stuck somewhere.

**Comment by Vigmos** [comment]
Yea the focus getting stuck is the issue. I will just find a messy workaround or use your suggestion to put it in the options menu. Thanks.

**Comment by jurialmunkey** [comment]
The crash is not caused by focus getting stuck. The crash is caused by a recursive loop.

Each widget group has a bumper at the top and bottom. The issue when you have no widgets is that the bumpers keep bumping focus between themselves recursively forever until Kodi crashes.

The change above fixes that so it will not crash.  

However, it is still possible to get stuck with no valid control to move to and so you would need to use the mouse to regain focus. That's what I mean when I say focus might still get stuck. But it won't crash anymore because there's no recursive loop.
