### ISSUE TITLE
Card View Ratio

### ISSUE THREAD

**Issue by Liquidrag** [jurialmunkey/skin.arctic.fuse#448]
### Skin section

Widgets

### Feature description

I'm wondering why the card's landscape box ratio isn't like the ratio you have set for board view.

### Why is this feature needed? Please justify and explain.

Currently, it cuts off the image and if it were consistent with the board ratio, IMHO it would lead to a better cohesive design.  

### Screenshots and Additional Info

Current card ratio cuts off the image.
<img width="1235" alt="Screen Shot 2024-01-28 at 12 32 34 PM" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/3e550ec2-7f60-4c65-9fa1-1a1f2583beaa">

<img width="1240" alt="Screen Shot 2024-01-28 at 5 27 45 PM" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/e755c6c1-bd82-4077-86c6-5bfad35f995b">

Board ratio does not.
<img width="1235" alt="Screen Shot 2024-01-28 at 12 32 34 PM" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/44c6f48a-e662-41c0-a653-af2156d68284">

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
In short, mostly because of alignment:

The posters need to maintain their alignment on the x axis for the transition animation to have the correct coordinates. They also need to properly align to the right edge of the screen to maintain a consistent appearance with the other layouts.

For the card style to meet both those conditions, the "card" width must be a multiple of the poster width.

- A poster widget item is 294px tall, 200px wide, and has a 40px item gap.
- At three posters wide, that makes the "card" 680px wide
- At 680px wide, a 16:9 image will lose 88.5px on the vertical `(680/16*9)-294=88.5`
- At two posters wide, that makes the "card" 440px wide.
- At 440px wide, a 16:9 image will lose 82.7px on the horizontal `(294/9*16)-440=82.7`

So no matter which way we go, we lose about 85 pixels of the image edge. 

I went with wider rather than narrower because my original idea for the card style was to be a sort of half way between a banner and landscape. In the original it was actually just two cards but I found that was too wide, hence bringing in the posters.

**Comment by Liquidrag** [comment]
Thank you for the answer. I wonder if it would be too noticeable if you took a few pixels from the posters.

**Comment by jurialmunkey** [comment]
It's the same issue with alignment and the animation transition though. The reason why it's so important is because the transition animation basically fakes the view (similar to the wall) so it needs reusable parts to cut down on all the extra hidden objects.

Plus I think shaving 20+ px off each poster would be pretty dramatic (got to remember posters are smaller surface area already so changing their dimensions has a bigger overall impact on their ratio). It's essentially the same issue again about artwork cropping but just shifted to the posters
