### ISSUE TITLE
Category widget rename bug?

### ISSUE THREAD

**Issue by JFG1000** [jurialmunkey/skin.arctic.fuse#451]
### Skin section

Widgets

### Current Behavior

When renaming the category widget to something it just display as intended, it's hard for me to explain but in the photo above the highlighted bit i tried to rename to, movies and the other section to shows etc, it just stays as "home" using classic style. 

### Expected Behavior

The section to rename successfully

### Steps To Reproduce

Skin widgets, edit, rename 

### Screenshots and Additional Info

![RDT_20240129_0741094503181007796891085](https://github.com/jurialmunkey/skin.arctic.fuse/assets/76907836/09399c34-ac15-4e83-9ac3-4269a80e9f1a)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by JFG1000** [comment]
EDIT : if it's working as intended do you think it's possible that when we rename each section it can appear at the top of the screen where the home is labeled so it gives abit more info as to what section we are viewing?

**Comment by jurialmunkey** [comment]
Renaming the shortcut will not change the name of the home window.

The only reason it works for a hub is because hub windows are custom windows without names and clicking a hub shortcut has a special extra action to set a special property which changes the fall back name when the window doesn't have a name.

I see you're talking specifically about classic mode - so I guess that makes sense to have an option for the header to show the label only for that mode.

**Comment by JFG1000** [comment]
Ok many thanks for confirming I've been trying to figure it out for ages, so is this something you could implement for us classic mode users? Would be greatly appreciated
