### ISSUE TITLE
:bug: Series/Season Finale Indicators not shown

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.fuse#461]
### Skin section

Library

### Current Behavior

I think this is more of a question than a bug. I tried out this feature yesterday and managed to display the Series/Season indicators as intended. This morning, they don't show. I have the latest versions of Arctic Fuse and TMDbHelper installed. I guess I've accidentally changed some settings somewhere. I have the Premiere/Finale indicator option set to true, but the banner is not displayed within TMDbHelper/Trakt/Your Next Episodes. Is there anything else that could prevent the display of the banner. Thank you.

### Expected Behavior

Season/Series banner displayed correctly

### Steps To Reproduce

I take the steps described above. Worked yesterday but not today.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Okay so this is really random and I only know this because I just discovered it myself from you asking about sorting order -- but fairly sure it's because you changed your sort order to recently watched for next episodes.


The episode type comes from the Trakt extended episode details. Because Next Episodes is based on In-Progress, which, in turn, is based on Watched History, then it is already pre-sorted according to recently watched and there's no reason for TMDbHelper to get those extended details to do more advanced sorting.

You can get around this by setting sorting to "today's" instead. That keeps recently watched order but pushes episodes airing today to the front of the list (which forces getting the extra details to check).

FYI lastweek is similar but extends the period to a week. That's my personally preferred one as I generally want to continue what I've recently been watching but I also want to be alerted to a new episode from a show which hasn't aired in a long time and thus I haven't watched recently (e.g. for a new season premiere...)

**Comment by berkhornet** [comment]
Many thanks - I’ve done as you suggested and everything is displayed again correctly.

Mick Rollitt
________________________________
