### ISSUE TITLE
:bug: Not all view types available

### ISSUE THREAD

**Issue by linesquarecube** [jurialmunkey/skin.arctic.fuse#462]
### Skin section

Library

### Current Behavior

I can only use square and list as view type in the episodes layer or any sub-layer of a video add-on. 

### Expected Behavior

I expect to be able to use all available view types in video addons. Comparing the same layer in AH2 on the same Kodi installation, I can select 9 different view types.

### Steps To Reproduce

Example Addon - ARDundZDF (german public television)
1. Select series to watch or subcategory from widget
2. Move up to change view type
3. See only two possible types to select

### Screenshots and Additional Info

First screenshot shows available view types in AF
Second screenshot shows the layer I'm on in AF.
Third screenshot shows available view types in AH2
Fourth screenshot shows the layer I'm on in AH2.
![01_viewtypes_af](https://github.com/jurialmunkey/skin.arctic.fuse/assets/81855936/7ebc8e51-a236-4c78-9c9d-fb76d4a90d91)
![02_layer_af](https://github.com/jurialmunkey/skin.arctic.fuse/assets/81855936/cb89bc39-27a7-4bfc-8c30-3e2600163526)
![03_viewtypes_ah2](https://github.com/jurialmunkey/skin.arctic.fuse/assets/81855936/d50ff9c6-b2e7-4448-97d5-f67ddf64510f)
![04_layer_ah2](https://github.com/jurialmunkey/skin.arctic.fuse/assets/81855936/545dfd35-daf9-4563-9e6b-1512c87c80f5)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This is an addon issue. It is not correctly setting the content type to episodes. 

You can see in the header of the dialog that the content is "none", so you only get options for none (which are square and list).

You will need to speak with the addon author and get them to fix their addon to set the correct content type.

**Comment by linesquarecube** [comment]
Thank you very much for that hint. Is there any workaround if the author of the addon is not willing to change the content type to something reasonable? Would it be easier if I play around with the addon or with the skin - I'm not a developer but I can fix some stuff if I know where to look :)

**Comment by jurialmunkey** [comment]
It is very simple for a plugin to add content type, so I'm not sure why they wouldn't want to - if those are episodes then content type should be set to episodes so that the skin knows how to display them.

It is literally one line before ending the directory
http://alwinesch.github.io/group__python__xbmcplugin.html#gaa30572d1e5d9d589e1cd3bfc1e2318d6

**Comment by jurialmunkey** [comment]
Ah I see in linked issue that they have a setting to enable it globally. That's going to be your best bet.

Not quite sure I understand why it is so difficult for the plugin to be able to determine the content type but I'm sure there must be a good reason - but takeaway point is that if the plugin has difficulty determining it based on the info it has at hand and where it has a proper programming language to use, then the skin has no hope of figuring it using just skinning xml!

 So only real option is going to be to use that global setting to set the plugin always to episodes but it will mean you have the one view for the entire plugin including any menu directories - because it essentially means the plugin is providing no hints that it's a different type of content and thus should have a different view.
