### ISSUE TITLE
Text or Box Icon row,  Audio format be should shown here too ?

### ISSUE THREAD

**Issue by DROIDshield** [jurialmunkey/skin.arctic.fuse#469]
### Skin section

Widgets

### Feature description

See pic, no audio icon shown on this box row.

### Why is this feature needed? Please justify and explain.

A feature that I believe should be shown
![20240205_224731](https://github.com/jurialmunkey/skin.arctic.fuse/assets/97023369/b6ffa0a5-8104-4780-8ae8-0b7ab8480b40)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
What do you mean by "audio icon".

Codecs are only ever shown in the footer.

**Comment by DROIDshield** [comment]
Sorry been away abit, yes I did mean the codec for the audio  so it would look like:

4K 2009  PG  2HR 33 MINS  DOLBY ATMOS 7.1 ENDS 18:37

But as you said and I guess once the particular movie 8s highlighted the codecs show up at the bottom left and now in colour too so I guess you have done this already.

**Comment by jurialmunkey** [comment]
Yeah there wouldn't be space for all that info.

Plus info line is not really intended for info about the file, only info about the item (eg genre, rating, year etc are about the movie itself whereas resolution, audio tracks etc are about the file it will be played with  so go in the footer instead) 

So technically I don't even think the resolution tag should go there but I keep it because it works as a decent anchor.
