### ISSUE TITLE
:bug: Video Versions dialog changed

### ISSUE THREAD

**Issue by Dml2023** [jurialmunkey/skin.arctic.fuse#478]
### Skin section

Video Info Dialog

### Current Behavior

Hi Jurialmunkey,

It appears that the Video Versions window display has changed in a recent version. On Version 0.4.64 this window displayed with the artwork in the left with the Movie titles on the right and details about each title listed on a second line. In the latest version, the artwork is now on the right with movie titles on the left, but the 2nd line just shows the file name.

### Expected Behavior

Was wondering if this was an intentional change or if the earlier version on this window will be re-implemented.

### Steps To Reproduce

Open a movie with multiple versions with the Video Media setting for 'Show videos with multiple versions as folder' disabled.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
The side switch is intentional. Brings it inline with the rest of the skin where artwork always on right side and text on left (e.g. wiki, media list). 

But the label in the list I definitely messed up when I switched the sides. I noticed this myself last night. This was a good reminder because I almost forgot to fix it today!
