### ISSUE TITLE
Clear function box next to search unavailable 

### ISSUE THREAD

**Issue by JFG1000** [jurialmunkey/skin.arctic.fuse#486]
### Skin section

Other

### Current Behavior

I've noticed recently that the box that a number of functions including "clear" next to the search box has dissappeared, was this intentional or is it perhaps a bug? 

### Expected Behavior

We can usually use a couple of functions whilst making a search for something, clear being one of them

### Steps To Reproduce

Navigate to search there is usually box to the right of the search box 

### Screenshots and Additional Info

![Screenshot_20240212_170116_Gallery](https://github.com/jurialmunkey/skin.arctic.fuse/assets/76907836/767defbe-3bca-4ffc-854b-0597658e7941)

I've highlighted the area where the box used to be that had the "clear" function 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by xyzfre** [comment]
I noticed the same thing today. It was a nice feature to have,if possible could it be re-added would be really grateful

**Comment by jurialmunkey** [comment]
It is intentional.

There is not visibility in that location when the background is shown.

All these features are possible by clicking the node button to toggle between Search, Library and Discover.

 When you switch to library or discover mode, a filter icon appears next to the mode button. From the filter button you can access all filters in a single dialog. The dialog also has a clear button to reset all the filters.

Search does not have any filters so it also does not have a clear filter button
