### ISSUE TITLE
Retaining renamed widget when using SkinVariables

### ISSUE THREAD

**Issue by Liquidrag** [jurialmunkey/skin.arctic.fuse#489]
### Skin section

Widgets

### Feature description

Would love it if when you rename a widget that points to a SkinVariable it would retain what you named it.

I am currently on Omega Beta 2 
Arctic Fuse v0.4.71~omega

### Why is this feature needed? Please justify and explain.

I currently have a "New Movies"Widget that points to a SkinVariable list that has a couple of Trakt lists but the title of those lists show instead of "New Movies" 

### Screenshots and Additional Info

In settings, I have renamed it "New Movies"
<img width="1242" alt="Screen Shot 2024-02-13 at 11 32 39 AM" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/2c3a0200-fa67-4e7d-8246-faafba3fb472">

Widget shows the name of the trakt list instead of "New Movies"
<img width="1230" alt="Screen Shot 2024-02-13 at 11 33 19 AM" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/47ea95f6-1ab9-470f-b819-bcff6416e773">

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
There's a few widgets like SkinVariables, TMDbHelper Recommendations/Based-On/Random, and Stacked widgets which are have special naming behaviour to allow for dynamic names (e.g. "Because you watched {film title}").

The dynamic name comes from `ListItem.Property(widget)` attached by the plugin. In SkinVariables filters, if this property is set for items in the original path then it is also passed through to the filtered list.

That's what's happening here - your filter is based upon a Trakt list which sets its name to the "widget" property, so that's passing though to the items shown in the filtered list (and because a filtered list is one of the special lists, the skin uses the dynamic name if available).

You can override this behaviour by editing your filter and setting your own custom names for each path. If a path has a custom name then it will override any "widget" property value from the original item.

**Comment by Liquidrag** [comment]
Renaming it works. Thank you!
