### ISSUE TITLE
[BUG] No way to remove background from widget or home page

### ISSUE THREAD

**Issue by 666jones** [jurialmunkey/skin.arctic.fuse#49]
### Skin section

Home Widgets

### Current Behavior

I'm unable to remove the background for the home or side menu items. The closest I could do to remove it was enter noon as a custom command but I think that shows as a error in my Kodi log. Doesn't seem to affect me at all. But a option to select none would be more simple 

### Expected Behavior

A option to disable or set none as the background 

### Steps To Reproduce

Skin settings
Edit home menu select background
No option to disable to background widget

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
It's a bit of an essential part of the skin to have the background spotlight widget. If you don't want a background widget you need to set the layout to be the basic "widgets only" one. 

For the layouts with the categories/submenu, the background spotlight widget is fairly essential because there needs to be something above the categories -- otherwise there is just a massive blank space.
