### ISSUE TITLE
Touch support help

### ISSUE THREAD

**Issue by spursgalea** [jurialmunkey/skin.arctic.fuse#492]
### Skin section

Mouse and Touch

### Current Behavior

Hi I love this skin  and can't see me using another skin in the  foreseeable future. there is one small issue I have.when I am in a add-on for example the movie db helper.i can not access the movie dB  Discovery  section when I touch it I end up the movie  dB movies. When I  touch  movie  dB movies. I end up movie  dB  and up  movie  dB tv shows and so on. I do understand that this skin is designed to be used by a remote. I just like it so much I want to use it on all my devices including my tablet and phone. Is there a why to fix this if it can be fixed thanks . I'm sorry if I posted as a bug if it isn't a bug it's just it's not a feature request as such

### Expected Behavior

Explained abbove

### Steps To Reproduce

Enter add-on and unable to access first category using touch

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
It's because of the way kodi list containers work.

The items need to be offset on x axis so that the main focus item isn't hidden under the side menu and is in correct alignment.

 Problem is that Kodi doesn't also have a way to offset or control the hit box of the items, so the hit box for each item is behind by the same amount as the how much the artwork needs to be offset for the padding from the left screen edge.

**Comment by spursgalea** [comment]
Thanks for the explanation

**Comment by jurialmunkey** [comment]
Landscape is already available for addons as a viewtype.

Which viewtype are available depends on what container content type the addon sets

Landscape is available for movies, videos, tvshows, episodes, seasons, artists, sets.

If it is not available it means the addon is not setting the content type correctly - you can see what content type the addon is setting in brackets at top of viewtype selection dialog. 

If the type is "none" but it is actually playable content of one of those types then you should speak to that addon author so that it displays correctly.

**Comment by spursgalea** [comment]
Thanks for the suggestion.am changthe correct viewtype.

**Comment by spursgalea** [comment]
Hi I hope you  get a notification for this message because see the issue is marked as closed. Thankfully I worked it out. I've changed all the square viewtypes form Square to list wall. the skin works great now on my touch device. Thanks for looking into the issue and explaining what it was. This is the best thing I've ever used an appreciate your work

**Comment by jurialmunkey** [comment]
No worries. Glad you figured it out.

I hadn't really thought about it being difficult on a touch device to press down to access the controls where you can change the view directly (but of course it is), so you have to rely on using the changer in skin settings instead which involves a bit more guess work to figure out the content type!

Anyway I had a few requests for an option to disable the "peek" on the screen edges so when I get to adding that I think it might inadvertently double as a "touch mode" since it will effectively remove the x offset from views.
