### ISSUE TITLE
:sparkles: Suggestion for touch mode

### ISSUE THREAD

**Issue by icarok99** [jurialmunkey/skin.arctic.fuse#498]
### Skin section

Other

### Feature description

1 - Return the keyboard to its previous position

2 - The context menu options must be clickable without the need to open another context menu 

3 - Suggestion when you click on the search option, the search bar appears in top, Similar to the default Kodi skin.

### Why is this feature needed? Please justify and explain.

It looks more visually beautiful the way I'm suggesting.

### Screenshots and Additional Info

Illustrative picture

![IMG_20240217_103230](https://github.com/jurialmunkey/skin.arctic.fuse/assets/46580318/cb81abf5-c56d-4bdd-a0be-ad0c975b2b54)

![Screenshot_2024-02-17-10-45-24-237_org xbmc kodi](https://github.com/jurialmunkey/skin.arctic.fuse/assets/46580318/1fccf436-f8c4-4d5c-8c6e-7f7746800eff)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Keyboard at bottom blocks what you are searching for with large keyboard.

**Comment by jurialmunkey** [comment]
BTW touch mode is not meant to change the design of the skin. 

It is only meant to make widget items easier to interact with touch/mouse by removing the items which "peek" from the screen edge. That reduces the artwork x-axis offset and places it closer to the actual hitbox to make it easier to click/touch the artwork and have the expected action/focus.

That's why it's called "touch mode". It isn't meant to redesign the skin to make it compatible with touch. I'll need to rename the option if it is being is misunderstood.

**Comment by jurialmunkey** [comment]
BTW for keyboard I agree that it looks nicer at the bottom but it is also less functional


For example, here it completely blocks visuals of all search results:
![screenshot00400](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/409441e1-173b-4895-96cb-1bbc6da3eb97)

Whilst at the top it at least shows you some of the results:
![screenshot00398](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/76a8f051-f208-4b11-bfb5-2facb3001298)

**Comment by jurialmunkey** [comment]
Actually, thinking about this gave me a really good idea just now.

Instead of moving keyboard to top, I can keep it at the bottom and instead slide the items up so that they peek out from underneath. It seems to work really well - best of both worlds!

![screenshot00402](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/77973e26-c303-4f2d-905c-5b2e801457d1)

**Comment by icarok99** [comment]
Yes, It's better, it's perfect.

**Comment by icarok99** [comment]
@jurialmunkey Have the buttons been disabled?

Quit, reload and close.
![IMG_20240307_201233](https://github.com/jurialmunkey/skin.arctic.fuse/assets/46580318/782db603-0feb-4e22-a72f-adc17c8534a5)
![IMG_20240307_201244](https://github.com/jurialmunkey/skin.arctic.fuse/assets/46580318/a8383493-e5c6-467a-bbc7-c8a9032b80fd)

**Comment by icarok99** [comment]
Without the buttons make it difficult to close things and exit Kodi because not everyone leaves the tauch screen buttons always visible.

**Comment by icarok99** [comment]
I always have to drag my finger to display the touchscreen buttons.

**Comment by jurialmunkey** [comment]
You should be able to two finger tap (or right mouse click) to go back.

But I will be adding soon to always display side tab if touch mode is enabled.

BTW you can configure the options panel in the widget customisation screen by clicking the option icon there.
