### ISSUE TITLE
Background image add a folder also

### ISSUE THREAD

**Issue by DROIDshield** [jurialmunkey/skin.arctic.fuse#499]
### Skin section

Other

### Feature description

Not sure if this has been asked before but I haven't found a trace.
Would it be possible to also add a background folder for images rather than just a image see atm I have groot as mine and yes it shows up at the end of thewidget row or if a movie or TV programme doesn't have a background image, but a folder with image that this feature could randomly pick from would be great..
 Ie like the startup folder already does and works the same way.
![20240217_215747](https://github.com/jurialmunkey/skin.arctic.fuse/assets/97023369/83ac6f15-357a-4536-9e26-5f40c82b822d)

### Why is this feature needed? Please justify and explain.

This feature i believe would enhance the look of the widgets with no background image in the folder or when the system looks up via tmdb helper 

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
This is not how the "custom" background is intended to be used. It is meant to be a low detail, low filesize, relatively plain image to be used as a plain background *behind* the fanart (i.e. as an alternative similar to the supplied options).

The background image is *always* rendered on a separate layer behind the fanart. So you're adding a lot of extra render strain here by using a high res, high detailed image with a large filesize for the background. You're effectively rendering two fanart all the time instead of one because the background is rendered first then the fanart image over the top.

I will add a separate different setting for adding a fanart fallback image/folder. You should stop using the background option this way.

**Comment by DROIDshield** [comment]
I thanks for the detailed info on how it works... well I will try it on the Shield and see if this slows it down then I will remove it... I know on my very powerful laptop it will be fine... but will see how it fairs.. thanks for adding the options though..👍

**Comment by jurialmunkey** [comment]
The issue is not the the new option. That will be fine.

The issue was with how you were using the old option. The "custom" window background is only meant to be a simple image as it will always be rendered behind the fanart even if there is fanart available.

i.e. the skin artwork is layered like so (from back to front) 

-> Background image
-> Fanart layer
-> Foreground items and info

So by you changing the background to a complex image, you are rendering two large images instead of one (background+fanart).

The new option only modifies the fanart layer, so it is a much better use of resources. You should set your background back to a simple background then use the new option for your fallback artwork.

**Comment by DROIDshield** [comment]
I've done this and it is absolutely fantastic... picking a different image where there is none and adding on from the folder even at the end of a widget row.. as seen in the image.. this is exactly what I was wanting it to do..all the thanks in the world. I feel it's time for a Kofi...👍
![20240221_215804](https://github.com/jurialmunkey/skin.arctic.fuse/assets/97023369/7f5c15d8-b1ec-4036-a029-8c83396178b5)

**Comment by xyzfre** [comment]
> I've done this and it is absolutely fantastic... picking a different image where there is none and adding on from the folder even at the end of a widget row.. as seen in the image.. this is exactly what I was wanting it to do..all the thanks in the world. I feel it's time for a Kofi...👍
> 
> ![20240221_215804](https://github.com/jurialmunkey/skin.arctic.fuse/assets/97023369/7f5c15d8-b1ec-4036-a029-8c83396178b5)
> 
> 

My apologies I know this is off-topic, but how did you get the percentage number to show up with the progress icon? Does this only work for library items ?

**Comment by DROIDshield** [comment]
Very nice indeed...👍
