### ISSUE TITLE
Info outline suggestion

### ISSUE THREAD

**Issue by Liquidrag** [jurialmunkey/skin.arctic.fuse#508]
### Skin section

Other

### Feature description

In AH2 i liked how when you open the info page I could quickly press up and the description is larger and easier to read. Now in AF, I have finally found something similar but dfferent. Now I have to scroll down to the wiki icon then press right or left to pull this screen up. My suggestion, if at all possible, is to have the top icon to do the same when you press left to save on clicks. Also is there an option for the text I highlighted to be bigger?

### Why is this feature needed? Please justify and explain.

Quick and intuitive navigation and functionality for endusers.

### Screenshots and Additional Info

<img width="1241" alt="Screen Shot 2024-02-19 at 10 45 08 AM" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/13c4947c-1d52-4133-b5bc-e1c6d8436c6f">

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
It was because of the wrap from the various lists that you could press left (e.g. in music there's a songs view on that button). But I think it makes sense to have a consistent onleft that opens plot in info dialog.

BTW - if you map a button on your remote to ActivateWindow(1113) you can also access the plot dialog outside of the info dialog.

**Comment by Liquidrag** [comment]
Thank you sir!
