### ISSUE TITLE
:sparkles: Episode banner enhancement

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.fuse#523]
### Skin section

Library

### Feature description

With my limited skills, I have been having a play with moving the episode type from the plot to the info line. Just wondered if you thought this would be applicable to the skin.

### Why is this feature needed? Please justify and explain.

Just experimentation at this stage.

### Screenshots and Additional Info

![screenshot00001](https://github.com/jurialmunkey/skin.arctic.fuse/assets/67786207/29c57a69-9add-459b-b4cc-4e142b5ee1bc)
![screenshot00000](https://github.com/jurialmunkey/skin.arctic.fuse/assets/67786207/ee001d50-6f6a-457b-841c-afc97ddc95b6)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by xyzfre** [comment]
Looks GREAT in the info line

**Comment by jurialmunkey** [comment]
There's a couple of issues with this approach (and which are why I put it with plot originally instead).

- Bad visibility. If infoline extends too wide into the flixart area, it starts to get bad visibility on light artwork.
- Less consistent. Info positioning becomes jumpy because the premiere/finale info is only available for some items.
- Weaker visual hierarchy. Once title/info/plot/ratings start becoming more variable widths, it makes it harder to parse the info at a glance. That's because generally content is read in an F-shape or Z-shape pattern -- i.e. user reads header L-R as first F-stem; then eyes move down to read info L-R as second F-stem; then eyes move down to final stem of widget. Keeping title+info+plot+ratings all roughly the same width allows this section to be read as a single stem in the visual hierarchy, whereas if their widths differ then they start to be read as separate and the interface feels more disorganised.

**Comment by berkhornet** [comment]
Appreciate your comments. Many thanks.
