### ISSUE TITLE
:bug: Side menu highlight on home when no link categories

### ISSUE THREAD

**Issue by Omarscomin** [jurialmunkey/skin.arctic.fuse#547]
### Skin section

Widgets

### Current Behavior

1. I start on the "Home" tab.

2. Then, I switch to my "TV Shows" tab. (The "Home" tab remains semi-selected when I do this). 

3. Then, I switch back to the "Home" tab. However, my "TV Shows" tab is still highlighted, despite displaying the content within in my "Home" section.  

Hopefully this makes sense. I deeply apologize for my lack of technical terminologies. Please let me know if you have any questions or if there's any other info that you need! Thank you for all of your hard work!

Device: Nvidia Shield Pro
Kodi version: Omega RC1
OS: Android

### Expected Behavior

For the selected tab to remain highlighted

### Steps To Reproduce

1. Select one of the sections on your side menu

2. Select a different section on your side menu, and you'll notice that the previous section remains highlighted

### Screenshots and Additional Info

Here is a screen recording of the issue:

https://youtu.be/lzju7E5zUPk?si=ud5qcQdPcUAkLxhI

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Dml2023** [comment]
I have also noticed this... If you are on the Home hub and then scroll down the menu bar in the left, when you press right to go onto the actual Home hub screen (categories or widget) the coloured dot to indicate which hub is active remains on the icon for the hub icon that you pressed right from, even though you remain on the Home hub. If you are on other hubs (shows, movies, music) the coloured dot remains next to the hub icon.

**Comment by jurialmunkey** [comment]
The reason for this change is that it is now possible to link the visibility of individual categories on the home screen to specific side menu item by using the "Link visibility" option -- and so the indicator follows the current group to show which is active on home.

I didn't want to break backwards compatibility on anyone, so the default for any existing categories is to be set as "always visible". However, you'll notice that if you add a _new_ category that it will automatically be assigned to the current group instead of all.

**Comment by Dml2023** [comment]
Hi Jurial, just playing around with the changes for category visibility and I can see that it will enable us to scroll down the side menu and a different set of widgets can then be enabled to appear depending on the highlighted side menu item. I live that you can also set a side menu spotlight as well. Amazing work, I love it.

**Comment by Dml2023** [comment]
Just trying to add some categories for other side menu items and I noticed that when trying to add a category the window that opens has the title of Shortcuts and underneath has FIXME>Submenu. I have to first create the category on the Home side menu and then change the visibility to where I want it to appear and then I can edit on the side menu screen. I am gonna assume this new functionality is still being finalised.

**Comment by jurialmunkey** [comment]
@Dml2023 - That's actually the submenu and the FIXME text is because there's no associated category. Didn't think to test that scenario where there's no categories assigned already, should be able to do something about that.

**Comment by Dml2023** [comment]
I've just re created my setup using this new feature (adding on home sidemenu first and the moving visibility to the desired sidemenu) and the only issue I've really noticed is if the first category item has a Submenu list as a widget then they widget is not displayed until you move focus over to the category (eg Title category with Submenu list A-C etc). I wonder if you are able to have the widget load when you first focus on the sidemenu item without having to move over to the category?

Thanks again

**Comment by Omarscomin** [comment]
> The reason for this change is that it is now possible to link the visibility of individual categories on the home screen to specific side menu item by using the "Link visibility" option -- and so the indicator follows the current group to show which is active on home.
> 
> I didn't want to break backwards compatibility on anyone, so the default for any existing categories is to be set as "always visible". However, you'll notice that if you add a _new_ category that it will automatically be assigned to the current group instead of all.

@jurialmunkey 

Ok, thank you for the info! I will play around with this feature later and try to wrap my mind around it :)

**Comment by Omarscomin** [comment]
@jurialmunkey 

I changed my home page widget visibility from "always visible" to "home", and it is behaving even more strangely than before. I'm not sure if it's just me, or maybe there are more settings that I need to tweak. I will attach another screen recording later.

**Comment by xyzfre** [comment]
> @jurialmunkey 
> 
> I changed my home page widget visibility from "always visible" to "home", and it is behaving even more strangely than before. I'm not sure if it's just me, or maybe there are more settings that I need to tweak. I will attach another screen recording later. 

I can't figure this feature out 😕

**Comment by Omarscomin** [comment]
Hi @jurialmunkey!

I changed the visibility on my home page widgets from "always visible" to "home". It behaves normally as I _scroll_ through the other categories on my side menu, but things start to get a little wonky when I actually _click_ on different categories. 

I went from my home page, to my TV shows section, then back to my home page. When I attempted to navigate back to my home page from my TV shows section, I had to scroll around, in order for my home page widgets to appear again. 

Here is another screen recording: 
https://youtu.be/bwP72BhU5eo?si=nIx_lVCiV7wzX_L5

I really can't apologize enough for my inability to explain this efficiently. Thank you for your time and patience!

**Comment by jurialmunkey** [comment]
@ambulancePilot It applies to the complex layout only on home screen but it is not forced. There is also an option for categories to be "always visible" - ie globally linked to all side items

**Comment by jurialmunkey** [comment]
@Omarscomin that's working correctly. You set the visibility of the category to only be visible when the home icon has focus, so when you focus other icons the categories are no longer visible on home screen. If you want the categories in home screen to always be visible when any side icon is focused the you should set always visible.

Always visible only applies to home window, not other hubs.

**Comment by Omarscomin** [comment]
> @Omarscomin that's working correctly. You set the visibility of the category to only be visible when the home icon has focus, so when you focus other icons the categories are no longer visible on home screen. If you want the categories in home screen to always be visible when any side icon is focused the you should set always visible.
> 
> Always visible only applies to home window, not other hubs. 

That's not the part that I think is working incorrectly. It's the fact that the category that I click on isn't the one that stays highlighted. The TV shows category is highlighted while the content on my home page is being displayed.

**Comment by Omarscomin** [comment]
@jurialmunkey 

I probably need to take another screen recording, with GUI sounds enabled. That way, you'll be able to tell when I'm fully selecting something, versus just hovering over it. I'll take attach another screen recording as soon as I can.

**Comment by Omarscomin** [comment]
Here is an updated screen recording with GUI sounds enabled:

https://youtu.be/WCnmc4_M5ik?si=uX5Uzi3vQOFFKdYh

From 0:25-0:35, my "TV shows" section has an indicator next to it, implying that it is selected, despite the fact that I fully selected the "home" section, and my home page widgets are the ones that are displayed. I have to click the "home" icon a second time, in order for the indicator to move to said section.

**Comment by jurialmunkey** [comment]
@Omarscomin that's because you are mixing two different scenarios - a hub window and the home categories.

When you *click* the tvshows icon you are going to your tvshows hub *window* which is a different window from home. You must then either press back or use the side menu to return the home window.

In the home window you can also separately link categories to each side item for when they *focused* (not clicked) - which categories display for the home menu depend on which side menu item is focused. If the category is set to always visible then it will display regardless of which icon is focused.

I agree that the indicator is confusing in its current state but that's only because the changes aren't complete yet. It was a mistake initially to have it indicate which window was active but I had it that way initially because I envisaged the skin working a different way - but I continually get comments that approach confuses people, so now I'm trying to work towards a different approach where the indicator relates only to content inside the window rather than the window itself. It's confusing at the moment because there's still remnants of the old approach and i didn't just want to completely break things in people but this will improve in coming updates.

**Comment by Omarscomin** [comment]
> that's because you are mixing two different scenarios - a hub window and the home categories.\n\nWhen you click the tvshows icon you are going to your tvshows hub window which is a different window from home. You must then either press back or use the side menu to return the home window.

I had to think about this all night long, but I finally get it now!

**Comment by ambulancePilot** [comment]
I'm using the categories layout and basically have all of my widgets in the home hub. Then I added my own search menu item which onclick takes me to window 1105. Disabled search and menu in the settings.

I also have my home hub categories visible to all the menu items so none of my categories go away when I highlight over my search menu item.

The behavior I'm seeing is that the blue dot indicator persists on whichever item was last highlighted when I go right on my remote which brings me to my home hub categories.

So when I navigate down to the search menu item and then move right into my home hub, the BLUE dot rests on the search menu item even though what I'm seeing on the screen has nothing to do with search (since I didn't click on the search menu item).

Is that how it's going to be? It's honestly not a big deal, but an easy fix for this might be to allow disabling of the blue dot for use cases like mine where hovering over any of the menu items doesn't change what you see on the screen.

As always thanks for your work! The skin gets better and better as time goes on.

**Comment by jurialmunkey** [comment]
@ambulancePilot yeah it is how it will be moving forward but I think an option to disable the dot entirely (at least for categories layout) like you're suggesting would probably be a good idea. 

Very easy for me to manage without over complicating things and gives a lot of flexibility in terms of not forcing any specific approach to widget layouts.

**Comment by ambulancePilot** [comment]
If it's possible, then excellent! Your work is so greatly appreciated.

**Comment by Omarscomin** [comment]
I'm really loving the new layout @jurialmunkey. Thank you so very much for all of your hard work

**Comment by jurialmunkey** [comment]
I think this one can be considered resolved now.
