### ISSUE TITLE
:bug: Hiding widget initialisation not functioning

### ISSUE THREAD

**Issue by Dml2023** [jurialmunkey/skin.arctic.fuse#549]
### Skin section

Widgets

### Current Behavior

Since updating the skin to 0.5, I have noticed that the widget initialisation behind splash setting is not behaving the same. Now, when the home hub first loads, the widget initialisation splash screen only appears for a split second and then the home hub displays but it is still loading my widgets (in progress etc)

### Expected Behavior

It used to remain on the splash screen for a few more seconds before displaying the home hub with the widgets loaded and displaying on screen.

### Steps To Reproduce

Enable the setting in Skin Settings | Expert | Hide widget initialisation behind splash then restart Kodi or reload the skin. In the past reloading the skin displayed the widget initialisation splash for a shorter time when compared to a full Kodi restart.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I'm pretty sure that should fix it.

It was because before I was cancelling the timeout if the menu gained focus but now it has focus by default so it cancels the alarm immediately. This should hopefully fix that while still letting you press back to cancel out of it if it gets stuck.

Let me know if after next update it still doesn't work but pretty sure this is the reason for it.

**Comment by Dml2023** [comment]
Thanks for this fix. The Initialising Widgets splash screen is now working properly.
