### ISSUE TITLE
:sparkles: Next Group: None visibility 

### ISSUE THREAD

**Issue by Dml2023** [jurialmunkey/skin.arctic.fuse#552]
### Skin section

Widgets

### Feature description

Would it be possible to have to have the ability to toggle on or off the 'Next Group: None' text that appears underneath the last row of widgets on the screen.

### Why is this feature needed? Please justify and explain.

This text now appears instead of the footer information that was appearing when on the last widget row.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by C-O-D** [comment]
The text here is somehow semi transparent overlapping with the widget titles in combined mode and always visible, no matter what element is focused...

**Comment by xyzfre** [comment]
If it's possible, it would be great to have an option to enable or disable the display on the Home Screen last roll of widgets The way it was before, provider logos or for example, one of my last widget rolls are my in progress TV shows which before it will show, In-progress Played 2 of 3 episodes or Unwatched Played 0 of 3 episodes ,, thank you for your amazing work.

**Comment by ambulancePilot** [comment]
I'm not sure I understand what this text at the bottom is supposed to indicate. What are "groups" and how can I use them?

**Comment by Bindou01** [comment]
On Horizon 2, there was a Widget called "Poster (Full)" which allowed you to have the poster line in full screen. I used it to display my Universes. It would actually be a good idea to find this Widget.

**Comment by jurialmunkey** [comment]
> I'm not sure I understand what this text at the bottom is supposed to indicate. What are "groups" and how can I use them?

In classic mode you can scroll up/down at the end of the widgets group to automatically go to the next icon's group. On the very last group you can also set a navigation option to explore further. 

The group text shows where you are scrolling to and keeps a consistent visual experience

With v5 it is now also possible to link category visibility to individual side menu items, so the intent is also to bring this continuous scroll feature to categories mode too.

Having codecs etc on just one item at the end never made any sense, especially since widgets can only show this information when focused and it presents an issue of what to display when not focus (the master user text everyone complains about).

**Comment by xyzfre** [comment]
I actually like the master user logo, I see you change it to white my opinion, I think it looks so much better with the Kodi logo blue the way it was before

**Comment by Bindou01** [comment]
Blue or gray I don't care, but if it has to be gray, it would be a little darker ideally, because it contrasts quite strongly in this black area. ^^
