### ISSUE TITLE
:sparkles: Option to Always show plot on OSD

### ISSUE THREAD

**Issue by SJ1O** [jurialmunkey/skin.arctic.fuse#57]
### Skin section

Fullscreen Video OSD

### Feature description

A option to Always show the plot on OSD would be nice. Make it simpler for the missis.

### Why is this feature needed? Please justify and explain.

Just to make it more simple for people with less knowledge on how Kodi works 

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
This is partially addressed by the option
`Skin Settings > Behaviour > Seekbar behaviour on delayed pause (Info)`

That will auto show the full details after 3 seconds of inactivity when the video is paused (if the video controls are open, the pause button must be focused -- it won't do it on other buttons since those get hidden when it expands up).

**Comment by C-O-D** [comment]
I'd appreciate this feature too...
