### ISSUE TITLE
:sparkles: always show side menu

### ISSUE THREAD

**Issue by SJ1O** [jurialmunkey/skin.arctic.fuse#571]
### Skin section

Widgets

### Feature description

On the previous version of fuse the side menu was always shown. Now when entering a hub I have close and menu as the two options rather then the actual side menu (home and the hubs) would it be possible to make the side menu always visible again.

No worries if not I'll just have to get used to it.

Hope all is well.

Cheers
Sam

### Why is this feature needed? Please justify and explain.

I much prefered it how it was before.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by Liquidrag** [comment]
+1 for this! Currently, I see little differences in "compound" and "categories" layout styles. I preferred the  old "categories" layout where the side menus were always present.

**Comment by L0bsang** [comment]
> I too preferred it when the side menu was always present. It makes sense to be able to access search from any screen rather than have to back out to the home screen.
> 
> However I think he's done this for some navigational standardization, and from that view it makes sense.

I set my navigation so that Up will access search directly, and that works nicely to have search always accessible even without the menu.
I also liked having the submenu always visible, but I understand having it be simplified when you are inside the library. Makes it clearer where you are at the moment.

**Comment by xyzfre** [comment]
> > I too preferred it when the side menu was always present. It makes sense to be able to access search from any screen rather than have to back out to the home screen.
> 
> > 
> 
> > However I think he's done this for some navigational standardization, and from that view it makes sense.
> 
> 
> 
> I set my navigation so that Up will access search directly, and that works nicely to have search always accessible even without the menu.
> 
> I also liked having the submenu always visible, but I understand having it be simplified when you are inside the library. Makes it clearer where you are at the moment.

Thank you for this reminder 💯💯change my settings now, when I push up, I can access the search menu from anywhere.

**Comment by xyzfre** [comment]
What I have done is in skin settings/Menus/Minimize menu set to Library and in widgets settings, Home,link visibility to always ,, and my side icons are always visible. Of course when you click on a separate hub, you get the menu icon but when you back out you always have the home page visible,which I get it now I'm starting to get used to it and see why he did it, makes the hubs more interesting on my end. Going to change my home hub around a little bit to make it more interesting being that that's my main display

**Comment by jurialmunkey** [comment]
> However I think he's done this for some navigational standardization, and from that view it makes sense.

@ambulancePilot 

Yep, this is the main reason.

The number one issue new users raise is about finding navigating the skin confusing, especially when back tracking.

The main pain points I've observed are:
1. Users confused whether they are navigating between **separate** windows or within the **same** window.
2. Directional navigation (particular ondown) doing something entirely different in different windows (made worse by point 1).

Having a close button when you leave the home window makes the distinction clear.

It also frees up the side menu in the library to add alternative buttons. For instance, a view option button so that ondown behaviour can stay consistent.

------

General comment:

Originally the footer was used to differentiate between library (footer) and hubs (no footer). 

It was a massive mistake on my part to cave to pressure and compromise that distinction by adding a footer to the end of the widget groups. Made the skin inconsistent and the distinction between windows worse.

Now that cat's out of the bag, there's no returning it, so only option is to try to fix my original mistake in terms of making the footer appear more consistently if enabled and finding an alternative better method of differentiating windows.


> +1 for this! Currently, I see little differences in "compound" and "categories" layout styles. I preferred the old "categories" layout where the side menus were always present.

@Liquidrag 

There's actually quite a big difference if you make use of the new "Link visibility" option when customising home categories. Home categories can now be linked to specific side icons (i.e. only display when a specific icon has focus).

Essentially allows for what hubs were previously used for but self contained within the home window without needing to click into a new window. 

There's still a place for hubs in terms of cordoning off the loading of a bigger set of widgets in a separate window; but idea is now to build a basic configuration for each side icon all within the home menu and only use the hubs as more of a configurable landing page for separate parts of the library.


Still a place for hub windows in hiding loading of a bigger set of widgets behind a window but idea now is to split the home screen up by side icon with a simplified set of options

**Comment by jurialmunkey** [comment]
------

General comment:

Originally the footer was used to differentiate between library (footer) and hubs (no footer). 

It was a massive mistake on my part to cave to pressure and compromise that distinction by adding a footer to the end of the widget groups. Made the skin inconsistent and the distinction between windows worse.

Now that cat's out of the bag, there's no returning it, so only option is to try to fix my original mistake in terms of making the footer appear more consistently if enabled and finding an alternative better method of differentiating windows.

**Comment by jurialmunkey** [comment]
> +1 for this! Currently, I see little differences in "compound" and "categories" layout styles. I preferred the old "categories" layout where the side menus were always present.

@Liquidrag 

There's actually quite a big difference if you make use of the new "Link visibility" option when customising home categories. Home categories can now be linked to specific side icons (i.e. only display when a specific icon has focus).

Essentially allows for what hubs were previously used for but self contained within the home window without needing to click into a new window. 

There's still a place for hubs in terms of cordoning off the loading of a bigger set of widgets in a separate window; but idea is now to build a basic configuration for each side icon all within the home menu and only use the hubs as more of a configurable landing page for separate parts of the library.


Still a place for hub windows in hiding loading of a bigger set of widgets behind a window but idea now is to split the home screen up by side icon with a simplified set of options

**Comment by jurialmunkey** [comment]
> I too preferred it when the side menu was always present. It makes sense to be able to access search from any screen rather than have to back out to the home screen.

@ambulancePilot @L0bsang 

I can definitely look for alternatives to this.

A couple of ideas I had:

1. Put a link in the new slide out view options/filter menu to switch to the search window
2. An option to enable the top/bottom search/options icons even when menu is collapsed

Both have benefits and disadvantages. The first feels like the more "correct" place for it to go (search goes with filter) but it is a bit hidden and you have to know it is there.

The second is better in terms of discoverability but not sure if it looks as clean and neat as the first option.

**Comment by jurialmunkey** [comment]
> The back key does not take us back to the main page, but only to the sidebar.

It does if you set to do so:
Skin Settings > Navigation > OnBack > Menu

**Comment by Bindou01** [comment]
Thans Jurial, I see what you mean, but it doesn't get the logic I tried to explain. Maybe try browsing Netflix to figure out what I mean.

**Comment by jurialmunkey** [comment]
> Thanks Jurial, I see what you mean. But this is not enough to realize the logic I tried to explain. Maybe try browsing Netflix to figure out what I mean.

That's how the skin was setup before these changes and you literally complained about it being confusing and couldn't understand it.

**Comment by Bindou01** [comment]
> > Merci Jurial, je vois ce que tu veux dire. Mais cela ne suffit pas pour comprendre la logique que j’ai essayé d’expliquer. Essayez peut-être de parcourir Netflix pour comprendre ce que je veux dire.
> 
> C'est ainsi que le skin était configuré avant ces changements et vous vous plaigniez littéralement du fait qu'il était déroutant et ne parveniez pas à le comprendre.
> 
> > Je trouve qu'avec cette logique, il est plus simple de penser l'interface de manière à créer des Hubs de type "Parent/Main", "Kids", "News", avec les mêmes catégories dans chaque Hub (Film, Animation, Documentaire, Série, Musique, etc.).
> 
> Vous devez utiliser des pseudo-profils pour cela, pas des hubs. Ou bien, utilisez simplement l'écran d'accueil et liez les catégories aux icônes du menu latéral et n'utilisez pas du tout de hubs.

Maybe I'm wrong, but what I'm trying to explain isn't quite the above logic either. It's a mix of both.

With the old logic, I couldn't put aside the "home page" without having to sacrifice the "normal" use of the return key (in "return" mode). Additionally, the readability on the Hub in use and the sidebar was not entirely clear. Now it is certainly clearer, however, there are still some limitations.

The ergonomic logic that I propose would be to ensure that there is no longer a “Home page”. But only Hubs, like on Netflix. Consequently, the return key will keep the same ergonomics as when it is set in "return" mode (return to the start of the widget -> return to the top of the list -> return to the sidebar), but without it allowing you to change Hub. In this way, changing Hub would be a "conscious" action.

It remains to be seen how to organize the visibility of the sidebar, without falling back into confusing visibility. I don't know if it's possible, but the sidebar should look like your new version, because it's dynamic and therefore it's perfectly clear and minimalist. For example, when you are not browsing it, you would only see the icon of the hub that is in progress, in the top position. In this way, there would be no overlap with the Widegts. The other icons would only appear when navigating in the bar. In this way, we would have the same visibility (clarity and minimalism) as today, but with a Hub icon instead of the “closed” button.

Advantage :
This would make Fuse even more aesthetic and more ergonomic. Example of a concrete case: A child who is in the "Kids" Hub could no longer close the hub and find themselves on the main page without realizing it, as is now possible by pressing the cross or clicking back too many times. He should consciously click on another icon, to move from one hub to another.

I don't know if I'm being clear, but for me the source of confusion in the old configuration mainly came from the notion of "Home page", which was acting as a "priority hub".

**Comment by xyzfre** [comment]
I really have gotten use to the new layout and the changes you made. I think it's perfect the way it is now some people just have to adapt to these new changes and it does make the skin a lot better.

**Comment by Bindou01** [comment]
> I really have gotten use to the new layout and the changes you made. I think it's perfect the way it is now some people just have to adapt to these new changes and it does make the skin a lot better.

It seems to me that I was the first to say that it was better this way on the forum. I think I can say that I have already adapted to this interface, because it is very ergonomic, which means that we now better understand the overall functioning of Fuse. It is precisely this new experience that has matured the reflection that I shared above.

Good day Xyzfre

**Comment by Liquidrag** [comment]
> > +1 for this! Currently, I see little differences in "compound" and "categories" layout styles. I preferred the old "categories" layout where the side menus were always present.
> 
> @Liquidrag
> 
> There's actually quite a big difference if you make use of the new "Link visibility" option when customising home categories. Home categories can now be linked to specific side icons (i.e. only display when a specific icon has focus).
> 
> Essentially allows for what hubs were previously used for but self contained within the home window without needing to click into a new window.
> 
> There's still a place for hubs in terms of cordoning off the loading of a bigger set of widgets in a separate window; but idea is now to build a basic configuration for each side icon all within the home menu and only use the hubs as more of a configurable landing page for separate parts of the library.
> 
> Still a place for hub windows in hiding loading of a bigger set of widgets behind a window but idea now is to split the home screen up by side icon with a simplified set of options
@jurialmunkey I'll start from scratch to see if I can get my mind wrapped around this new way of navigating. Thanks for the continued support!

**Comment by L0bsang** [comment]
I agree with @xyzfre and @matthius7. You had good reasons for making the changes to sidemenu and although it takes some time to wrap the head around, I can get used to the layout and navigation, especially with plausible navigation options to quickly get to search, back to home and to other menus. Maybe in the future stuff like text labels on topmenu and such would be nice-to-have, but that can come in time.

In terms of your alternatives proposed I am currently using up on navigation always goes to 'global' search, which makes sense and is consistent from hub to home to library. 
Option 2 might be nice, where the search icon is always visible even with a collapsed menu, letting the user know that up will search, and then the View menu item can be used for filtering and options. 
But honestly it is fine with my current set of options. Back goes to previous, end of content loops so you can navigate to the menu, down is bump, up is search. Hide menu set to Library.

**Slightly offtopic:**
Wanted to add something based on this comment

> Originally the footer was used to differentiate between library (footer) and hubs (no footer).
> 
> It was a massive mistake on my part to cave to pressure and compromise that distinction by adding a footer to the end of the widget groups. Made the skin inconsistent and the distinction between windows worse.

I generally like having useful footer information on every widget as well.

In AH2 I use(d) fullscreen widgetview with everything enabled including ratings, clearlogo, infoline, codecs/providers, studio etc so there is no difference between home and library and the maximum amount of information is present at a glance; while the little chevrons/pips show if there are more widgets above and below. I love that setup and still return to it often. If only premiere/finale labels could be added to AH2.... wink wink nudge nudge`

However I also like being able to have the next widget show, have the menus seamlessly connected via vertical scrolling, and have the mental flexibility to adapt (and teach my family) how to use the different navigation present in Fuse. 

All this is to say, you have excellent and consistent design principles, of course there are some annoyances (I want as many ratings as in Horizon 2, and also want to see the returning//ended status, and also would like more lines of plot shown haha). But we can understand the reasons we can't have everything and also get used to stuff, for example having footers only show within library/addon menus and not on the home/hub at all.

**Comment by SJ1O** [comment]
Hey Jurial,

I had a little skim of all the messages in this post and think I seen someone mention a option to disable the menu button so it's just a close button?

I had a little play with it and think the reason I got abit confused is when I went into the hub I kept clicking menu and it opening up all my home and hubs on the right side where I would normally access the settings. Rather then it just taking me back to my home screen.

As others have said it just takes abit of getting used to and that's no problem for me however explaining changes to the wife and family is tiresome as I can imagine it is for you explaining these changes to us 😅 and imagine we would all love to avoid having to constantly explain things. This is why I believe a option to disable the menu button might be good. Saves having the same options in multiple places.

Kind regards
Sam

**Comment by Bindou01** [comment]
Hi SJ10,
It is necessary not to lose sight of the fact that this is an Alpha version. This Skin is under construction and is subject to change again and again. We are the Alpha testers. If Jurial had to write a tutorial for each change, it would waste time. In my opinion, when the status of Fuse is at least in Beta, we can perhaps consider that the ergonomics will be fixed. And then it will seem necessary to me to communicate on its functioning. I also think that passionate users will want to do it for him, on video for example.

In the meantime, for my part, I leave Horizon 2 daily for my family. I'm tinkering on Fuse with another device until everything is completely clear.

**Comment by jurialmunkey** [comment]
> 
> I had a little play with it and think the reason I got abit confused is when I went into the hub I kept clicking menu and it opening up all my home and hubs on the right side where I would normally access the settings. Rather then it just taking me back to my home screen.
> 


@SJ1O - Thanks, this is useful feedback and confirms what I've felt for a while that the right side menu is the wrong place for it. 

I actually tried to remove it a while back but some people didn't like that - though I think that was more a case of they didn't like losing access to the shortcuts rather than the position/style itself.

Thinking out loud here, what might be useful is if the menu button instead triggers the left side menu to maximise with the expanded label option. So it's sort of like a pull out from the left with quick shortcuts to jump to other areas.

That would also draw a clearer distinction between right side dialogs being more about  settings, config, context type things whilst navigation between media content happens in the left side. And also means it will still work for same purpose in compound mode

**Comment by Bindou01** [comment]
> > I had a little play with it and think the reason I got abit confused is when I went into the hub I kept clicking menu and it opening up all my home and hubs on the right side where I would normally access the settings. Rather then it just taking me back to my home screen.
> 
> @SJ1O - Thanks, this is useful feedback and confirms what I've felt for a while that the right side menu is the wrong place for it.
> 
> I actually tried to remove it a while back but some people didn't like that - though I think that was more a case of they didn't like losing access to the shortcuts rather than the position/style itself.
> 
> Thinking out loud here, what might be useful is if the menu button instead triggers the left side menu to maximise with the expanded label option. So it's sort of like a pull out from the left with quick shortcuts to jump to other areas.
> 
> That would also draw a clearer distinction between right side dialogs being more about settings, config, context type things whilst navigation between media content happens in the left side. And also means it will still work for same purpose in compound mode

Doesn’t that tie in a bit with what I was saying previously?  (This is a real question, as I don't understand English perfectly)

**Comment by Bindou01** [comment]
@jurialmunkey 
This is great Jurial! I'm very excited because with the latest version of Fuse, you can almost configure the ergonomic mode that I talked about above. Thanks to the retractable sidebar that can be displayed from any Hub. Finally, there is only one “important” thing left to do. Be able to deactivate the Home page. I don't know if it's possible yet?

And then, there will only be one detail left to add, and we'll be there! Display the current hub icon somewhere in the interface. At the top, right next to the Hub name. Either on the left side, above or below the menu button. I don't know which is better.

Thank you for everything you do!

**Comment by SJ1O** [comment]
> > I had a little play with it and think the reason I got abit confused is when I went into the hub I kept clicking menu and it opening up all my home and hubs on the right side where I would normally access the settings. Rather then it just taking me back to my home screen.
> 
> @SJ1O - Thanks, this is useful feedback and confirms what I've felt for a while that the right side menu is the wrong place for it.
> 
> I actually tried to remove it a while back but some people didn't like that - though I think that was more a case of they didn't like losing access to the shortcuts rather than the position/style itself.
> 
> Thinking out loud here, what might be useful is if the menu button instead triggers the left side menu to maximise with the expanded label option. So it's sort of like a pull out from the left with quick shortcuts to jump to other areas.
> 
> That would also draw a clearer distinction between right side dialogs being more about settings, config, context type things whilst navigation between media content happens in the left side. And also means it will still work for same purpose in compound mode

Hey Jurial, just did the update and I must say that it's much better you did a great job. I personally think your right about having settings / config options on the right and keeping the media menu on the left it's much more consistent and simpler to navigate. Hopefully everyone is happy with this change. It must be hard to keep everyone happy. Well thanks for your implementations as always your work is much appreciated. I'll grab you another coffee on payday.

Kind regards
Sam

**Comment by Liquidrag** [comment]
@jurialmunkey Now that I got the "link visibility" figured out, I can say I love what your vision is! Thank you for your patience and hard work.

**Comment by jurialmunkey** [comment]
Next version re-adds options to show full menu in library and/or hubs.

It's an incremental setting for when menu is minimised 
`Settings > Library > Hubs > Home > (Topbar)`
