### ISSUE TITLE
Search function amendment request

### ISSUE THREAD

**Issue by JFG1000** [jurialmunkey/skin.arctic.fuse#574]
### Skin section

Widgets

### Feature description

Would it be atall possible to make an amendment to how the search function works, currently when we click new search it brings up the box on the right and side of the screen, but after we have typed something in when we click back on the remote to return to the results, it starts deleting the characters we just typed in instead, which results in the search being removed, the only way around this is to come out of the keyboard box then the press back for it to then take us to the results. 

### Why is this feature needed? Please justify and explain.

Could create abit more simplicity 

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I wish it were possible but unfortunately it is standard Kodi behaviour for the edit control. It needs a Kodi core change.

Edit control steals the back press and converts it backspace so it just ignores whatever onback behaviour the skin defined.

**Comment by vella9** [comment]
would it be possible to change the focus so that when the search button is pressed, the focus would be on the text box so that we can start tying immediately without having to press a couple of up arrows to get to the text box? just a minor thing that's all.

focus can also be changed so that once you click the search button on the side menu, it focuses on the search button inside the search page. Again just a minor thing I noticed that might be looked into.

Thank you for your amazing work @jurialmunkey
