### ISSUE TITLE
[Feature] Option to disable fanart clearlogos

### ISSUE THREAD

**Issue by 666jones** [jurialmunkey/skin.arctic.fuse#58]
### Skin section

Home Widgets

### Feature description

A Option to disable fanart clearlogos. Might increase profomance on some low end devices. Also afew of the clearlogos are dark text and not very easy to read in some cases so might be a nice feature to have.

### Why is this feature needed? Please justify and explain.

To possibly increase profomance on low end devices.
Possibly make some movie / show titles more visible 

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
What do you mean by "fanart clearlogos" ?

**Comment by 666jones** [comment]
Sorry I was referring to the logo things that I have highlighted in the below image

![20230802_024236](https://github.com/jurialmunkey/skin.arctic.fuse/assets/121204283/a4584434-1aaf-4a00-be98-98e122e624d0)

**Comment by 666jones** [comment]
> What do you mean by "fanart clearlogos" ?

Sorry I was referring to the logo things that I have highlighted in the below image

![20230802_024236](https://github.com/jurialmunkey/skin.arctic.fuse/assets/121204283/545b1758-2a33-4b70-a2bc-9136f717518f)

**Comment by deon10** [comment]
Hello

This has been marked as completed but the issue is still not resolved from what I see

I don’t see any option to disable clearlogo like OP suggested

I apologize if it was implemented but I didn’t see it. Would appreciate any help

thanks

(my reason for wanting to disable clearlogo is first, that sometimes it gets hidden by the background if they’re the same color as shown in the picture attached, also, sometimes clearlogos have inconsistent sizes, so it look  has weird. Also, having just normal text takes less resources and is more uniform)

thank you again
![IMG_1332](https://github.com/jurialmunkey/skin.arctic.fuse/assets/71561562/8f980fda-19ba-4e03-9962-8aee20d42dca)

**Comment by deon10** [comment]
> Skin Settings→Appearance change foreground logo to text.

God bless you my friend
