### ISSUE TITLE
add fast scrollbar back in

### ISSUE THREAD

**Issue by Aemstel2** [jurialmunkey/skin.arctic.fuse#583]
### Skin section

Library

### Feature description

In the library when pressing down, the scrollbar was removed. I would like this to return, because of an issue with remote control apps.

### Why is this feature needed? Please justify and explain.

I think it is actually better now, without the fast scrollbar. Looks nicer and is more user-friendly. However, scrolling faster by holding left or right does not work with the Yatse remote control app (and perhaps other apps as well?). The scrolling does not gain in speed when holding a direction. I know this is not a skin issue, but I doubt this will ever work with Yatse, because it never has. So the scrollbar worked well in this case. I assume the Yatse app is pretty popular, so therefore I thought I'd bring this to your attention. Please ignore if you feel it's not necessary. Thanks.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by adamosborne83** [comment]
> Oh wow, that's pretty well hidden :) Not a big fan of that location, but yeah it works. Thanks.

But imagine having a list of movies that was 4000 long, and trying to press down to get to that option...... 2 clicks Right is better haha....

**Comment by Aemstel2** [comment]
Haha ok, you got me there :))

Op wo 13 mrt. 2024 17:14 schreef adamosborne83 ***@***.***>:

**Comment by L0bsang** [comment]
Haha it took me a while to spot the scrollbar as well! Especially since I was in my library which has many items and so the scrollbar was tiny.

**Comment by jurialmunkey** [comment]
Maybe it would be better if the scroll had focus by default in the menu instead? 

I was playing around with that idea anyway.

Also I will be replacing it with an alphabet jump depending on sort method and page count, so that should help a lot with visibility and usage in the bigger lists.

**Comment by L0bsang** [comment]
After using it some more, I think it would be best if in the library a type of quick navigation (could be scroll or alphabet jump) was only one press away from content. If I load into a long list like titles in library, my first action is usually to want to jump around to a specific point.

Even if the scroll had default focus, that would still be a up, open menu, scroll, exit menu. With no indication that the quick scrolling is within a menu.
Instead of just down, scroll, up, which is easy and intuitive.

Maybe a down to scrollbar option can be the happy medium while you do the full replacement?

**Comment by L0bsang** [comment]
> But imagine having a list of movies that was 4000 long, and trying to press down to get to that option...... 2 clicks Right is better haha....

@adamosborne83 - But the only views where you would prefer to press right instead of down are list media and list landscape; which only show 4 items at a time, not exactly the ideal views for a long list. The rest of the views are horizontal. Or am I missing something?

**Comment by jurialmunkey** [comment]
These are all definitely valid points and one I wrestled with.

My main issue with down to scrollbar is that it makes navigation inconsistent. It should be possible to trust that navigation does the same thing in all places - eg why doesn't pressing down from a widget also open scrollbar despite the view looking identical when footer is enabled?

I could make the scrollbar always visible but I doubt that is desirable as it will disable the footer.

Open to ideas, just not sure of the solution.

I don't think I've ever seen any other TV apps have scrollbars so it feels like a bit of an outdated and clunky concept compared to searching or filtering which is what I'm trying to preference in making more accessible.

**Comment by adamosborne83** [comment]
> These are all definitely valid points and one I wrestled with.
> 
> My main issue with down to scrollbar is that it makes navigation inconsistent. It should be possible to trust that navigation does the same thing in all places - eg why doesn't pressing down from a widget also open scrollbar despite the view looking identical when footer is enabled?
> 
> I could make the scrollbar always visible but I doubt that is desirable as it will disable the footer.
> 
> Open to ideas, just not sure of the solution.
> 
> I don't think I've ever seen any other TV apps have scrollbars so it feels like a bit of an outdated and clunky concept compared to searching or filtering which is what I'm trying to preference in making more accessible. 

I do agree, and I guess I am unique in the fact that I use List View, but I find it easier whilst scrolling.
I do agree that having it always visible would be a step backwards cosmetically.

As always it's a hard one to make everyone happy.

Looking forward to seeing other people's suggestions, as this works well for me me me personally, but always willing to give other ideas a go.

**Comment by jurialmunkey** [comment]
This is what I've come up with so far. Seems to work well with different layouts.

Clicking the "View" buttons opens the panel on the alphabet, which can then be scrolled left/right to scroll through the letters. Moving down to the "Page" section allows scrolling left/right instead via page (i.e. moves the scrollbar). Can either click or press back to return.

From here, there's also quick access to the search and filter features.

Yes, it's two clicks instead of one to get there but it gives access to a much wider range of features and keeps navigation intact.

![screenshot00469](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/ef14827e-8d48-47bb-8074-f8026e16ccf5)
![screenshot00466](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/f62efdfc-af53-4fae-8453-a1b2fa8e6e18)
![screenshot00467](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/98e5bad9-c4b0-4f9e-8976-13e87aacf1ed)

**Comment by adamosborne83** [comment]
> This is what I've come up with so far. Seems to work well with different layouts.
> 
> Clicking the "View" buttons opens the panel on the alphabet, which can then be scrolled left/right to scroll through the letters. Moving down to the "Page" section allows scrolling left/right instead via page (i.e. moves the scrollbar). Can either click or press back to return.
> 
> From here, there's also quick access to the search and filter features.
> 
> Yes, it's two clicks instead of one to get there but it gives access to a much wider range of features and keeps navigation intact.
> 
> ![screenshot00469](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/ef14827e-8d48-47bb-8074-f8026e16ccf5)
> ![screenshot00466](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/f62efdfc-af53-4fae-8453-a1b2fa8e6e18)
> ![screenshot00467](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/98e5bad9-c4b0-4f9e-8976-13e87aacf1ed)
> 
> 

I'm sure we will moan 😜

**Comment by Aemstel2** [comment]
> This is what I've come up with so far. Seems to work well with different layouts.
> 
> Clicking the "View" buttons opens the panel on the alphabet, which can then be scrolled left/right to scroll through the letters. Moving down to the "Page" section allows scrolling left/right instead via page (i.e. moves the scrollbar). Can either click or press back to return.
> 
> From here, there's also quick access to the search and filter features.
> 
> Yes, it's two clicks instead of one to get there but it gives access to a much wider range of features and keeps navigation intact.
> 

That looks very good. I think that works well enough for many situations and solves the issue of not wanting a scrollbar at all. I can see why you don't want a scrollbar, because it's not really a thing that's used anymore and doesn't fit the rest of the skin.

But having hundreds or thousands of items on one view is also a bit strange to begin with. In that case a scrollbar maybe still does make sense? Maybe we should just get used to not showing so many items in one view, but it's nice to have the option for people with really large libraries. In AH2 I also really liked the poster wall when pressing down from poster row. It's kind of fun to see it all like that, but I guess it's not really useful.

I'm just throwing this out there. I think your solution is probably best. Maybe a down-to-posterwall/scrollbar as an option for views with a huge amount of items? But I can see that becoming too complicated.

**Comment by adamosborne83** [comment]
> This is what I've come up with so far. Seems to work well with different layouts.
> 
> Clicking the "View" buttons opens the panel on the alphabet, which can then be scrolled left/right to scroll through the letters. Moving down to the "Page" section allows scrolling left/right instead via page (i.e. moves the scrollbar). Can either click or press back to return.
> 
> From here, there's also quick access to the search and filter features.
> 
> Yes, it's two clicks instead of one to get there but it gives access to a much wider range of features and keeps navigation intact.
> 
> ![screenshot00469](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/ef14827e-8d48-47bb-8074-f8026e16ccf5)
> ![screenshot00466](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/f62efdfc-af53-4fae-8453-a1b2fa8e6e18)
> ![screenshot00467](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/98e5bad9-c4b0-4f9e-8976-13e87aacf1ed)
> 
> 

I cannot even get to view.......

https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/61ebc972-42de-49cf-9eec-544d42fed8f9

Left and right on amazon remote have no impact.

**Comment by Aemstel2** [comment]
Hmm it works well here, but I'm using poster-row view.

**Comment by adamosborne83** [comment]
> Hmm it works well here, but I'm using poster-row view.

Yes, it works on other views, but not list as video shows 😀

**Comment by jurialmunkey** [comment]
> > Hmm it works well here, but I'm using poster-row view.
> 
> Yes, it works on other views, but not list as video shows 😀

Do you have wrap set for onleft/right ? Because if not you should be able to press left to acccess menu and click view button which works fine for me.

Wrap will stop access to side menu with directional presses and assumes you have some other way to access the side menu.

**Comment by adamosborne83** [comment]
> > > Hmm it works well here, but I'm using poster-row view.
> > 
> > Yes, it works on other views, but not list as video shows 😀
> 
> Do you have wrap set for onleft/right ? Because if not you should be able to press left to acccess menu and click view button which works fine for me.
> 
> Wrap will stop access to side menu with directional presses and assumes you have some other way to access the side menu.

Yes I use wrap. Use it on homescreen widgets.
If I need to turn it off to make a compromise then so be it 😀

**Comment by jurialmunkey** [comment]
No I think it's reasonable to have the vertical list still go to side menu even if wrap enabled. It still stays in the spirit of the setting which is to wrap around at the ends and honestly it feels a bit weird that the list doesn't go to the side menu.

**Comment by L0bsang** [comment]
This works well enough. 
Doesn't seem the most elegant (partly because "View" is a bit of a misnomer for a menu that also has filters and navigation) but good enough for now. 

However I do agree with Aemstel2 where sometimes a scrollbar makes sense (especially for usage with a remote, where arrows are mostly used for navigation). 

I personally don't have an issue with widget and library looking different vis-a-vis scrollbars and footers; as my understanding on the home menu is that I am looking at a smaller number of content lists for quick loading, so down/up should take me to another widget row and I will have either a footer with info or be able to see the next widget. 

But once I expand that list or dig deeper to my content lists, I get a focused list of content with nothing else above or below; and then a scrollbar can be useful and makes sense to have even if there is a footer. However I don't feel too strongly about that, I am happy to be without or have it in a menu if it works better for the rest of the skin design.

**Comment by adamosborne83** [comment]
> No I think it's reasonable to have the vertical list still go to side menu even if wrap enabled. It still stays in the spirit of the setting which is to wrap around at the ends and honestly it feels a bit weird that the list doesn't go to the side menu.

Cheers Jurial.

**Comment by jurialmunkey** [comment]
> partly because "View" is a bit of a misnomer for a menu that also has filters and navigation

I'm happy to hear alternative name suggestions as I felt the same but just really wasn't sure what to call it since "filter" or "options" or "scroll" all have the same issue.

I guess "options" is probably most technically correct but I wasn't sure if it was *too* generic.

> However I do agree with Aemstel2 where sometimes a scrollbar makes sense (especially for usage with a remote, where arrows are mostly used for navigation).

I do have a solution for this coming up in next update where I have added an extra OnDown navigation choice called "Options" that either pulls up the view options or the settings options menu depending on where you are (settings in hubs, view in library).

**Comment by Aemstel2** [comment]
How about removing "Search" (the option with the hourglass icon) I think that is a bit confusing here. And then splitting it into 2 buttons?

"search" : shows everything above "filter" (minus "Search" which is removed)
"view": shows everything else

This would also allow to make the dialog smaller which now overlaps the poster-row, but could then be shown above it. I know this means an extra button on the left, but I don't think that's so bad.

**Comment by L0bsang** [comment]
Aemstel's suggestion is not bad with a neat implementation of the split.

But if the menu remains combined, I kind of like having an "Options" menu. 
Then stuff like a player controls (a common usecase is if I need to pick a different source/stream, or someone accidentally hits back during playback, we can go directly to the player from any view without having to go all the way back to home) and link to the addon settings (which is also useful for tweaking) can live in this menu.

But I believe your new OnDown navigation may do the trick. Will be trying it shortly.

**Comment by adamosborne83** [comment]
Well I'm happy 😊 thanks,

**Comment by L0bsang** [comment]
I have tried v0.5.12 layout and it seems good! 

A couple of minor observations:
1. Seems a tad redundant in the library to have down open the same view menu as the button on the side but it definitely makes sense, since it could go to Bump or Explore instead. I am wary of adding too many options to the skin or I would say maybe a way to disable the "View" button in the library if OnDown navigation goes to View would be quite neat. However this is fine as is.

2. I like having that button to open sidemenu, definitely can see the use, especially as a way to access the player controls from the settings menu, and seems more consistent than having them all appear in the settings menu. 
Currently I have the Movie and TV Show sidemenu click going to a library hub, but I feel like my family would expect it to go to the homescreen section.
I can adapt to this by setting up custom hubs to look the same as the home menu sections or setting all of them to ActivateWindow(Home) on click and putting my hub shortcuts into the settings menu instead. Again, this is quite fine, just need to setup the workaround.

**Comment by xyzfre** [comment]
Loving the new layout, I think it's perfect the way it is at this current state

**Comment by adamosborne83** [comment]
> Loving the new layout, I think it's perfect the way it is at this current state

Agree, thanks J.

**Comment by jurialmunkey** [comment]
@L0bsang 

> I am wary of adding too many options to the skin or I would say maybe a way to disable the "View" button in the library if OnDown navigation goes to View would be quite neat.

Yeah I wouldn't want to add *another* option but I think it would make sense if the open ondown (or onright for lists) is enabled that the view button is swapped for another. Maybe Search?

> Currently I have the Movie and TV Show sidemenu click going to a library hub, but I feel like my family would expect it to go to the homescreen section.

In 5.13 this is actually optional. The button will be "Close" by default but there is a skin setting to swap close with "Menu".

**Comment by L0bsang** [comment]
Yes this layout is ticking a lot of boxes. Thanks for the changes! (I also see a handy player menu in the view panel)

Replacing view with search is a decent solution, especially with the different search modes available. Maybe it can be on the top left similar to how it is in home menu for consistency? Although I imagine that would then place the view button up there when not swapped, which may not be ideal.

Side question, the combine widgets option is global right? I was thinking it might be nice to use it only in my hubs with down to explore.

**Comment by Bindou01** [comment]
I really appreciate the new section which allows you to advance through the lists in several ways, alphabetical, wall format, etc.
But why not leave a simplified fast forward bar in wall mode (without shutter)? Will the bottom be reserved for another functionality? Or is it to simplify the interface?
I found it practical to be able to move forward quickly in wall mode, without the appearance of the shutter which hides part of the view. I find that the two solutions are complementary.

**Comment by Aemstel2** [comment]
I think it's very nice now, in v0.6.0. Great job.

**Comment by jurialmunkey** [comment]
> I think it's very nice now, in v0.6.0. Great job.

Thanks! I think the slider makes a big difference in making it more obvious that you can scroll left/right.
