### ISSUE TITLE
change alternate versions to poster instead of landscape

### ISSUE THREAD

**Issue by Aemstel2** [jurialmunkey/skin.arctic.fuse#585]
### Skin section

Video Info Dialog

### Feature description

Alternate movie versions now show landscape images. Would like to be able to change that to posters.

### Why is this feature needed? Please justify and explain.

In my library I have different posters for different versions of the same movie. Would like to show those posters instead of landscapes in the alternate versions section.

On a related note (I didn't think it necessary to create a separate issue report for this, please correct me if I should): underneath the alternate versions it shows the movie's genre. I don't think that info is very useful? The genre is already shown elsewhere. Might be better/ cleaner to only show the version-text, imho.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
It has to be landscape in details dialog for consistency due to the slide animation positioning.

On a standard 16x9 screen 4 landscape or 7 posters fit. The details on the left equal 1 landscape width so when it slides over the posters won't neatly fit into that space.

Managing the text is actually a massive issue as there is no proper flag to identify a version item inside the version folder, and the substring check is very inefficient. With the way the sub label is handled in a variable it isn't a good candidate for changing.

**Comment by Aemstel2** [comment]
Right, I understand. Maybe something is possible in the future when Kodi finetunes versions a bit more.
