### ISSUE TITLE
sometimes wrong artwork is loaded when entering library

### ISSUE THREAD

**Issue by Aemstel2** [jurialmunkey/skin.arctic.fuse#597]
### Skin section

Library

### Current Behavior

When entering movie library from home-screen, the first movie it lands on sometimes (not always, seems random) shows incorrect artwork. I think it loads artwork from TMDB instead of the local artwork. When moving away from the movie to the movie next to it and then back to it, it loads the correct artwork.

This never happens with Estuary skin. Also, I have another instance of Kodi on a different machine, and there this issue doesn't occur. So I figured it might be a TMDB Helper cache issue. But clearing that cache does not fix the issue.

### Expected Behavior

Always load locally configured artwork when entering a library.

### Steps To Reproduce

1. From home-screen enter the movie library. Be sure it lands on a movie and not the parent directory icon. Disable that.
2. Notice the artwork on the first movie it lands on is sometimes incorrect. Not always, it seems random.
3. Moving to the next movie and back loads the correct artwork.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This happens because sometimes TMDbH is in the middle of processing the blurred artwork for the previous item when the item changes and very occasionally there ends up a race between the old and new with setting the properties to the container.

If you set the background artwork style to Fanart, Simple, or Fake (instead of Real Blur) so that it isn't using TMDbH then you will notice that it doesn't happen and artwork switches much faster because it doesn't need to be processed.

**Comment by Aemstel2** [comment]
I tried Simple and Fake and they still have this issue with the clearlogo, but no longer with the flixart.

**Comment by jurialmunkey** [comment]
> I tried Simple and Fake and they still have this issue with the clearlogo, but no longer with the flixart.

Yeah logo is cropped via TMDbH so will have the same issue.

> Also on the other Kodi installation I don't have this issue at all. Even with Real Blur. Maybe because that's a 1080p installation and the other is 4K..?

Less to do with resolution directly and more to do with processing power (which in a roundabout way the resolution affects since it takes more processing power for Kodi to render at 4k) . 

If artwork is processed quickly, then the race condition is less likely to happen when the item changes. It will simply set old artwork then new artwork in order.

I could set it to not be threaded which would force it to happen sequentially and not out of order, but that then will make things slower because the previous item must complete processing entirely before next item can start.

**Comment by Aemstel2** [comment]
Right, I understand. Thanks for explaining. I'll settle for Fake Blur then.
