### ISSUE TITLE
Option to change the spotlight content

### ISSUE THREAD

**Issue by patkino** [jurialmunkey/skin.arctic.fuse#6]
### Skin section

Home Widgets

### Feature description

Option to choose widget for the spotlight 

### Why is this feature needed? Please justify and explain.

Never found an option to change the spotlight content and it seems random to me

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Choose "background" from the side buttons in the customisation dialog.

Additionally, in the hubs the submenu content has an option to be used as the background widget so that it will switch as you move to different items. If you want it to be fixed to only the selected widget then just need to disable that option for each submenu
