### ISSUE TITLE
:sparkles: Toggle to replace episode thumbnail with fanart.

### ISSUE THREAD

**Issue by ryandotnet** [jurialmunkey/skin.arctic.fuse#617]
### Skin section

Library

### Feature description

Currently fanart for my anime library imported by the Shokodi plugin (https://github.com/ShokoAnime/Shokodi) replaces all episode images, overwriting the episode thumbnails. Is it possible to have a toggle / setting for it to not replace episode thumbnails?

### Why is this feature needed? Please justify and explain.

It breaks the episode thumbnails and it looks horrible, having the fanart displayed 7-8 times on the screen.

### Screenshots and Additional Info

![example](https://github.com/jurialmunkey/skin.arctic.fuse/assets/35957436/3239a766-5047-40ea-b8ed-2b962baff91f)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
This is nothing to do with the skin. The addon needs to fix this issue by providing episode thumbnails correctly in the Art(thumb) artwork type and setting the correct metadata.

With the correct metadata, episode thumbs are displayed in the skin.

**Comment by ryandotnet** [comment]
> This is nothing to do with the skin. The addon needs to fix this issue by providing episode thumbnails correctly in the Art(thumb) artwork type and setting the correct metadata.
> 
> With the correct metadata, episode thumbs are displayed in the skin.

Thanks for letting me know! I apologise as I've been advised that it would be a skin configuration issue and truthfully I don't know how it works so I decided to make this issue. I'll try and confirm with the plugin / addon creator and see if we could get to the bottom of this. Can I leave this issue open for a few days while I work this out?

**Comment by jurialmunkey** [comment]
For comparison, here is how Episodes look in TMDbHelper.
ListItem.DBType is set to Episode and thumbnail is placed in ListItem.Art(thumb)

![screenshot00475](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/41987137-9577-4eb3-a245-9b544aabcd8d)

> I apologise as I've been advised that it would be a skin configuration issue

You can see the conditions the skin uses here for landscape artwork:
https://github.com/jurialmunkey/skin.arctic.fuse/blob/85a5e8f60373681b55fd3de2d15b8b5865a18de0/1080i/script-skinvariables-images-includes.xml#L4900

So these are the conditions to show thumbnail

DBType is Episode or Video
`[String.IsEqual(ListItem.DBType,episode) | String.IsEqual(ListItem.DBType,video)]`

The Art(thumb) is available ( ! means not) and fanart hasn't been forced as Icon
`!String.IsEmpty(ListItem.Art(thumb)) + !String.IsEqual(ListItem.Icon,ListItem.Art(fanart))`

Spoilers aren't hidden (otherwise fanart is shown)
`!String.IsEqual(ListItem.Icon,OverlaySpoiler.png)`  

The thumb isn't the poster artwork (because posters are wrong dimensions)
`!String.IsEqual(ListItem.Art(thumb),ListItem.Art(poster)) + !String.IsEqual(ListItem.Art(thumb),ListItem.Art(tvshow.poster))`

For fanart to be shown in landscape, it needs to fail one of the above conditions.

> Can I leave this issue open for a few days while I work this out?

Sure, no problem at all.
