### ISSUE TITLE
Unable to deselect options on Content > Hubs > Down setting

### ISSUE THREAD

**Issue by Omarscomin** [jurialmunkey/skin.arctic.fuse#621]
### Skin section

Widgets

### Current Behavior

As of right now, the "options" bar is displayed at the end of my hubs, and there is no way to disable/deselect it in skin settings > navigation

### Expected Behavior

To be able to select "none" as an option for Content > Hubs > Down, as I don't want anything to be displayed there. 

### Steps To Reproduce

1. Skin settings > navigation > Set "Content > Hubs > Down" to "Options"
2. Try to set it back to displaying nothing when you reach the end of a hub 

### Screenshots and Additional Info

![Kodi_20240322_094229.png](https://github.com/jurialmunkey/skin.arctic.fuse/assets/129215684/5bbe33d3-40ff-4314-a0d7-8cab285e9708)

OS: Android
Device: 2019 Nvidia Shield Pro
Kodi Version: Omega RC2

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Rinicko** [comment]
Thank you, having the same problem

**Comment by tpaniaki** [comment]
Same on Omega RC1 Xbox.

**Comment by jurialmunkey** [comment]
Can you explain further what the issue is with displaying the Options tray? Other than just personal preference?

The shortcuts it displays are customisable, so you can use it for whatever you like. I plan to extend its use through out the skin to make down navigation more consistent.

**Comment by Omarscomin** [comment]
> Can you explain further what the issue is with displaying the Options tray? Other than just personal preference?


I feel like this is a trick question, because my explanation will be based on personal preferences😬😅I just prefer for there to be absolutely no confusion about which widget is the last widget on a page. I certainly understand why one would like and make use of the Options tray, as well as the other options that you made available for that spot, but I guess it seems strange to be _forced_ to have something there, especially since I've already found a home for all of the shortcuts that I use.

**Comment by tpaniaki** [comment]
To @Omarscomin defense, this post came before the option menu got moved from the sidebar (which then looked like a redundancy). If the tray is to stay there, a "bump" option would complicate (graphically) the access to the menu and shut Kodi down.

**Comment by tduong-cloud** [comment]
Is it possible to disable the option tray ? I have disable the items within but I can still see "Options"

**Comment by Omarscomin** [comment]
> Is it possible to disable the option tray ? I have disable the items within but I can still see "Options"

@tduong-cloud 
No. That's what I'm requesting with this post.

**Comment by tduong-cloud** [comment]
Yes, I have read it somewhere else here.

Will deal with it :).

Le lun. 25 mars 2024 à 00:49, Omarscomin ***@***.***> a
écrit :

**Comment by jurialmunkey** [comment]
> I feel like this is a trick question, because my explanation will be based on personal preferences😬😅I just prefer for there to be absolutely no confusion about which widget is the last widget on a page.

No, no trick question. Genuine question to try to understand better the issue/concern at hand and find something appropriate that will also be consistent across the skin.

My idea with the options tray is that in the library there's typically a need for accessing a toolbar for changing view options. However, like scrollbar, that's inconsistent navigation with other parts of the skin. 

My vision is that down either continues to another widget (or another page of widgets e.g. explore) or it stops. Ideally it would just continue infinitely but so far I haven't found a good way to get Kodi to do something like that. So since I can't do that, I need it to stop somewhere, so I thought options might be a good choice.

It's not the concept of bumping at the end that I have an issue with - that I'm fine with. The problem I face more here is what to display in the bottom left. When the footer is enabled, it is fine because you see the footer. But when it is disabled there needs to be a widget text in that space otherwise it makes the skin look a little broken because suddenly a space that always had content doesn't.

Lots of people complained when I added the "No more widget groups" text, which was my initial attempt here to solve this issue. So my second attempt is to go to Options (which then bumps). I'm not saying it is perfect, it just seems the most simple, least intrusive approach

**Comment by tduong-cloud** [comment]
Is there an option to loop up? That would be sick :D

Le mar. 26 mars 2024, 11:45, jurialmunkey ***@***.***> a
écrit :

**Comment by jurialmunkey** [comment]
> Is there an option to loop up? That would be sick 🗡️ 

That's what I would want to do (at least for classic) -- end loops back to top (and vice versa). 

It's not impossible but there are some annoying animation issues that I can't solve and which make it look bad when looping back around -- it's a little difficult to explain but you can see the type of issue it causes by scrolling all the way down through all the groups, then instead of scrolling back up, go to sidemenu and move to top icon and scroll down through the groups again and you'll see this really bad animation when switching between.

**Comment by tduong-cloud** [comment]
That would just be sick, but not a priority I think. Thanks again for your
great work.

Le mer. 27 mars 2024, 04:13, jurialmunkey ***@***.***> a
écrit :

**Comment by Omarscomin** [comment]
@jurialmunkey loving the "bump" for this feature. Thank you so much😊
