### ISSUE TITLE
Content-Hubs-Down ,,set to Explore shows up blank

### ISSUE THREAD

**Issue by xyzfre** [jurialmunkey/skin.arctic.fuse#626]
### Skin section

Widgets

### Current Behavior

Content-Hubs-Down set to Explore (ActivateWindow(1182) when pushing down it shows up blank, this just started happening with the recent update was working fine yesterday,, it’s only happening with the Home hub ,, with the Movies and TV show hubs the explore on down feature is working perfect 

### Expected Behavior

When using the Home hub, enable Content-Hubs-Down set to Explore when pushing down on my last widget for it to show recommendations etc..

### Steps To Reproduce

//

### Screenshots and Additional Info

//

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by xyzfre** [comment]
https://github.com/jurialmunkey/skin.arctic.fuse/assets/49699869/fe58250f-6f1e-4518-839f-a0600ce39cdf

**Comment by jurialmunkey** [comment]
It's a little tricky to customise atm but basically it will show your classic mode widgets for the icon if in categories mode, or the global widget set if in classic mode.

So in the customisation screen, if you switch it over to classic or global then add widgets then switch it back then it should work.

**Comment by Rinicko** [comment]
> It's a little tricky to customise atm but basically it will show your classic mode widgets for the icon if in categories mode, or the global widget set if in classic mode.
> 
> So in the customisation screen, if you switch it over to classic or global then add widgets then switch it back then it should work.

Wow... that's actually a pretty useful feature.. but totally hidden

**Comment by Rinicko** [comment]
> It's a little tricky to customise atm but basically it will show your classic mode widgets for the icon if in categories mode, or the global widget set if in classic mode.
> 
> So in the customisation screen, if you switch it over to classic or global then add widgets then switch it back then it should work.

Could you please give some insight into how this feature works 🙏🙏

I couldn't decide between this one and the new options tray, so I added a button in the options tray to ActivateWindow(1182), but this only shows the classic widget for the home icon.. When using the one from the navigation settings, does that open different windows for each icon or is there another reason why the button only opens the home icon classic widgets?? 🤔🤔

**Comment by Rinicko** [comment]
> It's a little tricky to customise atm but basically it will show your classic mode widgets for the icon if in categories mode, or the global widget set if in classic mode.
> 
> So in the customisation screen, if you switch it over to classic or global then add widgets then switch it back then it should work.

Also another thing, really sorry for any bother... why does it show an alarm clock notification when you exit the explore page with the back button

**Comment by jurialmunkey** [comment]
> Wow... that's actually a pretty useful feature.. but totally hidden

It's a bit of an experiment for me to test out some ideas for a more modular home screen without fully committing to a complete overhaul just yet -- which is why it is fairly hidden at the moment.

My eventual end goal is to make the classic/complex/global distinction redundant. Instead, there will simply be a home screen which adapts based on what widgets/categories/submenus/spotlights have been set -- e.g. if you want classic, you simply delete the categories; if you want complex, you simply add categories.

The window is a stepping stone on the way to that idea of there being different "levels" of widgets from more global to more specific.

> 
> I couldn't decide between this one and the new options tray, so I added a button in the options tray to ActivateWindow(1182), but this only shows the classic widget for the home icon.. When using the one from the navigation settings, does that open different windows for each icon or is there another reason why the button only opens the home icon classic widgets?? 🤔🤔

It requires a window property to be set before opening the window to determine which GUID to use.
`SetProperty(Hubs.ExtendedWidgetGUID,$INFO[Container(303).ListItem.Property(guid)],Home)`

But I wouldn't get too deeply attached to it in this form. It will be removed eventually, which is why it isn't listed in the shortcuts and can only be set ondown.

**Comment by xyzfre** [comment]
Thank you @jurialmunkey for adding this new setting in Furniture Left Footer info+library+widgets this is perfect. You get the best of both.(LEGEND)

**Comment by L0bsang** [comment]
> My eventual end goal is to make the classic/complex/global distinction redundant. Instead, there will simply be a home screen which adapts based on what widgets/categories/submenus/spotlights have been set -- e.g. if you want classic, you simply delete the categories; if you want complex, you simply add categories.
> 

Nice, will look forward to this! At the moment I jump between two home layouts in classic and complex modes because of the tradeoffs in navigation between them. 
Currently preferring the classic mode setup with "navigate between widget groups" selected and footer set to "Information+Library" because I find this is quite intuitive for the family. One can always see the next widget, the side menu highlight shows you which group you are in at the moment, and continuously pressing down will keep bringing up more content (using the explore at the end).

However I would like to have a spotlight at the top use some of the adaptive menus in complex mode. Replicating this layout in complex mode made it not as intuitive since I lose the continuous vertical scroll. Tried various combinations of menu, category and widget visibility.

**Comment by xyzfre** [comment]
> It's a little tricky to customise atm but basically it will show your classic mode widgets for the icon if in categories mode, or the global widget set if in classic mode.
> 
> 
> 
> So in the customisation screen, if you switch it over to classic or global then add widgets then switch it back then it should work. 

Sorry to bother you with this again really love the on down explore feature ,I was trying to figure this out, but I'm stuck ,the explore on down feature still shows up blank on my Home hub ,, it works for my movie hub and TV show hubs just not Home hub,, my set up is all complex mode never even tried Classic,on Windows 11 RC2 I'm on the latest version of AF.

**Comment by jurialmunkey** [comment]
@xyzfre - I wouldn't worry about it too much right now. It is being reverted to the default explore and I'm going to introduce a more simplified version of this "extended" explore window that is easier to configure.

**Comment by xyzfre** [comment]
@jurialmunkey loving the new update thank you for sharing this amazing skin you just keep surprising us LOL, but it's getting better and better💯💯

**Comment by xyzfre** [comment]
@jurialmunkey my apologies for commenting on this close issue, but having a hard time only on the Home Hubs to set up the on down explore feature like the way it used to be that it will show you recommendations etc.. it works perfect on my movie Hubs and TV show Hubs just not the home hub I must not be doing something right any help will be greatly appreciate it

**Comment by xyzfre** [comment]
https://github.com/jurialmunkey/skin.arctic.fuse/assets/49699869/f89b8cb8-9162-4974-b7ee-c520072e9bf8 Movie Hub

**Comment by xyzfre** [comment]
Movie Hub

**Comment by xyzfre** [comment]
https://github.com/jurialmunkey/skin.arctic.fuse/assets/49699869/12d1d9b0-7e6d-43a6-856b-12dcc4377a17

**Comment by xyzfre** [comment]
Tv Show Hub

**Comment by jurialmunkey** [comment]
On home, the explore page allows you to extend the widgets with an additional set per side icon. You can configure what widgets are shown by editing sidemenu and then choosing option to edit explore widgets

**Comment by xyzfre** [comment]
> On home, the explore page allows you to extend the widgets with an additional set per side icon. You can configure what widgets are shown by editing sidemenu and then choosing option to edit explore widgets

@jurialmunkey THANK YOU❣️ for explaining it,got it now finally, it's a hidden gem brilliant💯,I have a nice plan for this feature🙌🏼
