### ISSUE TITLE
Trailers on Info screen.

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#630]
### Skin section

Widgets

### Current Behavior

Kind of a request more than bug I guess.
Can you please bring back 'dialog' to play trailers in. 
Just if I watch a trailer on my library movies, it's refreshed by the time it finishes, so I lose the movie I wanted to watch.

### Expected Behavior

To play trailers within the info screen

### Steps To Reproduce

Click trailer within info

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
You can still set dialog.

The trailer setting was simplified to toggle between fullscreen or minimised, then the "minimised" setting changes depending on whether you have set the skin for background video playback or picture-in-picture dialog (in Skin Settings > Appearance)

Change was because the combo of trailer=background and backgroundvideo=disabled results in no playback since background video control is disabled.

My thinking was that if someone needs to disable PIP and switch to background video, it's because their system can't render video in a dialog, so it'd also be good to prevent that.

**Comment by adamosborne83** [comment]
> You can still set dialog.
> 
> The trailer setting was simplified to toggle between fullscreen or minimised, then the "minimised" setting changes depending on whether you have set the skin for background video playback or picture-in-picture dialog (in Skin Settings > Appearance)
> 
> Change was because the combo of trailer=background and backgroundvideo=disabled results in no playback since background video control is disabled.
> 
> My thinking was that if someone needs to disable PIP and switch to background video, it's because their system can't render video in a dialog, so it'd also be good to prevent that.

Morning J, you know I try not to cause too many issues. Although, this one is difficult. The issue is, whenever you click trailer from the info screen it closes the info screen, which then allows kodi to refresh, therefore losing the movie.
Is there anything you can do to help with this?
I'm sure in the AH2 days, I could click trailer and it would play full screen and then still be in the info screen when I stopped playback?

**Comment by jurialmunkey** [comment]
> The issue is, whenever you click trailer from the info screen it closes the info screen, which then allows kodi to refresh, therefore losing the movie.

Only `Skin Settings > Behaviour > Play trailers in fullscreen` will close the info dialog because it must close to get to the fullscreen video controls.

These combos don't close the info dialog:
Skin Settings > Appearance > Enable background video
Skin Settings > Behaviour > Play trailers in background
(i.e. videos play in background)

OR

Skin Settings > Appearance > Disable background video
Skin Settings > Behaviour > Play trailers in dialog
(i.e. videos play in a dialog) 


>I'm sure in the AH2 days, I could click trailer and it would play full screen and then still be in the info screen when I stopped playback?

AH2 faked a fullscreen trailer by overlaying a video control across the entire dialog. It never went "real" fullscreen.

The problem was that you could still interact with the controls in the video info dialog behind the video overlay, you just couldn't see them but you could still click them by mistake.

**Comment by adamosborne83** [comment]
> > The issue is, whenever you click trailer from the info screen it closes the info screen, which then allows kodi to refresh, therefore losing the movie.
> 
> Only `Skin Settings > Behaviour > Play trailers in fullscreen` will close the info dialog because it must close to get to the fullscreen video controls.
> 
> These combos don't close the info dialog:
> Skin Settings > Appearance > Enable background video
> Skin Settings > Behaviour > Play trailers in background
> (i.e. videos play in background)
> 
> OR
> 
> Skin Settings > Appearance > Disable background video
> Skin Settings > Behaviour > Play trailers in dialog
> (i.e. videos play in a dialog) 
> 
> 
> >I'm sure in the AH2 days, I could click trailer and it would play full screen and then still be in the info screen when I stopped playback?
> 
> AH2 faked a fullscreen trailer by overlaying a video control across the entire dialog. It never went "real" fullscreen.
> 
> The problem was that you could still interact with the controls in the video info dialog behind the video overlay, you just couldn't see them but you could still click them by mistake.
> 

I'm not at mu set up right now. I am 99.9% sure that Play Trailers in Dialog has gone? The reason I opened the issue. As I knew you added dialog for me previously when we spoke about Trailers.

**Comment by Liquidrag** [comment]
> Skin Settings > Appearance > Enable background video Skin Settings > Behaviour > Play trailers in background (i.e. videos play in background)
> 
> OR
> 
> Skin Settings > Appearance > Disable background video Skin Settings > Behaviour > Play trailers in dialog (i.e. videos play in a dialog)

To be clear, if we want trailers to play in dialog, we can NOT have background video as before? Previously trailers played in dialog but if I were watching a movie and backed out, the movie would still be visible in the top right spotlight type area.

**Comment by jurialmunkey** [comment]
> To be clear, if we want trailers to play in dialog, we can NOT have background video as before

That's correct. Otherwise I end up with bug reports like https://github.com/jurialmunkey/skin.arctic.fuse/issues/601 where people set an incompatible combo of settings which results in not being able to see playback at all.

**Comment by Liquidrag** [comment]
> It seems like playing trailers in the dialog is the preferred option, so maybe it is simpler to do away with the option altogether an only play in dialog.

Personally, that is what I like, it is consistent with playing trailers option on the flyout side menu and items in info does not refresh once the trailer has ended. 

<img width="1230" alt="Screen Shot 2024-03-25 at 9 19 09 AM" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/67547481-bdbb-413e-a769-9936a2ee3cca">

**Comment by adamosborne83** [comment]
> It seems like playing trailers in the dialog is the preferred option, so maybe it is simpler to do away with the option altogether an only play in dialog. 

Thank You J,

**Comment by L0bsang** [comment]
I like watching trailers fullscreen. But it did seem unusual that you would come back to your menu after a trailer in information, and had to go back into the information screen you were in when the trailer started information.
If it works better to have them in dialog/background so that the information screen stays focused, that seems like a worthwhile tradeoff.

Although that means there is no control over the trailer right, will continue playing unless you navigate to the videoplayer controls and stop it there? Doesn't seem ideal.

**Comment by adamosborne83** [comment]
> I like watching trailers fullscreen. But it did seem unusual that you would come back to the previous menu, and had to go back to the information screen you were in when the trailer started.
> If it works better to have them in dialog/background so that the information screen stays focused, that seems like a worthwhile tradeoff.
> 
> Although that means there is no control over the trailer in background right, will continue playing unless you navigate to the videoplayer controls and stop it there? Doesn't seem ideal.

Dialog you can, pause, stop, FF, REW,loop, do the whole lot. No functionality is lost at all.

**Comment by L0bsang** [comment]
I just tried dialog trailer in information and it works nicely, unlike background trailer I do have the full controls.

Am I correct in assuming that if I enable dialog trailer I need to use picture-in-picture instead of background for general video playback? 
PIP was causing crashes when it was first added so I disabled it (haven't checked it out recently); background video was also larger allowing me to see the playing video more clearly.

**Comment by xyzfre** [comment]
@jurialmunkey  With these new changes when watching a trailer, is there a way for me to see if it's playing for example 4K ,1080,720

**Comment by vella9** [comment]
@jurialmunkey from the option to autoplay trailers in background when opening info dialog, is there a way to toggle fullscreen please? Awesome job for this feature nonetheless! thank you!

**Comment by jurialmunkey** [comment]
@vella9 not directly but if you click the trailer button it will relaunch in the dialog and you can go to fake fullscreen from there

**Comment by jurialmunkey** [comment]
@xyzfre no, no resolution indicator. Though I'm not sure why that's important for a trailer?

**Comment by vella9** [comment]
> @vella9 not directly but if you click the trailer button it will relaunch in the dialog and you can go to fake fullscreen from there

would it be possible to continue trailer playback once trailer button is pressed? instead of starting from the beginning.

**Comment by xyzfre** [comment]
> @xyzfre no, no resolution indicator. Though I'm not sure why that's important for a trailer? 

It's not important,I think it's handy, sometimes to see if the trailer is playing in 4K and also there's some useful info on the left-hand side about the trailers. no biggie I was still able to accomplish this by using the context menu trailer option if I needed to see that info about the trailer. thank you  @jurialmunkey for the recent changes it's coming along amazing.![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/49699869/2f2ec9a3-3c8d-43db-a0df-3b1eb3a5c02e)

**Comment by xyzfre** [comment]
![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/49699869/16ca68ff-fe1b-4a86-aa6a-ed3385a0e063)
