### ISSUE TITLE
✨️ Option to customize startup point

### ISSUE THREAD

**Issue by Rinicko** [jurialmunkey/skin.arctic.fuse#647]
### Skin section

Widgets

### Feature description

Currently it starts focus on the second item, would be nice to get an option to change it back to the first item

### Why is this feature needed? Please justify and explain.

I used linked categories to avoid showing multiple categories on my homepage, unless they are needed... Starting on the second item instead of the home item will make the linked category visible, which defeats the feature's purpose of minimalism. Just an option to be considered 

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
You already can. Edit side menu in config. There is an option "default" which can be toggled on to set which icon has focus on start.

For the first item you might need to toggle it on/off to get it to set initially because I need to fix up the visual for the checkbox condition (kodi thinks an unset setting is same as 0 so the checkbox incorrectly shows as ticked for first item if the setting has never been set yet).

**Comment by Rinicko** [comment]
> You already can. Edit side menu in config. There is an option "default" which can be toggled on to set which icon has focus on start.
> 
> For the first item you might need to toggle it on/off to get it to set initially. I need to fix up the visual for the checkbox condition. kodi thinks an unset setting is same as 0 so the checkbox incorrectly shows as ticked for first item if the setting has never been set yet).

Ohh i see... I saw that option and was wondering why my home was default and yet my second item was on focus... Alright then I'll reselect it now... Thank you very much
