### ISSUE TITLE
losing focus from default side menu icon after using 'Next' button from Video OSD

### ISSUE THREAD

**Issue by vella9** [jurialmunkey/skin.arctic.fuse#673]
### Skin section

Widgets

### Current Behavior

Hi jurial, unfortunately issue #655 is happening again. Focus is getting lost when moving from first side menu icon [which is set to default] to the widget row, this time after watching multiple episodes [I noticed this after watching 2 'consecutive' episodes] using the 'Next' button from video OSD. I am using classic mode and I am on latest version 0.6.24. I also have Navigation>Content>Move between widget groups set to disabled.

This is occurring once you return to the main screen after watching multiple episodes. Once you return to the main screen, any button press will take you to the first side menu item and again, you can already notice that the first widget row is "darkened" and if you press the right button, focus is lost. A reload skin only will solve this issue.

I also have Autoclose OSD after X seconds enabled.

### Expected Behavior

once right button is pressed from first side menu icon, after watching multiple episodes using the 'Next' button on the video OSD, focus should be on the first item of the first widget.

### Steps To Reproduce

1. watch an episode 
2. use the 'Next' button from video OSD to watch the next episode once the first one has finished
3. once the second episode finishes, press the 'stop' button
4. you are returned to the main screen, press any button and this will take you to the first side menu item
5. press right to focus on first item of first widget
6. focus is lost

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by vella9** [comment]
Hi @jurialmunkey . I am attaching a video of the issue occurring. I appreciate if this can be looked into, Thanks

https://github.com/jurialmunkey/skin.arctic.fuse/assets/137268669/be891610-6bd5-478b-9058-5625b1964e9c

**Comment by vella9** [comment]
Hi @jurialmunkey , I wanted to share an update.

I added Discover to the side menu as a third option and upon exiting from the Discover, focus is lost as well here. 

I am thinking that this is related to the Default option of the side menu items. This is only my guess though.

I appreciate it if you can find some time to look into this as this is the only issue I am encountering to this amazing skin! 

Thanks

**Comment by jurialmunkey** [comment]
@vella9

Can you enable the debug info overlay found in expert skin settings (all the way at the end after dependencies). Then get me a video or screenshots of the various steps - will give me a good indication of which properties are set.

Also to double check - but does your very first widget in each group have content? (ie not disabled / none / or otherwise have no items). And are you using global widget groups anywhere?

**Comment by vella9** [comment]
@jurialmunkey thank you for your time to look into this 🙏

Kindly find the first video that relates to the Discover. 

https://github.com/jurialmunkey/skin.arctic.fuse/assets/137268669/a4c3e6f5-42d9-43ae-b6f0-4d17837859fb


> Also to double check - but does your very first widget in each group have content? (ie not disabled / none / or otherwise have no items).

Yes, my first widget in each group have content. I also do not have any disabled widgets or widgets set to none.



> And are you using global widget groups anywhere?

No, I am not using global widget groups.

I will be posting another video soon which relates to 'watching consecutive episodes'. Thank you!

**Comment by vella9** [comment]
@jurialmunkey 

Kindly find second video for 'watching consecutive episodes' using the next button on the video OSD. As previously stated, Movies side menu icon is set as 'default'.

https://streamable.com/hrddv7

Thank you!

**Comment by vella9** [comment]
sorry to disturb you again on this @jurialmunkey but I just wanted to let you know that this is still occurring in v0.6.24.

**Comment by jurialmunkey** [comment]
Yep sorry just haven't had a chance to look into it yet as have a busy patch at work at the moment. But will try to look into it soon.

**Comment by vella9** [comment]
no worries jurial and thank you for looking into this!

**Comment by jurialmunkey** [comment]
Can you let me know if this is still occurring in 0.7.4 ?

**Comment by vella9** [comment]
Hi @jurialmunkey, thanks for following up.

No issue is not occurring anymore, the only thing I wanted to highlight is that after watching multiple episodes using the 'next' button, upon returning to the Home Hub, any button press will take you to the first side menu item. Other than that, issue is not there anymore.

Thank you as always!

**Comment by jurialmunkey** [comment]
Yeah I think that's as good as we're likely going to get.

Something is causing Kodi to forget which widget ID it had focused on the home screen (you can in the top line of the debug overlay that when you stop the video there is no ID number displayed anymore for current control).

I'm guessing that the screen refresh rate change from video stopping causes the mouse cursor to reposition slightly and as a result end up with nothing focused because of where it is on screen -- which would also explain why it doesn't always happen.

Since no ID has focus, Kodi will simply focus the default control (the menu) instead when a direction is pressed - which is expected.

Problem previously was that the first widget group is not what we had saved in the property to tell the skin which widget is active. Pressing right from menu tells the skin to focus the widget that is stored in that property and we end up stuck because focus is now on a widget inside a group which is no longer active (and so Kodi won't accept inputs for that group).

With the recent skin changes, now if the menu focus position changes then the skin resets everything back to the top positions -- which forces the saved property to match what is on screen. Also, with the widgets now all being in one big group, even if you do end up on a widget that isn't active itself, the parent group is still visible so it will still accept input.

**Comment by vella9** [comment]
understood jurial, thank you for the explanation and our work as always.
