### ISSUE TITLE
:bug: Category focus carries over to other sidemenu items

### ISSUE THREAD

**Issue by Dml2023** [jurialmunkey/skin.arctic.fuse#690]
### Skin section

Widgets

### Current Behavior

This is a really minor issue and not a real pain, but I thought I would let you know... I have TV and Movie sidemenu items and they each have 4 separate categories with their own widgets, If I was to scroll over to the 4th category of my TV sidemenu and look at the widgets press up to return to the spotlight and then navigate to the movie sidemenu item, the 4th category on the Movies sidemenu display has the focus.

### Expected Behavior

I would expect that the first time I access a side menu item that the first category would be the one that is focused.

### Steps To Reproduce

Have more than one sidemenu item with multiple categories.
Navigate to the first sidemenu item and then go to a category other then the first one.
Return to the spotlight widget and then left click to go back to the sidemenu.
Go to the next category with multiple categories.
The first category will not be focused.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Do these categories have the same name? e.g. Both "Genres" or similar?

Because if so, that's a Kodi behaviour I can't override. Whenever a container refreshes, if there's an item with the same label as was previously focused then Kodi will attempt to refocus that item.

It's the same reason in the combined views or adaptive submenus sometimes the widget will not be at the start and instead will be on the same item as from the previous list.

Not sure if that's what you're seeing or if it's something else.

**Comment by Dml2023** [comment]
Hi Jurialmunkey,

The first 2 categories are identical for both the TV and Movies sidemenu groupings however the 3rd and 4th are completely different. Eg. The 4th category in the TV sidemenu is labelled 'On the box' with 2 widget rows from TMDb Helper and the 4the category in the Movies sidemenu is labelled 'In Cinemas' with 3 widget rows from TMDb Helper.

As I mentioned above, it is not a real pain, I just wanted to let you know incase is is something you are able to control in the skin.

Cheers.

**Comment by jurialmunkey** [comment]
Does this still happen in 0.6.31 ?
