### ISSUE TITLE
Widget lag:

### ISSUE THREAD

**Issue by Blackysbd** [jurialmunkey/skin.arctic.fuse#692]
### Skin section

Widgets

### Current Behavior

Version 0.6.9 widgets are instant as can be seen in the video
When updating beyond 0.6.9 widgets have a delay, which is even worse on the nvidia shield

### Expected Behavior

Navigating widgets worked better before update

### Steps To Reproduce

Update beyond 6.0.9
No other changes

### Screenshots and Additional Info

https://imgur.com/a/uTUMCtx
https://imgur.com/9rBkbMy

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by CyberRooke** [comment]
How are you able to have just a search button in your side bar? 🤔🤔

**Comment by bassemhelal18** [comment]
Same issue

**Comment by CyberRooke** [comment]
> ### Skin section
> 
> Widgets
> 
> ### Current Behavior
> 
> Version 0.6.9 widgets are instant as can be seen in the video
> When updating beyond 0.6.9 widgets have a delay, which is even worse on the nvidia shield
> 
> ### Expected Behavior
> 
> Navigating widgets worked better before update
> 
> ### Steps To Reproduce
> 
> Update beyond 6.0.9
> No other changes
> 
> ### Screenshots and Additional Info
> 
> https://imgur.com/a/uTUMCtx
> https://imgur.com/9rBkbMy
> 
> ### Checklist
> 
> - [X] I have made a separate issue for each bug that I am reporting.
> - [X] I have searched the issues and this bug has not been reported.
> - [X] I am using the most recent skin version.
> - [X] I have confirmed that this bug does not occur in the default skin.

Off topic - How did you remove the options button from your side items, please 🙏??

**Comment by jurialmunkey** [comment]
The difference is that widgets are loaded ondemand now, hence the delay.

Previously ALL submenu widgets were being loaded everytime widgets refresh. 

Whilst that appears "fast" if they've already loaded, obviously it is pretty bad ettitique for free services like tmdb to load content you aren't even using constantly (eg if you have 20 genres in a submenu then you're loading all 20 each time and multiply that by however many submenus and categories you have and you can see it balloons out rapidly). I expect most plugins do some caching but still it is going to be a lot of unnecessary overhead. 

The bigger problem, however, is that Kodi loads widgets sequentially. So that submenu with 20 widgets will cause everything else which comes after it to be delayed in loading. This way with dynamic loading, widgets afterwards are not held up. 

The other problem from the code side is that this old approach means there no longer is a fixed ID for the top widget, which makes the skin code difficult (also why it didn't work with stacking). Whereas reusing the widget gives a fixed ID, which is necessary for some upcoming features I have planned and makes the skin much easier to manage. It also puts me on the path of being able to have the submenu widget work in combined mode. 

All of which is to say - the change is intentional and likely won't be reverted.

**Comment by Blackysbd** [comment]
Appreciate the detailed explanation, looking forward to see what you do with combined mode.
