### ISSUE TITLE
movies missing from actor credits when sorted by date

### ISSUE THREAD

**Issue by Aemstel2** [jurialmunkey/skin.arctic.fuse#706]
### Skin section

Video Info Dialog

### Current Behavior

When viewing an actor's credits it shows the movies in your library first. Which is great. This works fine except when sorting by Date. When sorted by date, many movies are missing.

### Expected Behavior

When sorting actor's credits by date, show all the actor's movies in the library at the front.

### Steps To Reproduce

1. Pick a movie with an actor you have lots of movies from
2. Go to the movie information
3. Go to Details
4. Choose the actor and choose Credits
5. Sort by Date
6. Notice how many movies are missing at the front

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
There's not much I can do about this. The results come from TMDb so it will be the first 50 results according to date and whatever library movies you have in there will be at the front.

**Comment by jurialmunkey** [comment]
Basically works reverse of what you're thinking. It doesn't get your library then add items onto it. It simply gets results from TMDb and whatever happens also to be in your library is moved to the front by the plugin.

This is for performance reasons because a library might have 1000s of items -- much slower to get 1000 items from library and check each one to see if they have the actor then add TMDb results on top VS. get 50 results from TMDb and check if those results are in the library.

**Comment by Aemstel2** [comment]
Ok, I understand. Thanks for the explanation.
