### ISSUE TITLE
skinvariables error installing AH2 besides AF

### ISSUE THREAD

**Issue by taiseer999** [jurialmunkey/skin.arctic.fuse#765]
### Skin section

Other

### Current Behavior

Once AH2 is is installed and skin to changed to AH2 from AF a persistent error pops up "skinvariables error"

### Expected Behavior

not to show

### Steps To Reproduce

Install AH2
Change skin from AF to AH2
Error message pops up
[01_KODI_CRASH.log](https://github.com/jurialmunkey/skin.arctic.fuse/files/15080220/01_KODI_CRASH.log)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Turn off extra fanart in Fuse before switching skins.
OR
Restart Kodi after switching skins.

It's a kodi issue where it does not cancel looping alarms after switching skins, so you need to do it manually first.

The error is because the alarm runs a timed command which does not exit in the second skin.

**Comment by taiseer999** [comment]
Thanks for the reply, could guide me to how to turn off the extra fanart

**Comment by jurialmunkey** [comment]
In skin settings appearance, at the bottom.

**Comment by taiseer999** [comment]
Git it thanks a lot
