### ISSUE TITLE
[Feature] default so search bar 

### ISSUE THREAD

**Issue by titelheld** [jurialmunkey/skin.arctic.fuse#78]
### Skin section

Home Widgets

### Feature description

When switching to the search window the default focus should be on the search bar so that one can immediately start type if the search query. 

### Why is this feature needed? Please justify and explain.

Currently the default focus is not on the search bar and this one has to select the search bar first before typeing the query. 

I understand this is great for the onscreen keyboard for people that do not have a keyboard remote but troublesome for those with keyboard remotes. 

### Screenshots and Additional Info

![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/25116213/797b37cc-e62f-42be-9f75-6d31aaefc4cc)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
The reason it is like this is because Kodi's "edit" control blocks the Back command (forces it to be "Backspace" instead)

If the edit control has focus by default navigation gets really confusing because you can't press back to leave and it's not immediately clear what you should do. Plus the cursor always ends at the right of the word when means you have to scroll through several letters to press left back into the side menu.

**Comment by titelheld** [comment]
Ah i see why that problematic. 

It was just so nice and simple in arctic horizon 2 to just select the search by going left and being able to start typing immediately.
