### ISSUE TITLE
Classic mode and move between widget groups bug

### ISSUE THREAD

**Issue by JFG1000** [jurialmunkey/skin.arctic.fuse#880]
### Skin section

Widgets

### Current Behavior

Hey jurial I've noticed when both of these are enabled a bug occurs with the widgets, upon skin reload or kodi launch instead of loading the first set of widgets on the first section it will cycle through them and then load a random widget set on that section, as an example, for me personally it would usually load next episodes first and highlight that, instead many times it will load me straight into shows watchlist. 

### Expected Behavior

Usually the skin loads is into the first set of widgets 

### Steps To Reproduce

Reload skin or launch kodi with multiple widgets set up on the first section 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Make sure default sidemenu item is first item. Otherwise kodi will have weird focus behaviour due to widgets in the list above loading afterwards.

Honestly should have never implemented the option to select default focus position. It's a huge thorn in my side!

**Comment by L0bsang** [comment]
> Honestly should have never implemented the option to select default focus position. It's a huge thorn in my side!

I think we can do away with this, especially if it is a problem. Always focusing on the first item makes sense, people can simply reorder their sidemenu items accordingly.

**Comment by jurialmunkey** [comment]
> I think we can do away with this, especially if it is a problem. Always focusing on the first item makes sense, people can simply reorder their sidemenu items accordingly.

Yeah I think the main reason people wanted it was to have search first, then focus the second item by default -- but I think with search/options additional icons being added back in, then it is less necessary.

I guarantee when I remove it people will complain like I'm killing their first born child though!

**Comment by JFG1000** [comment]
> > I think we can do away with this, especially if it is a problem. Always focusing on the first item makes sense, people can simply reorder their sidemenu items accordingly.
> 
> Yeah I think the main reason people wanted it was to have search first, then focus the second item by default -- but I think with search/options additional icons being added back in, then it is less necessary.
> 
> I guarantee when I remove it people will complain like I'm killing their first born child though!

Please could you leave it for an option for us to enable jurial? The only reason why I ask this mate as the search that is on the very top of the screen won't allow me to search specific content via an addon. I don't know how to figure the options and search one to do that unless someone can explain.

Many thanks

**Comment by L0bsang** [comment]
@JFG1000 

The search on the top of the screen does indeed allow you to search specific addon content. 
Look for Search option on the bottom  of widget customization window and add a search path the same way you would add a widget.

Custom search paths for various addons can be found here:
https://github.com/jurialmunkey/skin.arctic.horizon.2/discussions/1014
If the search path for the addon you are trying to search cannot be found in that discussion, you may need to check with the developer what search path could work (they should know since they coded that search option).

You absolutely do not need an option to have a default focus if all you are using it for is to have search as the first item but not focused. 
Just live with moving your search sidemenu item so it is not the first item, not so big a deal.

**Comment by JFG1000** [comment]
@L0bsang i shall look into having the search at the top then

**Comment by jurialmunkey** [comment]
> 
> Please could you leave it for an option for us to enable jurial? 

I can't "fix" the widget focus issue and keep this option. 

It is literally just how kodi works. The default item widget gets focused but if it is not available at that time (because it hasn't loaded anything yet) then Kodi focuses something else nearby. Additionally if content above that widget loads in afterwards, then it pushes the other widgets down after the focus property was set. 

The only solution is to always focus the first widget in the group and that's not possible if youre asking to focus something other than the first one by default. 

It's the same reason why there must be a spotlight in complex. I need a control which I know will be the first in the group so I can set focus to it.

**Comment by JFG1000** [comment]
No worries jurial completely understand thankyou for explaining it all, and your work on this amazing skin as always, I've got my search at the top like it used to be after tinkering with my set up last night, much prefer it that way, many thanks
