### ISSUE TITLE
:bug: classic mode side menu focus/group focus indicator 

### ISSUE THREAD

**Issue by vella9** [jurialmunkey/skin.arctic.fuse#887]
### Skin section

Widgets

### Current Behavior

when navigating up/down between side menu items in classic mode with group focus indicator=on and side menu>minimize=always/never, a visible delay of the group focus indicator is occurring. This is not the case in complex mode. 

### Expected Behavior

when navigating up/down between side menu items in classic mode, focus should hide the navigation of the group focus indicator entirely. 
Group focus indicator should navigate at the exact same time as the focus.

### Steps To Reproduce

1. select classic mode
2. group focus indicator=on
3. side menu>minimize=always or never
4. navigate focus up/down between side menu item
5. group focus indicator is visible between one side menu item to another

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This is needed to stop the skin unnecessarily spamming setfocus calls if scrolling fast through the menu.

It's similar to why submenu widgets paths only update once you stop of the submenu item rather than as you scroll.

It's not necessary in complex because there's no "move between groups", so the indicator is the same as the focused icon rather than based on focused widget (which has to wait for the focus command to fire).

**Comment by vella9** [comment]
understood, thanks for the info jurial.
