### ISSUE TITLE
Side Menu vertical 

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#933]
### Skin section

Widgets

### Current Behavior

Hey J,

Thanks for adding this in, but as you can see it jumps a bit.

### Expected Behavior

Not to

### Steps To Reproduce

Horizontal top bar.
Vertical info bar

### Screenshots and Additional Info

https://imgur.com/a/ck1peRv

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
There's not a lot that can be done about this. It is to do with how Kodi handles rendering with sync vs async loading of textures.

If the CPU/GPU can't serve sync textures fast enough to keep up with FPS then the GUI locks and you get animation jankiness (vs' async which renders regardless and so get smoother animations at the cost of textures popping-in).

It's particularly noticeable here because new window loading adds a lot of new controls to render, and there are a lot of complex animations affecting the entire screen (more parts of the screen to render = more overhead = more jankiness).

Future versions of Kodi will optimise this better with front-to-back rendering, reduced reliance on sync textures, and generally better options for more performant textures -- but from the skin side, there's not much that can be done to improve performance other than remove features (queue the crying).

I can attempt to mask it a bit better by increasing the delay where the animation switches from displaying library to info dialog (it might look like one window, but it is actually two windows here with some animation tricks to mask the seam) but I won't ever be able to "fix" it as it is a rendering issue.

**Comment by adamosborne83** [comment]
I think I'll close this issue, thank you for explaining and trying to fix it. 
Hopefully K22 will address the issue better.
Always appreciate J
