### ISSUE TITLE
🐛 Titles in Spotlight are jumping around

### ISSUE THREAD

**Issue by Rinicko100** [jurialmunkey/skin.arctic.fuse#963]
### Skin section

Widgets

### Current Behavior

Hello... I've noticed an issue with the titles on spotlight widget after recent change in title label approach... The titles seem to jump around from one size to another which makes it look a bit rough.

The video below is low quality but it does show the title jumping

https://github.com/jurialmunkey/skin.arctic.fuse/assets/172080110/f7936a88-7c6a-4441-8f8d-8ebcb89a8767

Also, it is not due to the change of font as I also tried it with the default font and got same result

### Expected Behavior

Titles should display normally

### Steps To Reproduce

Create a spotlight widget
Navigate from one item to the other

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Back to people whinging about the Kodi logo instead I guess it is then!

**Comment by Rinicko100** [comment]
> Back to people whinging about the Kodi logo instead I guess it is then!
> 

😭😭😂 well damn

I'm a little confused though, If you don't mind explaining it to me🤔🤔... OfficerKD spotted a way to remove the kodi logo... and it didn't seem to affect anything... Just wondering what the reason behind it being there is?

**Comment by jurialmunkey** [comment]
> I'm a little confused though, If you don't mind explaining it to me🤔🤔... OfficerKD spotted a way to remove the kodi logo... and it didn't seem to affect anything

Not affecting function and not affecting visual balance are two separate things.

The issue is that the title font is significantly smaller than most clearlogos. This size difference creates visual balance issues with vertical space.

Vertically centering the title in the space creates a large disconnecting gap to the info/plot. Bottom aligning the title creates an imbalance in the padding to the header in standard views.ws.

One solution is to add the "eyebrow" anchor of the Kodi logo to allow bottom alignment whilst still filling the vertical space to retain appropriate padding (e.g. [similar to what Netflix series do](https://logosarchive.com/wp-content/uploads/2022/08/Netflix-Wednesday-logo.png)). Another solution is having a variable sized font to switch from larger single line, to smaller double line and continue to fill the vertical space consistently.

All options have downsides:
Variable width = Laggy
Kodi logo = Extra clutter
Small font only = Visually unbalanced
Large font only = Longer titles truncated

Ultimately I decided last is best - more minimal if people complain about long titles they can turn on label scrolling.

**Comment by Rinicko100** [comment]
> > I'm a little confused though, If you don't mind explaining it to me🤔🤔... OfficerKD spotted a way to remove the kodi logo... and it didn't seem to affect anything
> 
> Not affecting function and not affecting visual balance are two separate things.
> 
> The issue is that the title font is significantly smaller than most clearlogos. This size difference creates visual balance issues with vertical space.
> 
> Vertically centering the title in the space creates a large disconnecting gap to the info/plot. Bottom aligning the title creates an imbalance in the padding to the header in standard views.
> 
> One solution is to add the "eyebrow" anchor of the Kodi logo to allow bottom alignment whilst still filling the vertical space to retain appropriate padding (e.g. [similar to what Netflix series do](https://logosarchive.com/wp-content/uploads/2022/08/Netflix-Wednesday-logo.png)). Another solution is having a variable sized font to switch from larger single line, to smaller double line and continue to fill the vertical space consistently.
> 
> All options have downsides:
> Variable height = Laggy
> Kodi logo = Extra clutter
> Small font only = Visually unbalanced
> Large font only = Longer titles truncated
> 
> Ultimately I decided last is best - It's the most performant option (less elements) and best suits the minimal style of the skin. If people complain about long titles not fitting then they they can turn on label scrolling.

I see 🤔🤔... I fully understand now. Thanks for the explanation... I also think large font with scrolling labels is best.. I'd probably reduce the font size on my end, but it's still better than the kodi logo for people who don't want to tinker with font.xml or use clearlogos

**Comment by xyzfre** [comment]
> Back to people whinging about the Kodi logo instead I guess it is then!
> 
> 

The Kodi logo use to look perfect the way you had it ,,way better Then having the large Fonts.

**Comment by vella9** [comment]
Was it ever considered creating a logo specifically to the skin? This can replace the kodi logo without too much trouble and can also be used elsewhere in the skin maybe. Just asking.

**Comment by xyzfre** [comment]
> Was it ever considered creating a logo specifically to the skin? This can replace the kodi logo without too much trouble and can also be used elsewhere in the skin maybe. Just asking.

This also sounds like a GREAT idea ,, and the fonts can go back to the way they were before which look way better ,maybe a Arctic Fuse logo🤔

**Comment by vella9** [comment]
> maybe a Arctic Fuse logo

that's what I thought. It would be a nice addition I think. Let's see if jurial likes the idea.
