### ISSUE TITLE
:bug: Issue with Trailers in Information Page

### ISSUE THREAD

**Issue by vella9** [jurialmunkey/skin.arctic.fuse#965]
### Skin section

Widgets

### Current Behavior

On 0.7.20, when trying to toggle trailer to fullscreen by pressing Trailer button in the information page, I am getting a black window/screen and the buttons to toggle fullscreen, stop and pause are not visible anymore as they used to before.

### Expected Behavior

trailer should resume in the window that pops up and buttons should be available once more to toggle fullscreen, pause or stop trailer.

### Steps To Reproduce

as per Current Behavior 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by OfficerKD637** [comment]
I think what's happening is clicking on the 'Trailer' button in the Info page stops the trailer playback (but only when the auto trailer in the info page is already playing).
Hence you get a black screen with only the replay button. Clicking on it will start the trailer from the beginning.

If you manage to beat the the timer by going to the info page and clicking on the trailer button before the auto trailer can start, the trailer actually plays inside the dialog like it's supposed to. And clicking back will keep it resumed in the background.

I assume this is because in [here](https://github.com/jurialmunkey/skin.arctic.fuse/blob/02f35c8028e6bcf43c56ef7eb408ebfacd14c664/1080i/Custom_1123_Dialog_Trailer.xml#L6) the condition is `Player.HasVideo` and not `!Player.HasVideo` which might conflict with the new Timers.xml onstart and onstop conditions.

But even if you change it to Player.HasVideo, it'll only fix it for cases when the Skin has both Spotlight and Info auto trailers enabled. That is, if the auto trailer starts playing in the Spotlight, and you click on Info and then the Trailer button, the video will keep playing throughout without restarting the trailer.
But if you only have Info Auto trailer enabled (but Spotlight trailer disabled), going to the Info page and once the auto trailer starts, clicking on the trailer button will restart the trailer everytime. Hitting back from the trailer window will keep it resumed in the background but clicking it again will restart the trailer.

Also, @jurialmunkey I had a question if you don't mind. I know you have repeatedly said that Kodi always overrides back when a video is playing to make it full screen, but I noticed in these last few versions (after Timers.xml was implemented and Alarms were removed) if you go to the Info page of any item and the auto trailer starts playing (whether its in the Spotlight or even in any of your normal widgets) and you hit back, it takes you back to the home screen. Doesn't maximize the video! I thought it was a glitch but I think the move to Timers.xml has added a lot of hidden enhancements haha.

**Comment by jurialmunkey** [comment]
@OfficerKD637 -back is only overridden in home screen, nowhere else.

**Comment by OfficerKD637** [comment]
> @OfficerKD637 -back is only overridden in home screen, nowhere else.

Thanks for clarifying that! I think I have been tinkering around with the skin too much and losing my mind haha.
> 
> Also I think you're trying to fix an issue different to the one that is reported (it sounds like you're trying to keep trailers playing when info opens but that's not what this bug is). This bug is about the trailers dialog stopping the trailer playing, which I know the cause of due to a property set to the wrong window.

Oh I see... The changes I suggested here and in this [comment](https://github.com/jurialmunkey/skin.arctic.fuse/discussions/966#discussioncomment-9833662) seem to fix this issue and maintain the trailer playback continuity throughout moving between Spotlight and Info windows (which IMHO is a nice thing, maybe?). But maybe the code goes about it in a very roundabout way?

Would love to know your thoughts!

**Comment by vella9** [comment]
Thank you jurial!
